Repository Emurgo/yoroi-frontend, pull requests merged in 2018-12, with the labels that each got.

#129 Change all FIXMEs to TODOs
  .circleci/config.yml
  app/api/ada/adaWallet.js
  app/api/ada/index.js
  app/scripts/generateSTxs.js
  app/stores/ada/DaedalusTransferStore.js
  features/step_definitions/tx-history-steps.js
  features/support/webdriver.js
Labels: NFC

#138 Reorganize Specs folder
  README.md
  docs/specs/code/MIGRATE_YOROI.md
  docs/specs/meta/MEETING.md
  docs/specs/meta/TEMPLATE.md
  docs/specs/meta/TRIAGE.md
Labels: NFC

#132 Add all steps for to run CI locally
  features/README.md
  features/localCI/connect.sh
  features/localCI/create.sh
  features/localCI/new_build.sh
  features/localCI/post_copy.sh
  features/localCI/setup.sh
  features/localCI/wrap_command.sh
  features/support/default-wallet.json
  features/support/default-wallet.key
  features/support/default-wallet.key.lock
  package.json
Labels: NFC

#151 Fix various manage-translations problems
  .githooks/post-checkout
  README.md
  app/i18n/README.md
  docs/SETUP.md
  package.json
  translations/translation-runner.js
Labels: NFC

#167 Ruslan/refactoring internal methods
  app/api/ada/adaAddress.js
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaWallet.js
  app/api/ada/restoreAdaWallet.js
  app/scripts/generateSTxs.js
Labels: refactoring, small-scale change

#173 better development debugging source-map
  webpack/development.config.js
Labels: NFC

#175 trezor topbar icon
  app/assets/images/top-bar/with-trezor-logo-white.inline.svg
  app/components/topbar/TopBarCategory.js
  app/components/topbar/TopBarCategory.scss
  app/config/topbarConfig.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/toplevel/LoadingStore.js
  app/stores/toplevel/TopbarStore.js
Labels: WIP / DO NOT MERGE, small-scale change

#185 Fixing extra space
  app/components/layout/TopBarLayout.scss
  package-lock.json
Labels: bug (confirmed), downgraded, fix for next version

#199 Feature/footer help links
  app/assets/images/footer/buy-trezor.inline.svg
  app/assets/images/footer/how-to-connect-trezor.inline.svg
  app/assets/images/footer/how-to-create-wallet.inline.svg
  app/assets/images/footer/how-to-restore-wallet.inline.svg
  app/assets/images/footer/what-is-hardware-wallet.inline.svg
  app/components/footer/HelpLinkFooter.js
  app/components/footer/HelpLinkFooter.scss
  app/components/layout/TopBarLayout.js
  app/components/layout/TopBarLayout.scss
  app/components/wallet/WalletAdd.scss
  app/components/wallet/trezorConnect/common/HelpLinkBlock.scss
  app/containers/MainLayout.js
  app/containers/wallet/Wallet.js
  app/containers/wallet/WalletAddPage.js
  app/i18n/locales/en-US.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  app/themes/prebuilt/yoroi.js
Labels: small-scale change
