Repository Emurgo/yoroi-frontend, pull requests merged in 2018-11, with the labels that each got.

#100 Cleanup Readmes
  README.md
  app/i18n/README.md
  docs/RELEASE.md
  docs/SETUP.md
Labels: NFC

#92 Design documentation & cleanup
  .eslintrc
  app/README.md
  app/actions/README.md
  app/actions/ada/ada-redemption-actions.js
  app/actions/ada/index.js
  app/actions/ada/node-update-actions.js
  app/api/README.md
  app/api/ada/adaAccount.js
  app/api/ada/adaAddress.js
  app/api/ada/adaLocalStorage.js
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaTransactionsHistory.js
  app/api/ada/adaTypes.js
  app/api/ada/adaWallet.js
  app/api/ada/daedalusTransfer.js
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoToModel.js
  app/api/ada/lib/cardanoCrypto/cryptoUtils.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/lovefieldDatabase.js
  app/api/ada/lib/utils.js
  app/api/ada/lib/yoroi-backend-api.js
  app/api/ada/restoreAdaWallet.js
  app/api/common.js
  app/assets/README.md
  app/components/README.md
  app/components/layout/TopBar.js
  app/config/README.md
  app/containers/README.md
  app/domain/README.md
  app/domain/Wallet.js
  app/scripts/generateSTxs.js
  app/stores/README.md
  app/stores/TransactionsStore.js
  app/stores/ada/AdaWalletSettingsStore.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/index.js
  app/stores/index.js
  app/stores/lib/Store.js
  app/types/README.md
  app/types/daedalusTransferTypes.js
  chrome/README.md
  chrome/assets/img/ada-logo.inline.svg
  chrome/assets/img/ada-symbol-smallest-dark.inline.svg
  chrome/assets/img/ada-symbol-smallest-white.inline.svg
  chrome/assets/img/ada-symbol.inline.svg
  chrome/assets/img/cardano-logo-white.inline.svg
  chrome/assets/img/receive-ic.svg
  chrome/assets/img/send-ic.svg
  chrome/extension/index.js
  config/config-types.js
  flow/declarations/CardanoCrypto.js
Labels: NFC

#106 fix of typo
  docs/SETUP.md
Labels: NFC

#113 fix bad README merge
  README.md
  docs/SETUP.md
Labels: NFC

#101 Draft triage system
  docs/specs/TRIAGE.md
Labels: NFC, new scenario (desired)

#102 First version of meeting spec
  docs/specs/MEETING.md
Labels: NFC, new scenario (desired)

#103 first version of spec template
  docs/specs/TEMPLATE.md
Labels: NFC, new scenario (desired)

#114 Cleanup Store folder & associated code
  .eslintrc
  app/README.md
  app/api/ada/adaWallet.js
  app/api/ada/index.js
  app/api/common.js
  app/api/localStorage/index.js
  app/components/daedalusTransfer/DaedalusTransferSummaryPage.js
  app/components/layout/TopBar.js
  app/config/transactionAssuranceConfig.js
  app/containers/TopBarContainer.js
  app/containers/daedalusTransfer/DaedalusTransferPage.js
  app/containers/settings/Settings.js
  app/containers/settings/categories/WalletSettingsPage.js
  app/containers/wallet/Wallet.js
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/WalletReceivePage.js
  app/containers/wallet/WalletSendPage.js
  app/containers/wallet/WalletSummaryPage.js
  app/containers/wallet/dialogs/ChangeWalletPasswordDialogContainer.js
  app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  app/environment.js
  app/stores/AppStore.js
  app/stores/LoadingStore.js
  app/stores/ProfileStore.js
  app/stores/README.md
  app/stores/SidebarStore.js
  app/stores/UiDialogsStore.js
  app/stores/UiNotificationsStore.js
  app/stores/WalletBackupStore.js
  app/stores/ada/AdaAddressesStore.js
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/AdaWalletSettingsStore.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/index.js
  app/stores/base/AddressesStore.js
  app/stores/base/TransactionsStore.js
  app/stores/base/WalletSettingsStore.js
  app/stores/base/WalletStore.js
  app/stores/index.js
  app/stores/lib/CachedRequest.js
  app/stores/lib/LocalizedCachedRequest.js
  app/stores/lib/Reaction.js
  app/stores/lib/Store.js
  app/types/transactionAssuranceTypes.js
  app/utils/imports.js
  app/utils/logging.js
  config/config-types.js
  features/step_definitions/common-steps.js
Labels: NFC

#118 PR feedback for Store Cleanup PR
  app/stores/README.md
  app/stores/ada/DaedalusTransferStore.js
  app/stores/base/AddressesStore.js
  app/stores/base/Store.js
  app/stores/base/TransactionsStore.js
  app/stores/base/WalletSettingsStore.js
  app/stores/base/WalletStore.js
  app/stores/index.js
  app/stores/toplevel/AppStore.js
  app/stores/toplevel/LoadingStore.js
  app/stores/toplevel/ProfileStore.js
  app/stores/toplevel/SidebarStore.js
  app/stores/toplevel/UiDialogsStore.js
  app/stores/toplevel/UiNotificationsStore.js
  app/stores/toplevel/WalletBackupStore.js
  app/utils/formatters.js
  app/utils/imports.js
Labels: NFC

#120 Fix flow error in Stores index
  app/stores/ada/index.js
  app/stores/index.js
Labels: NFC

#124 Enable React devtools
  README.md
  chrome/manifest.development.json
  chrome/views/main_window.pug
  docs/SETUP.md
  docs/TOOLS.md
Labels: NFC

#125 Spec for Migrate Yoroi Wallet feature
  docs/specs/MIGRATE_YOROI.md
Labels: new scenario (desired)

#121 Cleanup Features folder
  .eslintrc
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaTransactionsHistory.js
  app/api/ada/adaWallet.js
  app/api/ada/lib/yoroi-backend-api.js
  app/api/ada/restoreAdaWallet.js
  app/stores/ada/DaedalusTransferStore.js
  features/step_definitions/.eslintrc
  features/step_definitions/addresses-generation-steps.js
  features/step_definitions/common-steps.js
  features/step_definitions/daedalus-transfer-steps.js
  features/step_definitions/general-settings-steps.js
  features/step_definitions/installation-procedure-steps.js
  features/step_definitions/main-ui-steps.js
  features/step_definitions/select-language-steps.js
  features/step_definitions/settings-ui-steps.js
  features/step_definitions/transactions-steps.js
  features/step_definitions/tx-history-steps.js
  features/step_definitions/wallet-creation-steps.js
  features/step_definitions/wallet-restoration-steps.js
  features/step_definitions/wallet-steps.js
  features/support/helpers/helpers.js
  features/support/helpers/i18n-helpers.js
  features/support/helpers/language-selection-helpers.js
  features/support/helpers/route-helpers.js
  features/support/helpers/terms-of-use-helpers.js
  features/support/mockData.json
  features/support/mockDataBuilder.js
  features/support/mockDataTypes.js
  features/support/mockServer.js
  features/support/mockWebSocketServer.js
  features/support/webdriver.js
  package.json
Labels: NFC

#130 Simple readme for features folder
  features/README.md
Labels: NFC
