Repository Emurgo/yoroi-frontend, pull requests merged in 2019-03, with the labels that each got.

#323 1.3.1 Version bump
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  package-lock.json
  package.json
Labels: bug (confirmed)

#324 Fix missing numbering on ToS for Traditional Chinese
  app/i18n/locales/terms-of-use/ada/zh-Hant.md
Labels: UI/UX, bug (confirmed)

#325 Some new assets
  app/assets/images/lock screen-disabled.inline.svg
  app/assets/images/lock screen-enabled.inline.svg
  app/assets/images/lock.inline.svg
  app/assets/images/locked.inline.svg
  app/assets/images/top-bar/daedalus-migration-active.inline.svg
  app/assets/images/top-bar/daedalus-transfer.inline.svg
  app/assets/images/top-bar/setting-active.inline.svg
  app/assets/images/top-bar/settings-ic.inline.svg
  app/assets/images/top-bar/yoroi-migration-active.inline.svg
  app/components/topbar/TopBarCategory.scss
  app/config/topbarConfig.js
Labels: UI/UX

#328 Fix position of About Yoroi
  app/components/settings/menu/SettingsMenu.js
Labels: bug (confirmed)

#333 Fix Conflicting SVG ids
  package-lock.json
  package.json
  webpack/development.config.js
Labels: bug (confirmed), fix for next version, regression

#337 Remove unused CSS
  app/components/wallet/summary/WalletSummary.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: NFC

#335 Feature/enable themes
  app/components/settings/categories/DisplaySettings.js
  app/components/settings/categories/DisplaySettings.scss
  app/components/settings/categories/display/ThemeThumbnail.js
  app/components/settings/menu/SettingsMenu.js
  app/containers/settings/categories/DisplaySettingsPage.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: UI/UX

#334 Update TrezorConnect API to v7
  app/api/ada/hardwareWallet/trezorNewTransactions.js
  app/api/ada/lib/test-config.js
  app/config.js
  app/domain/TrezorSignTx.js
  app/i18n/locales/Indonesian.json
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  app/stores/ada/TrezorConnectStore.js
  chrome/3rd-party/trezor/trezor-usb-permissions.html
  config/config-types.js
  config/development.json
  config/mainnet.json
  config/staging.json
  config/test.json
  config/testnet.json
  docs/specs/code/TREZOR_INTEGRATION.md
  package-lock.json
  package.json
Labels: fix for next version

#340 SVG Loader on all mainnets + remove stale cleanups
  app/components/footer/FooterItem.js
  app/components/loading/Loading.js
  app/components/topbar/TopBarCategory.js
  app/components/wallet/WalletReceive.js
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/summary/WalletSummary.js
  app/components/wallet/transactions/Transaction.js
  app/components/wallet/transactions/TransactionTypeIcon.js
  app/components/wallet/trezorConnect/AboutDialog.js
  app/components/wallet/trezorConnect/ConnectDialog.js
  app/components/wallet/trezorConnect/SaveDialog.js
  app/components/wallet/trezorConnect/common/HelpLinkBlock.js
  app/components/widgets/DialogBackButton.js
  app/components/widgets/DialogCloseButton.js
  app/components/widgets/NotificationMessage.js
  app/components/widgets/ProgressSteps.js
  app/components/widgets/forms/AdaCertificateUploadWidget.js
  webpack/development.config.js
  webpack/mainnet.config.js
  webpack/staging.config.js
  webpack/test.config.js
  webpack/testnet.config.js
Labels: bug (confirmed)

#281 [spec] Ledger Integration
  docs/specs/code/ledger-integration/BOLOS_SDK_SETUP.md
  docs/specs/code/ledger-integration/FIRMWARE_UPDATE.md
  docs/specs/code/ledger-integration/README.md
Labels: triage-approved

#354 fix of #353
  app/containers/footer/AddWalletFooter.js
  app/i18n/locales/Indonesian.json
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: bug (confirmed), fix for next version

#322 Fix Desync issue
  app/api/ada/adaAddress.js
  app/api/ada/adaLocalStorage.js
  app/api/ada/adaMigration.js
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaTransactionsHistory.js
  app/api/ada/adaTypes.js
  app/api/ada/adaWallet.js
  app/api/ada/hardwareWallet/createWallet.js
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/api/ada/lib/adaAddressProcessing.js
  app/api/ada/lib/lovefieldDatabase.js
  app/api/ada/lib/utils.js
  app/api/ada/restoreAdaWallet.js
  app/api/index.js
  app/api/localStorage/index.js
  app/components/settings/categories/AboutYoroiSettings.js
  app/containers/wallet/WalletReceivePage.js
  app/environment.js
  app/scripts/generateSTxs.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/TrezorSendStore.js
  app/stores/base/AddressesStore.js
  app/stores/index.js
  app/stores/toplevel/LoadingStore.js
  app/stores/toplevel/ProfileStore.js
  app/utils/logging.js
  chrome/README.md
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  chrome/manifest.test.json
  chrome/manifest.testnet.json
  features/addresses-generation.feature
  features/migration.feature
  features/step_definitions/common-steps.js
  features/step_definitions/migration-steps.js
  features/step_definitions/transactions-steps.js
  features/support/mockData.json
  features/support/mockDataBuilder.js
  features/support/webdriver.js
  features/transactions.feature
  features/wallet-restoration.feature
  package-lock.json
  package.json
Labels: bug (confirmed)

#360 Remove height restriction
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, bug (confirmed)

#363 Add Ledger address verification
  app/actions/ada/hw-verify-address-actions.js
  app/actions/ada/index.js
  app/api/ada/index.js
  app/assets/images/search-ic-dark.inline.svg
  app/assets/images/search-ic.svg
  app/components/wallet/WalletAdd.js
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletReceive.scss
  app/components/wallet/receive/AddressDetailsDialog.js
  app/components/wallet/receive/AddressDetailsDialog.scss
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/containers/wallet/WalletReceivePage.js
  app/domain/LedgerLocalizedError.js
  app/domain/WalletAddress.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  app/stores/ada/HWVerifyAddressStore.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/index.js
  package-lock.json
  package.json
Labels: fix for next version, small-scale change

#365 Add verify function on Trezor
  app/containers/wallet/WalletReceivePage.js
  app/domain/TrezorLocalizedError.js
  app/stores/ada/HWVerifyAddressStore.js
  app/stores/ada/TrezorSendStore.js
  package-lock.json
  package.json
Labels: small-scale change

#358 Limit max height of dropdown selection
  app/themes/overrides/OptionsOverrides.scss
  features/step_definitions/select-language-steps.js
Labels: UI/UX, bug (confirmed), fix for next version

#368 Add Ledger Affiliate and documentation link [ch126]
  app/components/wallet/hwConnect/ledger/AboutDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/HelpLinkBlock.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/containers/footer/AddWalletFooter.js
  app/i18n/locales/Indonesian.json
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: UI/UX, fix for next version

#367 Replace Ledger logo
  app/assets/images/top-bar/with-ledger-nano-s-logo-white.inline.svg
  app/assets/images/top-bar/with-ledger-nano-s-logo.inline.svg
  app/components/topbar/TopBarCategory.js
  app/components/topbar/TopBarCategory.scss
  app/config/topbarConfig.js
Labels: fix for next version

#369 New Crowdin translations
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: fix for next version

#371 Change test version number
  app/api/ada/adaMigration.js
  features/step_definitions/migration-steps.js
Labels: bug (confirmed)
