Repository Emurgo/yoroi-frontend, pull requests merged in 2019-06, with the labels that each got.

#536 Fix encoding for background page for non-EN users
  chrome/views/background.html
Labels: bug (confirmed)

#538 shin/ch1230/make-new-theme-top-bar-height-same-as-old
  app/assets/images/top-bar/with-trezor-t-logo-white.inline.svg
  app/components/layout/TopBarLayout.scss
  app/components/topbar/TopBar.scss
  app/components/topbar/TopBarCategory.scss
  app/themes/prebuilt/Common.js
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#541 Update bignumber
  package-lock.json
  package.json
Labels: NFC

#542 Add new icon
  chrome/assets/img/icon-128.png
  chrome/assets/img/icon-16.png
  chrome/assets/img/icon-48.png
Labels: UI/UX

#543 Bump axios version
  package-lock.json
  package.json
Labels: NFC

#539 shin/ch1228/sync-receive-page-with-new-design
  app/assets/images/verify-icon.inline.svg
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletReceive.scss
  app/components/wallet/receive/VerifyAddressDialog.js
  app/components/wallet/receive/VerifyAddressDialog.scss
  app/containers/wallet/WalletReceivePage.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: UI/UX

#545 shin/ch1248/update-new-yoroi-staging-endpoint
  chrome/manifest.development.json
  chrome/manifest.staging.json
  config/development.json
  config/staging.json
Labels: NFC

#546 Transactions Table Responsive
  app/components/wallet/transactions/Transaction.scss
Labels: UI/UX

#547 shin/ch1232/fix-all-top-bar-icon-color-and-selection
  app/components/topbar/TopBarCategory.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#549 Shin/ch1264/sync hw connect dialog with new proposal
  app/actions/ada/hw-connect-actions.js
  app/assets/images/hardware-wallet/check-prerequisite-header-icon.inline.svg
  app/assets/images/hardware-wallet/ledger/check-modern.inline.svg
  app/assets/images/hardware-wallet/ledger/check.inline.svg
  app/assets/images/hardware-wallet/trezor/check-modern.inline.svg
  app/assets/images/hardware-wallet/trezor/check.inline.svg
  app/components/wallet/hwConnect/common/CheckDialog.scss
  app/components/wallet/hwConnect/common/DialogCommonStyle.scss
  app/components/wallet/hwConnect/common/ProgressStepBlock.js
  app/components/wallet/hwConnect/common/SaveDialog.scss
  app/components/wallet/hwConnect/ledger/CheckDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/CheckDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/widgets/DialogCloseButton.scss
  app/containers/footer/AddWalletFooter.js
  app/containers/wallet/dialogs/WalletLedgerConnectDialogContainer.js
  app/containers/wallet/dialogs/WalletTrezorConnectDialogContainer.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/routes-config.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/TrezorConnectStore.js
  app/types/HWConnectStoreTypes.js
Labels: UI/UX, small-scale change

#552 Terms Checkbox Block Sticky
  app/components/profile/terms-of-use/TermsOfUseForm.js
  app/components/profile/terms-of-use/TermsOfUseForm.scss
  app/components/profile/terms-of-use/TermsOfUseText.js
  app/components/profile/terms-of-use/TermsOfUseText.scss
Labels: UI/UX

#556 Add Spanish + Italian
  app/App.js
  app/assets/images/flags/italian.inline.svg
  app/assets/images/flags/spanish.inline.svg
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/toplevel/ProfileStore.js
  crowdin.yml
Labels: UI/UX

#551 shin/ch1263/add-spending-password-to-the-change-password
  app/components/wallet/WalletSettings.js
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#540 Refactor SendPage
  app/actions/ada/index.js
  app/actions/ada/ledger-send-actions.js
  app/actions/ada/trezor-send-actions.js
  app/actions/ada/tx-builder-actions.js
  app/actions/ada/wallets-actions.js
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaNewTransactions.test.js
  app/api/ada/adaTypes.js
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/api/ada/lib/adaAddressProcessing.js
  app/api/ada/lib/utils.js
  app/components/wallet/send/HWSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/send/WalletSendForm.scss
  app/components/widgets/forms/WarningBox.js
  app/components/widgets/forms/WarningBox.scss
  app/containers/wallet/WalletSendPage.js
  app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/ada/AdaTransactionBuilderStore.js
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/index.js
  app/stores/base/Store.js
  app/utils/formatters.js
  features/daedalus-transfer.feature
  features/mock-chain/mockImporter.js
  features/mock-chain/mockServer.js
  features/step_definitions/common-steps.js
  features/step_definitions/daedalus-transfer-steps.js
  features/step_definitions/transactions-steps.js
  features/transactions.feature
  features/tx-history.feature
  flow/declarations/cardano-wasm.js
  package-lock.json
  package.json
Labels: UI/UX, bug (confirmed)

#557 Add error when unable to load Yoroi
  app/components/loading/Loading.js
  app/components/settings/categories/SupportSettings.js
  app/containers/LoadingPage.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/toplevel/LoadingStore.js
Labels: UI/UX

#531 Wallet Add Classic Theme
  app/assets/images/add-wallet-picture.svg
  app/assets/images/add-wallet/add-wallet-bg-modern.inline.svg
  app/assets/images/add-wallet/connect-hw-classic.inline.svg
  app/assets/images/add-wallet/connect-hw-modern.inline.svg
  app/assets/images/add-wallet/create-wallet-classic.inline.svg
  app/assets/images/add-wallet/create-wallet-modern.inline.svg
  app/assets/images/add-wallet/option-dialog/connect-ledger-classic.inline.svg
  app/assets/images/add-wallet/option-dialog/connect-ledger-modern.inline.svg
  app/assets/images/add-wallet/option-dialog/connect-trezor-classic.inline.svg
  app/assets/images/add-wallet/option-dialog/connect-trezor-modern.inline.svg
  app/assets/images/add-wallet/option-dialog/restore-normal-wallet-classic.inline.svg
  app/assets/images/add-wallet/option-dialog/restore-normal-wallet-modern.inline.svg
  app/assets/images/add-wallet/option-dialog/restore-paper-wallet-classic.inline.svg
  app/assets/images/add-wallet/option-dialog/restore-paper-wallet-modern.inline.svg
  app/assets/images/add-wallet/restore-wallet-classic.inline.svg
  app/assets/images/add-wallet/restore-wallet-modern.inline.svg
  app/assets/images/top-bar/daedalus-migration-active.inline.svg
  app/assets/images/top-bar/daedalus-migration.inline.svg
  app/assets/images/wallets/business_wallet.svg
  app/assets/images/wallets/master_key.svg
  app/assets/images/yoroi-logo-white.inline.svg
  app/components/layout/TopBarLayout.js
  app/components/wallet/WalletAdd.js
  app/components/wallet/WalletAdd.scss
  app/components/wallet/WalletAddModern.js
  app/components/wallet/WalletConnectHardwareDialog.js
  app/components/wallet/WalletCreateDialog.scss
  app/components/wallet/WalletCreateListDialog.js
  app/components/wallet/WalletRestoreOptionsDialog.js
  app/components/wallet/WalletTypeItem.js
  app/components/wallet/WalletTypeItem.scss
  app/components/wallet/add/option-dialog/OptionBlock.js
  app/components/wallet/add/option-dialog/OptionBlock.scss
  app/components/wallet/add/option-dialog/OptionListWrapperStyle.scss
  app/components/wallet/add/option-dialog/WalletConnectHWOptionDialog.js
  app/components/wallet/add/option-dialog/WalletRestoreOptionDialog.js
  app/components/widgets/Dialog.scss
  app/containers/MainLayout.js
  app/containers/profile/LanguageSelectionPage.js
  app/containers/wallet/Wallet.js
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/dialogs/WalletConnectHWOptionDialogContainer.js
  app/containers/wallet/dialogs/WalletCreateListDialogContainer.js
  app/containers/wallet/dialogs/WalletRestoreOptionDialogContainer.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/themes/overrides/ModalOverrides.scss
  app/themes/prebuilt/Common.js
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  features/step_definitions/common-steps.js
  features/step_definitions/general-settings-steps.js
  features/step_definitions/wallet-creation-steps.js
  features/step_definitions/wallet-restoration-steps.js
Labels: UI/UX

#554 Fix sequential execution of fee requests
  app/components/wallet/send/WalletSendForm.js
  app/stores/ada/AdaTransactionBuilderStore.js
  app/stores/lib/Request.js
Labels: bug (confirmed), question

#558 Update react-polymorph and remove hack
  app/themes/overrides/OptionsOverrides.scss
  app/themes/overrides/OptionsOverridesClassic.scss
  app/themes/skins/AutocompleteOwnSkin.js
  package-lock.json
  package.json
Labels: UI/UX, WIP / DO NOT MERGE

#566 Wingdings as default on dev
  app/App.js
  app/themes/index.global.scss
Labels: NFC, UI/UX

#568 Add change I forgot to push
  app/components/settings/categories/SupportSettings.js
  app/containers/LoadingPage.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/toplevel/LoadingStore.js
Labels: UI/UX, bug (confirmed)

#569 Add wallet icons classic size fix
  app/assets/images/add-wallet/connect-hw-classic.inline.svg
  app/assets/images/add-wallet/create-wallet-classic.inline.svg
  app/assets/images/add-wallet/restore-wallet-classic.inline.svg
Labels: UI/UX

#570 Update NUMBER_PLATES.md
  docs/specs/code/NUMBER_PLATES.md
Labels: NFC

#560 Explorer integration (1/3)
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletReceive.scss
  app/components/widgets/hashWrappers/ExplorableHash.js
  app/components/widgets/hashWrappers/ExplorableHash.scss
  app/components/widgets/hashWrappers/RawHash.js
  app/components/widgets/hashWrappers/RawHash.scss
  app/components/widgets/hashWrappers/UsableHash.js
  app/components/widgets/hashWrappers/UsableHash.scss
  app/containers/widgets/ExplorableHashContainer.js
  app/i18n/locales/en-US.json
  app/themes/PolymorphThemes.js
  app/themes/overrides/index.js
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  app/utils/routing.js
Labels: small-scale change

#571 Add warning for slow internet connections on Daedalus transfer
  app/components/transfer/AnnotatedLoader.js
  app/components/transfer/AnnotatedLoader.scss
  app/containers/transfer/DaedalusTransferWaitingPage.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#580 Bump timeout for real
  features/step_definitions/common-steps.js
  features/support/webdriver.js
Labels: NFC

#581 shin/fix-learn-more-text
  app/components/wallet/add/option-dialog/WalletRestoreOptionDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#561 shin/Fix-TOU-page
  app/components/profile/terms-of-use/TermsOfUseForm.js
  app/components/profile/terms-of-use/TermsOfUseForm.scss
  app/components/profile/terms-of-use/TermsOfUseText.scss
  app/i18n/locales/en-US.json
  features/installation-procedure.feature
  features/step_definitions/installation-procedure-steps.js
Labels: UI/UX

#583 Daedalus investigation
  app/api/ada/adaTransactions/adaNewTransactions.test.js
  app/api/ada/adaWallet.test.js
  app/api/ada/daedalusTransfer.js
  app/api/ada/daedalusTransfer.test.js
  app/api/ada/errors.js
  app/stores/ada/DaedalusTransferStore.js
  app/utils/logging.js
Labels: NFC

#585 Wallet recovery phrase hide for the last step
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
Labels: UI/UX

#527 shin/ch1204/change-daedalus-transfer-according-to-new
  app/components/transfer/TransferInstructionsPage.js
  app/components/transfer/TransferInstructionsPage.scss
  app/containers/transfer/DaedalusTransferInstructionsPage.js
  app/containers/transfer/DaedalusTransferPage.js
  app/i18n/locales/en-US.json
  features/daedalus-transfer.feature
  features/step_definitions/daedalus-transfer-steps.js
Labels: UI/UX, fix for next version

#608 Enable Italian on prod
  app/stores/toplevel/ProfileStore.js
Labels: UI/UX

#607 Disable hot reload on production
  babel.config.js
Labels: NFC

#614 Disable test that always fails
  features/ada-redemption.feature
Labels: NFC, regression

#565 Explorer integration (2/3)
  app/components/transfer/TransferSummaryPage.js
  app/components/transfer/TransferSummaryPage.scss
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletReceive.scss
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/components/wallet/WalletRestoreVerifyDialog.scss
  app/components/wallet/receive/VerifyAddressDialog.js
  app/components/wallet/receive/VerifyAddressDialog.scss
  app/components/wallet/send/HWSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/settings/paper-wallets/FinalizeDialog.js
  app/components/wallet/settings/paper-wallets/FinalizeDialog.scss
  app/components/wallet/transactions/Transaction.js
  app/components/wallet/transactions/Transaction.scss
  app/components/widgets/CopyableAddress.js
  app/components/widgets/CopyableAddress.scss
  app/components/widgets/hashWrappers/ExplorableHash.js
  app/components/widgets/hashWrappers/ExplorableHash.scss
  app/components/widgets/hashWrappers/RawHash.js
  app/components/widgets/hashWrappers/RawHash.scss
  app/components/widgets/hashWrappers/UsableHash.js
  app/components/widgets/hashWrappers/UsableHash.scss
  app/containers/widgets/ExplorableHashContainer.js
  app/i18n/locales/en-US.json
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  app/utils/routing.js
  features/step_definitions/addresses-generation-steps.js
  features/step_definitions/general-settings-steps.js
  features/step_definitions/main-ui-steps.js
Labels: fix for next version, small-scale change

#593 shin/new-theme-enable-and-small-fixes
  app/api/ada/index.js
  app/components/settings/categories/general-setting/ThemeSettingsBlock.js
  app/components/topbar/TopBarCategory.scss
  app/stores/toplevel/ProfileStore.js
Labels: fix for next version

#622 Bump package-lock.json
  package-lock.json
Labels: NFC, fix for next version

#595 Explorer integration (3/3)
  app/actions/profile-actions.js
  app/api/ada/index.js
  app/api/ada/lib/storage/adaLocalStorage.js
  app/api/ada/lib/storage/helpers.js
  app/components/settings/categories/general-setting/ExplorerSettings.js
  app/components/settings/categories/general-setting/ExplorerSettings.scss
  app/components/transfer/TransferSummaryPage.js
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/components/wallet/receive/VerifyAddressDialog.js
  app/components/wallet/send/HWSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/settings/paper-wallets/FinalizeDialog.js
  app/components/wallet/transactions/Transaction.js
  app/components/wallet/transactions/WalletTransactionsList.js
  app/containers/settings/categories/GeneralSettingsPage.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/transfer/DaedalusTransferSummaryPage.js
  app/containers/wallet/WalletReceivePage.js
  app/containers/wallet/WalletSendPage.js
  app/containers/wallet/WalletSummaryPage.js
  app/containers/wallet/dialogs/CreatePaperWalletDialogContainer.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  app/containers/widgets/ExplorableHashContainer.js
  app/domain/Explorer.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/toplevel/ProfileStore.js
  flow/declarations/utils.js
Labels: UI/UX, fix for next version, small-scale change

#623 shin/ch1451/fix-setting-button-disable-state-color
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, bug (confirmed), fix for next version, small-scale change

#626 shin/ch1455/fix-tx-pending-color
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, bug (confirmed), fix for next version, small-scale change

#624 shin/ch1453/fix-verify-restore-dialog-button-name
  app/components/wallet/WalletRestoreVerifyDialog.js
Labels: UI/UX, fix for next version, small-scale change

#625 Branch & Github links in About Yoroi
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.js
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.scss
  app/components/widgets/hashWrappers/ExplorableHash.js
  app/components/widgets/hashWrappers/ExplorableHash.scss
  app/environment.js
  app/i18n/locales/en-US.json
  webpack/commonConfig.js
Labels: UI/UX

#635 shin/ch1412/change-button-s-text-opacity-on-receive-page
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletReceive.scss
Labels: UI/UX, fix for next version, small-scale change

#634 shin/ch1472/fix-create-paper-wallet-password-margin
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.scss
Labels: UI/UX, bug (confirmed), fix for next version, small-scale change

#633 shin/ch1467/fix-about-yoroi-icon-font-same-as-text-block
  app/components/widgets/LinkButton.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, fix for next version, small-scale change

#636 shin/ch1402/increase-tab-height-from-40px-to-50px
  app/components/wallet/layouts/WalletWithNavigation.scss
  app/components/wallet/navigation/WalletNavButton.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, fix for next version, small-scale change

#628 Remove default letter-spcing on modern theme
  app/components/wallet/WalletAdd.scss
  app/themes/index.global.scss
Labels: UI/UX

#601 Bump to 1.7
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  chrome/manifest.test.json
  chrome/manifest.testnet.json
  package-lock.json
  package.json
Labels: NFC, fix for next version

#644 shin/ch1494/fix-fonts-for-windows-modern-theme
  app/assets/fonts/RobotoMono-Bold.ttf
  app/assets/fonts/RobotoMono-Light.ttf
  app/assets/fonts/RobotoMono-Medium.ttf
  app/assets/fonts/RobotoMono-Regular.ttf
  app/assets/fonts/RobotoMono-Thin.ttf
  app/assets/fonts/Rubik-Black.ttf
  app/assets/fonts/Rubik-Bold.ttf
  app/assets/fonts/Rubik-Light.ttf
  app/assets/fonts/Rubik-Medium.ttf
  app/assets/fonts/Rubik-Regular.ttf
  app/themes/index.global.scss
Labels: UI/UX, bug (confirmed), fix for next version

#567 Add flow to all files and fix related errors
  app/ThemeManager.js
  app/api/ada/index.js
  app/api/ada/lib/decrypt.js
  app/components/footer/FooterItem.js
  app/components/settings/SettingsLayout.js
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.js
  app/components/wallet/export/ExportTransactionDialog.js
  app/components/wallet/hwConnect/common/ProgressStepBlock.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/skins/AmountInputSkin.js
  app/components/wallet/transactions/Transaction.js
  app/components/widgets/BigButtonForDialogs.js
  app/components/widgets/Dialog.js
  app/components/widgets/DialogBackButton.js
  app/components/widgets/DialogCloseButton.js
  app/components/widgets/InformativeMessage.js
  app/components/widgets/LinkButton.js
  app/components/widgets/NotificationMessage.js
  app/components/widgets/ProgressSteps.js
  app/components/widgets/forms/PasswordInstructions.js
  app/config.js
  app/containers/footer/AddWalletFooter.js
  app/containers/settings/Settings.js
  app/containers/wallet/WalletSummaryPage.js
  app/domain/WalletTransaction.js
  app/i18n/errors.js
  app/i18n/global-messages.js
  app/i18n/translations.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/TrezorConnectStore.js
  app/themes/prebuilt/Common.js
  app/types/HWConnectStoreTypes.js
  app/utils/ReactToolboxMobxForm.js
  app/utils/form.js
  app/utils/routing.js
  app/utils/tabManager.js
  app/utils/validations.js
  chrome/3rd-party/trezor/trezor-usb-permissions.js
Labels: NFC

#648 Fix deprecation warning on componentWillMount
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/wallet/transactions/WalletTransactionsList.js
Labels: NFC

#649 Bump remaining Babel packages
  babel.config.js
  package-lock.json
  package.json
Labels: NFC

#642 shin/ch1510/margin-on-paper-wallet-dialog-is-too-small
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.js
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.scss
Labels: UI/UX, bug (confirmed), fix for next version, small-scale change

#653 Add missing scrollbar on HW dialogs
  app/components/wallet/hwConnect/common/DialogCommonStyle.scss
Labels: UI/UX, bug (confirmed)

#582 Refactoring old components styles
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/WalletRestoreDialog.scss
  app/components/wallet/backup-recovery/MnemonicWord.js
  app/components/wallet/backup-recovery/MnemonicWord.scss
  app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.scss
  app/components/wallet/backup-recovery/WalletRecoveryInstructions.js
  app/components/wallet/backup-recovery/WalletRecoveryInstructions.scss
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.scss
  app/components/wallet/backup-recovery/WalletRecoveryPhraseMnemonic.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseMnemonic.scss
  app/components/wallet/hwConnect/common/CheckDialog.scss
  app/components/wallet/hwConnect/common/ConnectDialog.scss
  app/components/wallet/hwConnect/common/DialogCommonStyle.scss
  app/components/wallet/hwConnect/common/SaveDialog.scss
  app/components/wallet/hwConnect/ledger/CheckDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/CheckDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/widgets/ProgressSteps.scss
  features/step_definitions/wallet-creation-steps.js
Labels: NFC

#659 shin/ch1567/use-handleexternallinkclick-method-for-opening-new
  app/components/footer/FooterItem.js
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.js
  app/components/wallet/hwConnect/ledger/CheckDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/HelpLinkBlock.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/CheckDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/HelpLinkBlock.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/widgets/LinkButton.js
  app/containers/footer/AddWalletFooter.js
  app/containers/wallet/dialogs/WalletLedgerConnectDialogContainer.js
  app/containers/wallet/dialogs/WalletTrezorConnectDialogContainer.js
  app/i18n/locales/en-US.json
Labels: NFC

#658 Specify new spending password on restore
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#660 shin/ch1562/update-ui-text-to-show-ledger-nano-x-as-supported
  app/components/footer/FooterItem.js
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.js
  app/components/wallet/hwConnect/ledger/CheckDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/HelpLinkBlock.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/CheckDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/HelpLinkBlock.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/widgets/LinkButton.js
  app/containers/footer/AddWalletFooter.js
  app/containers/wallet/dialogs/WalletLedgerConnectDialogContainer.js
  app/containers/wallet/dialogs/WalletTrezorConnectDialogContainer.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#689 Maybe fix Chrome tests?
  features/support/webdriver.js
Labels: bug (unconfirmed)

#661 shin/ch1395/fix-text-on-hw-connect-check-step-dialog
  app/components/wallet/hwConnect/trezor/CheckDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#702 Add lovefield types
  app/api/ada/lib/storage/lovefieldDatabase.js
  flow-typed/npm/lovefield_v2.x.x.js
Labels: NFC

#712 Add language and yoroi version to header requests
  app/api/ada/lib/state-fetch/remoteFetcher.js
  app/stores/ada/StateFetchStore.js
Labels: fix for next version, small-scale change

#711 Add missing back buttons
  app/components/uri/URIDisplayDialog.js
  app/components/uri/URIGenerateDialog.js
  app/components/wallet/hwConnect/ledger/CheckDialog.js
  app/components/wallet/hwConnect/trezor/CheckDialog.js
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/WalletReceivePage.js
  app/containers/wallet/dialogs/WalletLedgerConnectDialogContainer.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/containers/wallet/dialogs/WalletTrezorConnectDialogContainer.js
  app/i18n/locales/en-US.json
Labels: UI/UX, fix for next version

#710 V almonacid/ch1592/balance hide screen button
  app/actions/profile-actions.js
  app/api/localStorage/index.js
  app/assets/images/top-bar/password.hide.inline.svg
  app/assets/images/top-bar/password.show.inline.svg
  app/components/topbar/WalletTopbarTitle.js
  app/components/topbar/WalletTopbarTitle.scss
  app/containers/TopBarContainer.js
  app/stores/toplevel/ProfileStore.js
  features/main-ui.feature
  features/step_definitions/main-ui-steps.js
Labels: UI/UX, fix for next version
