Repository Emurgo/yoroi-frontend, pull requests merged in 2019-05, with the labels that each got.

#155 Spec for lock screen
  docs/specs/code/LOCK_WALLET_WITH_PIN.md
Labels: WIP / DO NOT MERGE, help wanted, proposal

#432 Add monospace font
  app/assets/fonts/RobotoMono-Bold.ttf
  app/assets/fonts/RobotoMono-Light.ttf
  app/assets/fonts/RobotoMono-Medium.ttf
  app/assets/fonts/RobotoMono-Regular.ttf
  app/assets/fonts/RobotoMono-Thin.ttf
  app/components/transfer/TransferSummaryPage.scss
  app/components/wallet/WalletReceive.scss
  app/components/wallet/receive/AddressDetailsDialog.scss
  app/components/wallet/send/HWSendConfirmationDialog.scss
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/send/WalletSendForm.scss
  app/components/wallet/transactions/Transaction.js
  app/components/wallet/transactions/Transaction.scss
  app/stores/toplevel/ProfileStore.js
  app/themes/index.global.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#433 Fix missing theme flag
  app/components/profile/terms-of-use/TermsOfUseText.js
  app/components/settings/categories/TermsOfUseSettings.js
  app/containers/settings/categories/TermsOfUseSettingsPage.js
Labels: UI/UX, bug (confirmed)

#434 New SCSS architecture
  app/App.js
  app/ThemeManager.js
  app/actions/index.js
  app/actions/theme-actions.js
  app/components/settings/categories/SupportSettings.js
  app/components/settings/categories/SupportSettings.scss
  app/containers/TopBarContainer.js
  app/containers/profile/LanguageSelectionPage.js
  app/containers/profile/TermsOfUsePage.js
  app/containers/settings/Settings.js
  app/containers/settings/categories/DisplaySettingsPage.js
  app/containers/settings/categories/SupportSettingsPage.js
  app/containers/settings/categories/WalletSettingsPage.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/wallet/AdaRedemptionPage.js
  app/containers/wallet/NoWalletsPage.js
  app/containers/wallet/Wallet.js
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/WalletReceivePage.js
  app/containers/wallet/WalletSendPage.js
  app/containers/wallet/WalletSummaryPage.js
  app/containers/wallet/dialogs/ChangeWalletPasswordDialogContainer.js
  app/containers/wallet/dialogs/CreatePaperWalletDialogContainer.js
  app/containers/wallet/dialogs/WalletLedgerConnectDialogContainer.js
  app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  app/containers/wallet/dialogs/WalletTrezorConnectDialogContainer.js
  app/stores/index.js
  app/stores/toplevel/ProfileStore.js
  app/stores/toplevel/ThemeStore.js
  app/themes/index.js
  app/themes/overrides/index.js
  app/types/injectedPropsType.js
Labels: UI/UX

#377 Revision to daedalusTransfer.instructions.attention.text
  app/i18n/locales/en-US.json
Labels: fix for next version, small-scale change

#418 Send All options
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaNewTransactions.test.js
  app/api/ada/adaTypes.js
  app/api/ada/daedalusTransfer.js
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/api/ada/lib/utils.js
  app/api/ada/lib/yoroi-backend-api.js
Labels: small-scale change

#437 Changing the theme type in DaedalusTransferFormPage
  app/components/transfer/TransferMnemonicPage.js
  app/components/wallet/transactions/Transaction.scss
  app/containers/transfer/DaedalusTransferFormPage.js
  app/containers/transfer/DaedalusTransferPage.js
Labels: UI/UX

#438 New SCSS architecture Lang selection page [ch922]
  app/components/profile/language-selection/LanguageSelectionForm.js
  app/components/profile/language-selection/LanguageSelectionForm.scss
  app/containers/profile/LanguageSelectionPage.js
Labels: NFC

#439 New SCSS architecture TOU page [ch923]
  app/components/profile/terms-of-use/TermsOfUseForm.js
  app/components/profile/terms-of-use/TermsOfUseForm.scss
  app/components/profile/terms-of-use/TermsOfUseText.js
  app/components/profile/terms-of-use/TermsOfUseText.scss
  app/containers/profile/TermsOfUsePage.js
  features/step_definitions/installation-procedure-steps.js
Labels: NFC

#441 New SCSS architecture Daedalus Transfer page [ch924]
  app/components/transfer/TransferInstructionsPage.js
  app/components/transfer/TransferInstructionsPage.scss
  app/components/transfer/TransferMasterKeyPage.js
  app/components/transfer/TransferMasterKeyPage.scss
  app/components/transfer/TransferMnemonicPage.js
  app/components/transfer/TransferMnemonicPage.scss
  app/components/transfer/TransferSummaryPage.js
  app/components/transfer/TransferSummaryPage.scss
  app/components/wallet/WalletReceive.js
  app/components/wallet/ada-redemption/AdaRedemptionForm.js
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/summary/WalletSummary.js
  app/components/widgets/BorderedBox.js
  app/components/widgets/BorderedBox.scss
  app/containers/transfer/DaedalusTransferFormPage.js
  app/containers/transfer/DaedalusTransferInstructionsPage.js
  app/containers/transfer/DaedalusTransferPage.js
Labels: NFC

#443 New SCSS architecture Send page [ch942]
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/send/WalletSendForm.scss
  features/step_definitions/transactions-steps.js
Labels: NFC

#452 Disable confirm button if boxes are unchecked
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
Labels: bug (confirmed)

#454 Wallet creation fix
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  app/stores/base/WalletStore.js
Labels: bug (confirmed)

#445 Decouple state fetching from api layer
  app/actions/ada/ada-redemption-actions.js
  app/actions/ada/addresses-actions.js
  app/actions/ada/daedalus-transfer-actions.js
  app/actions/ada/transactions-actions.js
  app/actions/ada/wallet-settings-actions.js
  app/actions/dialogs-actions.js
  app/actions/notifications-actions.js
  app/actions/profile-actions.js
  app/actions/wallet-backup-actions.js
  app/api/ada/adaRedemption.js
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaNewTransactions.test.js
  app/api/ada/adaTransactions/adaTransactionsHistory.js
  app/api/ada/adaWallet.js
  app/api/ada/daedalusTransfer.js
  app/api/ada/hardwareWallet/createWallet.js
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/api/ada/lib/adaAddressProcessing.js
  app/api/ada/lib/state-fetch/IFetcher.js
  app/api/ada/lib/state-fetch/helpers.js
  app/api/ada/lib/state-fetch/remoteFetcher.js
  app/api/ada/lib/state-fetch/types.js
  app/api/ada/lib/yoroi-backend-api.js
  app/api/ada/restoreAdaWallet.js
  app/api/common.js
  app/containers/settings/categories/WalletSettingsPage.js
  app/containers/wallet/AdaRedemptionPage.js
  app/containers/wallet/Wallet.js
  app/containers/wallet/WalletSummaryPage.js
  app/containers/wallet/dialogs/CreatePaperWalletDialogContainer.js
  app/stores/ada/AdaRedemptionStore.js
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/StateFetchStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/ada/TrezorSendStore.js
  app/stores/ada/index.js
  app/stores/base/TransactionsStore.js
  app/stores/base/WalletStore.js
  features/support/mockServer.js
Labels: NFC

#455 New flow-typed definitions
  app/api/ada/errors.js
  app/api/common.js
  app/components/layout/GridFlexContainer.js
  app/components/loading/Loading.js
  app/components/profile/language-selection/LanguageSelectionForm.js
  app/components/settings/categories/GeneralSettings.js
  app/components/settings/categories/PaperWalletSettings.js
  app/components/transfer/TransferInstructionsPage.js
  app/components/transfer/TransferMasterKeyPage.js
  app/components/transfer/TransferMnemonicPage.js
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/ada-redemption/AdaRedemptionForm.js
  app/components/wallet/hwConnect/trezor/AboutDialog.js
  app/components/wallet/send/HWSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendForm.js
  app/containers/transfer/DaedalusTransferErrorPage.js
  app/containers/transfer/DaedalusTransferFormPage.js
  app/containers/transfer/DaedalusTransferInstructionsPage.js
  app/containers/transfer/DaedalusTransferMasterKeyFormPage.js
  app/containers/wallet/WalletSendPage.js
  app/i18n/LocalizableError.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/lib/Request.js
  app/types/i18nTypes.js
  app/types/notificationType.js
  flow-typed/npm/axios_v0.18.x.js
  flow-typed/npm/bluebird_v3.x.x.js
  flow-typed/npm/classnames_v2.x.x.js
  flow-typed/npm/es6-error_v4.x.x.js
  flow-typed/npm/lodash_v4.x.x.js
  flow-typed/npm/react-copy-to-clipboard_v5.x.x.js
  flow-typed/npm/react-intl_v2.x.x.js
  flow-typed/npm/react-router_v4.x.x.js
  package.json
Labels: NFC

#448 Fix Shin/ch962/fix yoroiclassic theme regression bugs
  app/components/mixins/HeaderBlock.scss
  app/components/wallet/hwConnect/common/HelpLinkBlock.scss
  app/components/wallet/hwConnect/ledger/HelpLinkBlock.js
  app/components/wallet/hwConnect/trezor/HelpLinkBlock.js
  app/components/wallet/settings/paper-wallets/CreatePaperDialog.js
  app/components/wallet/settings/paper-wallets/CreatePaperDialog.scss
Labels: WIP / DO NOT MERGE, bug (confirmed)

#457 fix text on SET CUSTOM PAPER WALLET PASSWORD [ch969]
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.js
  app/components/widgets/forms/PasswordInstructions.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
Labels: fix for next version, small-scale change

#458 Fix Shin/ch962/fix yoroiclassic theme regression bugs-2
  app/components/wallet/hwConnect/common/DialogCommonStyle.scss
  app/components/wallet/hwConnect/ledger/AboutDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/AboutDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/widgets/ErrorBlock.js
Labels: bug (confirmed), fix for next version

#459 Fix checkbox & select dropdown
  app/themes/overrides/OptionsOverrides.scss
  app/themes/overrides/OptionsOverridesClassic.scss
  app/themes/overrides/SelectOverridesClassic.scss
Labels: UI/UX, bug (confirmed)

#460 Fix About Yoroi SVG on Firefox
  app/components/widgets/LinkButton.js
  app/components/widgets/LinkButton.scss
Labels: UI/UX, bug (confirmed)

#461 Fix incorrect words left count [ch1005]
  app/components/wallet/WalletRestoreDialog.js
Labels: bug (confirmed), fix for next version, small-scale change

#463 Fix string
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#462 Shin/ch1008/add words left count on daedalus transfer
  app/components/transfer/TransferMnemonicPage.js
  app/components/wallet/WalletRestoreDialog.js
  app/i18n/global-messages.js
  features/step_definitions/wallet-restoration-steps.js
Labels: fix for next version, small-scale change

#465 Fix error on 0-length paper wallet password
  app/components/wallet/WalletRestoreDialog.js
Labels: UI/UX

#464 Port from Shin's fix
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/widgets/forms/InlineEditingInput.js
Labels: bug (confirmed)

#467 Add missing scrollbar on two pages
  app/components/settings/SettingsLayout.scss
  app/components/wallet/WalletAdd.scss
Labels: UI/UX, bug (confirmed)

#466 Fix back button on hardware wallet send
  app/components/wallet/send/HWSendConfirmationDialog.js
  app/containers/wallet/WalletSendPage.js
Labels: UI/UX, bug (confirmed)

#469 Fix scrollbar on settings
  app/components/settings/SettingsLayout.scss
  app/components/settings/menu/SettingsMenu.scss
Labels: UI/UX, bug (confirmed)

#473 Rename ID to checksum to avoid user confusion
  app/components/settings/categories/PaperWalletSettings.js
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/components/wallet/settings/paper-wallets/FinalizeDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#471 Bump to version 1.6.0
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  chrome/manifest.test.json
  chrome/manifest.testnet.json
  package-lock.json
  package.json
Labels: NFC

#474 just a hint for firefox-dev installation
  docs/SETUP.md
Labels: small-scale change

#470 Fixing overlapping pre-filled values with floating labels
  app/themes/skins/FormFieldOwnSkin.scss
Labels: UI/UX

#475 Shin/ch1018/new scss architecture common components
  app/components/layout/TopBarLayout.js
  app/components/layout/TopBarLayout.scss
  app/components/topbar/TopBar.js
  app/components/topbar/TopBar.scss
  app/components/topbar/TopBarCategory.js
  app/components/topbar/TopBarCategory.scss
  app/components/topbar/banners/TestnetWarningBanner.js
  app/components/topbar/banners/TestnetWarningBanner.scss
  app/containers/MainLayout.js
  app/containers/TopBarContainer.js
  app/containers/profile/LanguageSelectionPage.js
  app/containers/profile/TermsOfUsePage.js
  app/containers/settings/Settings.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/wallet/WalletAddPage.js
  features/step_definitions/general-settings-steps.js
  features/step_definitions/wallet-steps.js
Labels: NFC

#472 Shin/ch1019/importing changes from closed pr 416
  app/App.js
  app/components/layout/TopBarLayout.js
  app/components/layout/TopBarLayout.scss
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletRestoreDialog.js
  app/containers/MainLayout.js
  app/containers/profile/LanguageSelectionPage.js
  app/containers/profile/TermsOfUsePage.js
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/WalletReceivePage.js
Labels: WIP / DO NOT MERGE, small-scale change

#482 shin/ch941/new-scss-architecture-transaction-page
  app/components/wallet/summary/WalletSummary.js
  app/components/wallet/summary/WalletSummary.scss
  app/components/wallet/transactions/Transaction.js
  app/components/wallet/transactions/Transaction.scss
  app/components/wallet/transactions/WalletNoTransactions.js
  app/components/wallet/transactions/WalletNoTransactions.scss
  app/components/wallet/transactions/WalletTransactionsList.js
  app/components/wallet/transactions/WalletTransactionsList.scss
  app/containers/wallet/WalletSummaryPage.js
  features/step_definitions/transactions-steps.js
  features/step_definitions/tx-history-steps.js
Labels: NFC

#483 shin/ch943/new-scss-architecture-receive-page
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletReceive.scss
  app/components/wallet/settings/paper-wallets/FinalizeDialog.js
  app/components/widgets/CopyableAddress.js
  app/components/widgets/CopyableAddress.scss
  app/containers/wallet/WalletReceivePage.js
  features/step_definitions/addresses-generation-steps.js
  features/step_definitions/main-ui-steps.js
Labels: NFC

#484 shin/ch1052/new-scss-architecture-widgets
  app/components/wallet/hwConnect/common/HWErrorBlock.js
  app/components/widgets/Dialog.js
  app/components/widgets/Dialog.scss
  app/components/widgets/ErrorBlock.js
  app/components/widgets/ErrorBlock.scss
  app/components/widgets/ProgressSteps.js
  app/components/widgets/ProgressSteps.scss
  app/components/widgets/forms/InlineEditingInput.js
  app/components/widgets/forms/InlineEditingInput.scss
  app/components/widgets/forms/ReadOnlyInput.js
  app/components/widgets/forms/ReadOnlyInput.scss
  features/step_definitions/settings-ui-steps.js
  features/step_definitions/wallet-creation-steps.js
  features/step_definitions/wallet-restoration-steps.js
Labels: NFC

#486 shin/ch1057/new-scss-architecture-miscellaneous-fix
  app/components/footer/FooterItem.js
  app/components/loading/Loading.scss
  app/components/topbar/WalletAccountIcon.scss
  app/components/topbar/WalletTopbarTitle.scss
  app/components/transfer/AnnotatedLoader.scss
  app/components/transfer/TransferMasterKeyPage.scss
  app/components/wallet/layouts/WalletWithNavigation.js
  app/components/wallet/navigation/WalletNavButton.js
  app/components/wallet/navigation/WalletNavButton.scss
  app/components/wallet/navigation/WalletNavigation.js
  app/components/wallet/skins/AmountInputSkin.js
  app/components/wallet/skins/AmountInputSkin.scss
  app/containers/wallet/Wallet.js
  features/step_definitions/transactions-steps.js
Labels: NFC

#487 Cleanup background script
  chrome/extension/background.js
  flow-typed/npm/bluebird_v3.x.x.js
  package-lock.json
  package.json
Labels: NFC

#492 Fix error logging
  app/utils/logging.js
Labels: NFC, bug (confirmed)

#476 Send All Feature
  app/actions/ada/wallets-actions.js
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaNewTransactions.test.js
  app/api/ada/index.js
  app/components/wallet/send/HWSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/send/WalletSendForm.scss
  app/containers/wallet/WalletSendPage.js
  app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/AdaWalletsStore.js
  features/step_definitions/transactions-steps.js
  features/support/mockData.json
  features/transactions.feature
Labels: small-scale change

#489 shin/ch1071/fix-formfieldownskin-react-warning-keys
  app/themes/skins/AutocompleteOwnSkin.js
Labels: bug (confirmed)

#485 V almonacid/ch1013/cardano uri scheme spec
  docs/specs/code/URI_SCHEME.md
  docs/specs/images/image1.gif
  docs/specs/images/image2.png
Labels: spec

#493 Shin/ch1096/fix dialog width in moderntheme
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/themes/overrides/AutocompleteOverrides.scss
  app/themes/overrides/ModalOverrides.scss
  app/themes/prebuilt/YoroiModern.js
  app/themes/skins/FormFieldOwnSkin.scss
Labels: bug (confirmed)

#496 Move batching code to single BatchFetcher
  app/api/ada/adaTransactions/adaTransactionsHistory.js
  app/api/ada/adaWallet.js
  app/api/ada/index.js
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/api/ada/lib/state-fetch/helpers.js
  app/api/ada/lib/state-fetch/remoteFetcher.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/StateFetchStore.js
Labels: NFC

#497 Update of new SCSS architecture(base at #434)
  app/App.js
  chrome/views/main_window.html
Labels: bug (confirmed)

#499 Fix empty string broken on crowdin
  app/components/profile/language-selection/LanguageSelectionForm.js
  app/components/settings/categories/GeneralSettings.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
Labels: UI/UX, bug (confirmed)

#500 Fix theme preview
  app/components/settings/categories/DisplaySettings.js
  app/components/settings/categories/DisplaySettings.scss
  app/components/settings/categories/display/ThemeThumbnail.js
  app/i18n/global-messages.js
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, bug (confirmed)

#501 [ClassicTheme] fix CREATE A NEW WALLET dialog
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletCreateDialog.scss
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.js
  app/components/widgets/forms/PasswordInstructions.js
  app/components/widgets/forms/PasswordInstructions.scss
Labels: bug (confirmed)

#491 Yoroi storage spec
  docs/specs/code/STORAGE.md
  docs/specs/code/storage_spec.png
  docs/specs/code/storage_spec.svg
Labels: spec

#504 fix transactions page
  app/components/wallet/transactions/Transaction.js
  app/components/wallet/transactions/Transaction.scss
Labels: bug (confirmed)

#509 shin/fix-ledger-connect-save-stage-asset
  app/assets/images/hardware-wallet/ledger/save-error-modern.inline.svg
  app/assets/images/hardware-wallet/ledger/save-load-modern.inline.svg
Labels: bug (confirmed)

#513 Fix 4 bugs in wallet creation & restoration
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/components/wallet/WalletRestoreVerifyDialog.scss
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/base/WalletStore.js
Labels: bug (confirmed)

#447 Sebastiengllmt/ch949/decouple storage from api layer
  app/api/ada/adaRedemption.js
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaTransactionsHistory.js
  app/api/ada/adaTypes.js
  app/api/ada/adaWallet.js
  app/api/ada/daedalusTransfer.js
  app/api/ada/hardwareWallet/createWallet.js
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/api/ada/lib/state-fetch/helpers.js
  app/api/ada/lib/state-fetch/remoteFetcher.js
  app/api/ada/lib/storage/AdaTypesConfig.js
  app/api/ada/lib/storage/adaAccount.js
  app/api/ada/lib/storage/adaAddress.js
  app/api/ada/lib/storage/adaLocalStorage.js
  app/api/ada/lib/storage/adaMigration.js
  app/api/ada/lib/storage/cryptoToModel.js
  app/api/ada/lib/storage/helpers.js
  app/api/ada/lib/storage/lovefieldDatabase.js
  app/api/ada/lib/storage/types.js
  app/api/ada/lib/utils.js
  app/api/ada/paperWallet/paperWalletPdf.js
  app/api/ada/restoreAdaWallet.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/stores/ada/AdaRedemptionStore.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/StateFetchStore.js
  features/step_definitions/tx-history-steps.js
  features/support/mockDataTypes.js
  features/support/webdriver.js
  features/wallet-restoration.feature
Labels: NFC

#510 shin/ch1149/increase-padding-between-tabs-and-content
  app/components/wallet/hwConnect/common/DialogCommonStyle.scss
  app/components/wallet/hwConnect/common/SaveDialog.scss
  app/components/wallet/hwConnect/ledger/AboutDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/AboutDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
Labels: bug (confirmed)

#514 shin/ch1163/create-wallet-recover-phrase-dialog-fix
  app/components/wallet/backup-recovery/WalletRecoveryInstructions.scss
  app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.scss
  app/components/wallet/backup-recovery/WalletRecoveryPhraseMnemonic.scss
Labels: small-scale change

#515 Fix ref usage
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/widgets/forms/InlineEditingInput.js
Labels: bug (confirmed)

#508 Adding translation for Total Balance string in the topbar
  app/components/topbar/WalletTopbarTitle.js
  app/i18n/locales/en-US.json
Labels: small-scale change

#521 Fix flag orientation
  app/assets/images/flags/german.inline.svg
Labels: NFC, UI/UX

#519 shin/ch1165/sync-transactions-page-with-proposed-design-2
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  app/components/wallet/summary/WalletSummary.scss
  app/components/wallet/transactions/Transaction.js
  app/components/wallet/transactions/Transaction.scss
  app/components/wallet/transactions/WalletNoTransactions.js
  app/components/wallet/transactions/WalletNoTransactions.scss
  app/components/wallet/transactions/WalletTransactionsList.js
  app/components/wallet/transactions/WalletTransactionsList.scss
  app/containers/wallet/WalletSummaryPage.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  features/support/mockData.json
  features/support/mockDataBuilder.js
Labels: bug (confirmed)

#512 shin/ch1155/swap-link-and-error-block-in-all-hw-connect
  app/components/wallet/hwConnect/ledger/AboutDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/AboutDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
Labels: small-scale change

#522 Fix types for Trezor
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/domain/HWSignTx.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/ada/TrezorSendStore.js
  app/types/HWConnectStoreTypes.js
Labels: NFC

#520 shin/fix-trezor-API-firefox-manifest-setup-#344
  app/config.js
  app/environment.js
  app/stores/ada/TrezorConnectStore.js
  app/utils/logging.js
  app/utils/userAgentInfo.js
  package.json
Labels: small-scale change

#505 Redo e2e test mock data
  .eslintrc
  app/api/ada/adaTypes.js
  config/test.json
  features/ada-redemption.feature
  features/addresses-generation.feature
  features/daedalus-transfer.feature
  features/main-ui.feature
  features/migration.feature
  features/mock-chain/TestWallets.js
  features/mock-chain/mockImporter.js
  features/mock-chain/mockServer.js
  features/mock-chain/mockWebSocketServer.js
  features/settings-ui.feature
  features/step_definitions/common-steps.js
  features/step_definitions/daedalus-transfer-steps.js
  features/step_definitions/settings-ui-steps.js
  features/step_definitions/transactions-steps.js
  features/step_definitions/tx-history-steps.js
  features/step_definitions/wallet-restoration-steps.js
  features/support/mockData.json
  features/support/mockDataBuilder.js
  features/support/mockDataTypes.js
  features/support/webdriver.js
  features/transactions.feature
  features/tx-history.feature
  features/wallet-creation.feature
  features/wallet-restoration.feature
  flow-typed/npm/selenium-webdriver_v3.x.x.js
Labels: NFC

#528 Material select label for modern theme
  app/themes/overrides/SelectOverrides.scss
Labels: UI/UX

#526 shin/ch1168/no-transactions-found-image-for-classic-theme
  app/assets/images/transaction/no-transactions-yet.classic.inline.svg
  app/assets/images/transaction/no-transactions-yet.modern.inline.svg
  app/components/wallet/transactions/WalletNoTransactions.js
  app/components/wallet/transactions/WalletNoTransactions.scss
  app/containers/wallet/WalletSummaryPage.js
Labels: UI/UX, small-scale change

#529 shin/fix-topbar-update
  app/stores/toplevel/TopbarStore.js
Labels: bug (confirmed)

#530 shin/fix-send-all-i18n
  app/components/wallet/send/WalletSendForm.js
  app/i18n/locales/en-US.json
Labels: small-scale change

#534 shin/fix-toolbar-on-add-wallet
  app/containers/wallet/WalletAddPage.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/toplevel/LoadingStore.js
  app/stores/toplevel/TopbarStore.js
Labels: bug (confirmed)

#533 shin/fix-dialogs
  app/components/wallet/WalletRestoreVerifyDialog.scss
  app/components/wallet/receive/AddressDetailsDialog.js
  app/components/wallet/receive/AddressDetailsDialog.scss
  app/components/wallet/send/HWSendConfirmationDialog.scss
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/settings/paper-wallets/FinalizeDialog.scss
  app/components/widgets/Dialog.js
  app/components/widgets/Dialog.scss
  app/themes/overrides/ModalOverrides.scss
  app/themes/overrides/ModalOverridesClassic.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: bug (confirmed)

#535 sync-connect-hw-with-new-design
  app/assets/images/hardware-wallet/info-icon.inline.svg
  app/components/wallet/hwConnect/common/AboutDialog.scss
  app/components/wallet/hwConnect/common/DialogCommonStyle.scss
  app/components/wallet/hwConnect/common/SaveDialog.scss
  app/components/wallet/hwConnect/ledger/AboutDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/AboutDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX
