Repository Emurgo/yoroi-frontend, pull requests merged in 2019-12, with the labels that each got.

#1178 Add nameof babel transform
  .eslintrc.js
  app/api/ada/index.js
  babel.config.js
  flow/declarations/babelPlugin.js
  package-lock.json
  package.json
Labels: NFC

#1179 Shelley wallet restoration dialog
  app/api/ada/lib/cardanoCrypto/plate.js
  app/api/ada/lib/storage/bridge/walletBuilder/shelley.js
  app/api/ada/lib/storage/models/utils.js
  app/api/ada/transactions/shelley/utxoTransactions.test.js
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/config/numbersConfig.js
  app/config/stringConfig.js
  app/containers/transfer/YoroiPlatePage.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/i18n/locales/en-US.json
  app/stores/ada/YoroiTransferStore.js
  chrome/manifest.shelley-dev.js
Labels: UI/UX

#1180 Transfer jest tests
  app/api/ada/lib/storage/bridge/tests/shelleyGroup.test.js
  app/api/ada/transactions/transfer/legacyDaedalus.js
  app/api/ada/transactions/transfer/legacyDaedalus.test.js
  app/api/ada/transactions/transfer/legacyYoroi.js
  app/api/ada/transactions/transfer/legacyYoroi.test.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/YoroiTransferStore.js
Labels: NFC

#1183 Always use byte-encoding for Shelley addresses
  app/api/ada/index.js
  app/api/ada/lib/storage/bridge/utils.js
  app/api/ada/transactions/shelley/accountingTransaction.test.js
  app/api/ada/transactions/shelley/accountingTransactions.js
  app/api/ada/transactions/shelley/daedalusTransfer.js
  app/api/ada/transactions/shelley/utxoTransactions.js
  app/api/ada/transactions/shelley/utxoTransactions.test.js
  app/api/ada/transactions/shelley/yoroiTransfer.js
  app/api/ada/transactions/transfer/legacyDaedalus.test.js
  app/api/ada/transactions/transfer/legacyYoroi.test.js
  config/shelley-dev.json
Labels: bug (confirmed)

#1185 Restoration as a store
  .flowconfig
  app/actions/ada/index.js
  app/actions/ada/wallet-restore-actions.js
  app/components/wallet/WalletRestoreDialog.js
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/dialogs/CreatePaperWalletDialogContainer.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/stores/ada/WalletRestoreStore.js
  app/stores/ada/YoroiTransferStore.js
  app/stores/ada/index.js
  babel.config.js
  package-lock.json
  package.json
Labels: NFC

#1188 Bumpt to corejs3
  babel.config.js
  package-lock.json
  package.json
Labels: bug (confirmed)

#1189 Upgrade to "reward wallet" on wallet restore
  app/actions/ada/daedalus-transfer-actions.js
  app/actions/ada/wallet-restore-actions.js
  app/actions/ada/yoroi-transfer-actions.js
  app/api/ada/transactions/transfer/legacyYoroi.js
  app/components/profile/uri-prompt/UriPromptForm.js
  app/components/transfer/BaseTransferPage.scss
  app/components/transfer/TransferInstructionsPage.scss
  app/components/transfer/TransferLayout.scss
  app/components/transfer/TransferSummaryPage.js
  app/components/transfer/TransferSummaryPage.scss
  app/components/transfer/TransferWaitingPage.scss
  app/components/transfer/YoroiTransferStartPage.scss
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryInstructions.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  app/components/wallet/hwConnect/common/ProgressStepBlock.js
  app/components/wallet/restore/LegacyExplanation.js
  app/components/wallet/restore/LegacyExplanation.scss
  app/components/wallet/settings/paper-wallets/CreatePaperDialog.js
  app/components/widgets/Dialog.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/transfer/DaedalusTransferSummaryPage.js
  app/containers/transfer/YoroiTransferPage.js
  app/containers/transfer/YoroiTransferSummaryPage.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/ada/WalletRestoreStore.js
  app/stores/ada/YoroiTransferStore.js
  app/themes/prebuilt/YoroiModern.js
  app/types/TransferTypes.js
Labels: UI/UX

#1190 Allow transfer for cip1852 and hardware wallets
  app/actions/ada/yoroi-transfer-actions.js
  app/api/ada/index.js
  app/api/ada/index.test.js
  app/components/transfer/HardwareDisclaimer.js
  app/components/transfer/HardwareDisclaimer.scss
  app/components/transfer/TransferInstructionsPage.js
  app/components/transfer/YoroiTransferStartPage.js
  app/components/transfer/navigation/TransferNavigation.js
  app/components/uri/URILandingDialog.js
  app/components/wallet/restore/LegacyExplanation.js
  app/components/widgets/BigButtonForDialogs.js
  app/components/widgets/forms/MnemonicInput.js
  app/config.js
  app/containers/transfer/HardwareDisclaimerPage.js
  app/containers/transfer/HardwareTransferFormPage.js
  app/containers/transfer/YoroiPlatePage.js
  app/containers/transfer/YoroiTransferPage.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/environment.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/ada/WalletRestoreStore.js
  app/stores/ada/YoroiTransferStore.js
  app/types/TransferTypes.js
  babel.config.js
  package-lock.json
  package.json
Labels: UI/UX, WIP / DO NOT MERGE, small-scale change

#1194 Fix wallet upgrade
  app/api/ada/lib/state-fetch/types.js
  app/api/ada/lib/storage/bridge/tests/shelleyGroup.test.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  chrome/manifest.shelley-dev.js
  config/shelley-dev.json
Labels: UI/UX, bug (confirmed)

#1196 Wasm usage for mock chain generation
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/rustLoader.js
  app/api/ada/lib/storage/bridge/tests/common.js
  app/api/ada/lib/storage/bridge/tests/mockNetwork.js
  app/api/ada/lib/storage/bridge/tests/multiwallet.test.js
  app/api/ada/lib/storage/bridge/tests/shelleyGroup.test.js
  app/api/ada/lib/storage/bridge/tests/simpleTxs.test.js
  app/api/ada/lib/storage/bridge/tests/status.test.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/components/wallet/transactions/Transaction.js
  app/domain/WalletTransaction.js
  features/mock-chain/TestWallets.js
  features/mock-chain/mockImporter.js
  features/step_definitions/transactions-steps.js
  features/step_definitions/tx-history-steps.js
Labels: NFC

#1197 Properly handle sendTx running mock backend
  app/api/ada/lib/state-fetch/remoteFetcher.js
  app/api/ada/lib/state-fetch/types.js
  app/api/ada/lib/storage/bridge/tests/mockNetwork.js
  app/api/ada/lib/storage/bridge/utils.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  config/development.json
  config/mainnet.json
  config/shelley-testnet.json
  config/test.json
  features/mock-chain/mockImporter.js
  features/mock-chain/mockServer.js
  package-lock.json
Labels: NFC

#1199 Fix mismatch on input amount type from backend
  app/api/ada/lib/state-fetch/remoteFetcher.js
Labels: bug (confirmed)

#1198 Fix send screen validation
  app/api/ada/index.js
  app/api/ada/lib/storage/bridge/hashMapper.js
  app/api/ada/lib/storage/bridge/tests/mockNetwork.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/api/ada/lib/storage/bridge/utils.js
  app/api/ada/transactions/byron/utils.js
  app/api/ada/transactions/utils.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendForm.js
  app/containers/wallet/WalletSendPage.js
  app/i18n/locales/en-US.json
  app/stores/ada/AdaWalletsStore.js
  app/stores/toplevel/LoadingStore.js
Labels: UI/UX, bug (confirmed)

#1073 shin/ch2084/implement-dashboard-no-delegate-page
  app/assets/images/dashboard/empty-dashboard.inline.svg
  app/assets/images/dashboard/exclamation-mark.inline.svg
  app/assets/images/dashboard/total-ada.inline.svg
  app/assets/images/dashboard/total-delegated.inline.svg
  app/assets/images/dashboard/total-rewards.inline.svg
  app/components/wallet/staking/dashboard/Address.js
  app/components/wallet/staking/dashboard/Address.scss
  app/components/wallet/staking/dashboard/Card.js
  app/components/wallet/staking/dashboard/Card.scss
  app/components/wallet/staking/dashboard/EmptyDashboard.js
  app/components/wallet/staking/dashboard/EmptyDashboard.scss
  app/components/wallet/staking/dashboard/EpochProgress.js
  app/components/wallet/staking/dashboard/EpochProgress.scss
  app/components/wallet/staking/dashboard/GraphWrapper.js
  app/components/wallet/staking/dashboard/GraphWrapper.scss
  app/components/wallet/staking/dashboard/ProgressCircle.js
  app/components/wallet/staking/dashboard/ProgressCircle.scss
  app/components/wallet/staking/dashboard/RewardPopup.js
  app/components/wallet/staking/dashboard/RewardPopup.scss
  app/components/wallet/staking/dashboard/StakePool.js
  app/components/wallet/staking/dashboard/StakePool.scss
  app/components/wallet/staking/dashboard/StakingDashboard.js
  app/components/wallet/staking/dashboard/StakingDashboard.scss
  app/components/wallet/staking/dashboard/Tooltip.js
  app/components/wallet/staking/dashboard/Tooltip.scss
  app/components/wallet/staking/dashboard/UserSummary.js
  app/components/wallet/staking/dashboard/UserSummary.scss
  app/containers/wallet/staking/StakingDashboardPage.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/themes/prebuilt/YoroiModern.js
  package-lock.json
  package.json
Labels: UI/UX

#1203 Show certificate inside transaction history
  app/api/ada/index.js
  app/api/ada/lib/state-fetch/remoteFetcher.js
  app/api/ada/lib/storage/bridge/tests/__snapshots__/status.test.js.snap
  app/api/ada/lib/storage/bridge/tests/shelleyGroup.test.js
  app/api/ada/lib/storage/bridge/tests/status.test.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/api/ada/lib/storage/database/primitives/api/read.js
  app/api/ada/lib/storage/database/primitives/tables.js
  app/api/ada/lib/storage/database/transactionModels/multipart/api/read.js
  app/api/ada/lib/storage/database/transactionModels/multipart/api/write.js
  app/api/ada/lib/storage/database/transactionModels/multipart/tables.js
  app/api/ada/lib/storage/models/utils.js
  app/api/ada/transactions/types.js
  app/api/ada/transactions/utils.js
  app/api/ada/transactions/utils.test.js
  app/components/wallet/transactions/Transaction.js
  app/domain/WalletTransaction.js
  app/i18n/locales/en-US.json
  app/stores/ada/AdaTransactionsStore.js
  app/stores/base/TransactionsStore.js
Labels: UI/UX

#1204 Better handle pending transactions
  app/Routes.js
  app/components/layout/VerticallyCenteredLayout.js
  app/components/layout/VerticallyCenteredLayout.scss
  app/components/wallet/staking/dashboard/EmptyDashboard.js
  app/components/wallet/staking/dashboard/EmptyDashboard.scss
  app/components/wallet/staking/dashboard/StakingDashboard.js
  app/components/wallet/transactions/Transaction.js
  app/components/widgets/InformativeError.js
  app/components/widgets/InformativeError.scss
  app/containers/wallet/staking/SeizaFetcher.js
  app/containers/wallet/staking/StakingAdvancePage.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/containers/wallet/staking/StakingPage.js
  app/containers/wallet/staking/StakingSimplePage.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#1205 Dashboard dates based on certificate
  app/api/ada/lib/storage/bridge/delegationUtils.js
  app/api/ada/lib/storage/bridge/hashMapper.js
  app/api/ada/lib/storage/bridge/timeUtils.js
  app/components/layout/VerticallyCenteredLayout.scss
  app/components/wallet/staking/dashboard/EpochProgress.js
  app/components/wallet/staking/dashboard/RewardPopup.js
  app/components/wallet/staking/dashboard/StakingDashboard.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/stores/ada/DelegationStore.js
  features/mock-chain/mockImporter.js
Labels: UI/UX

#1208 Hide Delegation Advance tab [ch2340]
  app/components/wallet/navigation/WalletNavigation.js
Labels: small-scale change

#1207 Set Yoroi's total amount to Seiza's userADA [ch2339]
  app/containers/wallet/staking/StakingPage.js
  app/utils/formatters.js
Labels: small-scale change

#1212 Decouple discriminant from network name
  app/api/ada/index.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/api/ada/restoration/shelley/scan.js
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.js
  app/components/topbar/banners/TestnetWarningBanner.js
  app/containers/transfer/YoroiPlatePage.js
  app/environment.js
  app/stores/ada/WalletRestoreStore.js
  app/stores/toplevel/ProfileStore.js
  app/stores/toplevel/WalletBackupStore.js
Labels: bug (confirmed)

#1213 Seiza URL as template
  app/Routes.js
  app/api/ada/lib/test-config.js
  app/containers/wallet/staking/StakingPage.js
  config/config-types.js
  config/development.json
  config/mainnet.json
  config/shelley-dev.json
  config/shelley-testnet.json
  config/staging.json
  config/test.json
  config/testnet.json
Labels: bug (confirmed)

#1214 Remove intro message
  app/components/profile/language-selection/IntroBanner.js
  app/components/profile/language-selection/IntroBanner.scss
  app/i18n/locales/en-US.json
Labels: UI/UX

#1206 Pool status from Github data
  app/api/ada/errors.js
  app/api/ada/lib/state-fetch/IFetcher.js
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/api/ada/lib/state-fetch/remoteFetcher.js
  app/api/ada/lib/state-fetch/types.js
  app/api/ada/lib/storage/bridge/tests/mockNetwork.js
  app/api/ada/lib/storage/models/PublicDeriver/traits.js
  app/components/settings/menu/SettingsMenu.js
  app/components/settings/menu/SettingsMenuItem.js
  app/components/wallet/staking/dashboard/StakePool.js
  app/components/wallet/staking/dashboard/StakePool.scss
  app/components/widgets/LinkButton.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/i18n/locales/en-US.json
  app/stores/ada/DelegationStore.js
  features/mock-chain/mockImporter.js
  features/mock-chain/mockServer.js
  package-lock.json
  package.json
Labels: UI/UX

#1219 Small UI fixes
  app/components/wallet/staking/DelegationTxDialog.js
  app/containers/wallet/staking/SeizaFetcher.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/containers/wallet/staking/StakingPage.js
  app/i18n/global-messages.js
Labels: bug (confirmed)

#1220 Fix next reward clock?
  app/containers/wallet/staking/StakingDashboardPage.js
Labels: UI/UX, question

#1223 Maybe fix 2 bugs
  app/stores/ada/DelegationTransactionStore.js
  app/stores/base/WalletStore.js
Labels: bug (confirmed)

#1228 Add delegation success screen
  app/actions/ada/delegation-transaction-actions.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/assets/images/transfer-success-shelley.inline.svg
  app/components/transfer/SuccessPage.js
  app/components/transfer/SuccessPage.scss
  app/components/wallet/staking/DelegationSuccessDialog.js
  app/components/wallet/staking/DelegationSuccessDialog.scss
  app/containers/transfer/YoroiPlatePage.js
  app/containers/wallet/staking/SeizaFetcher.js
  app/containers/wallet/staking/StakingPage.js
  app/i18n/locales/en-US.json
  app/stores/ada/DelegationTransactionStore.js
Labels: UI/UX

#1229 Fix DB on upgrade
  app/api/ada/lib/storage/database/index.js
  chrome/manifest.shelley-testnet.js
Labels: bug (confirmed)

#1231 Fix DB again
  app/api/ada/lib/storage/database/index.js
Labels: bug (confirmed)

#1235 Cleanup manifest
  chrome/constants.js
  chrome/manifest.development.js
  chrome/manifest.mainnet.js
  chrome/manifest.shelley-dev.js
  chrome/manifest.shelley-testnet.js
  chrome/manifest.staging.js
  chrome/manifest.template.js
  chrome/manifest.test.js
  chrome/manifest.testnet.js
  features/mock-chain/mockServer.js
  scripts/connections.js
  scripts/start.js
  scripts/startWithMockServer.js
  webpack/devConfig.js
Labels: NFC

#1236 First wave of design feedback
  app/components/topbar/WalletTopbarTitle.js
  app/components/wallet/staking/dashboard/Address.scss
  app/components/widgets/LoadingSpinner.js
  app/components/widgets/LoadingSpinner.scss
  app/containers/wallet/staking/SeizaFetcher.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/containers/wallet/staking/StakingPage.js
  app/domain/PublicDeriverWithCachedMeta.js
Labels: UI/UX

#1238 More manifest improvements + Seiza processing screen
  app/containers/wallet/staking/SeizaFetcher.js
  chrome/constants.js
  chrome/manifest.development.js
  chrome/manifest.mainnet.js
  chrome/manifest.shelley-dev.js
  chrome/manifest.shelley-testnet.js
  chrome/manifest.staging.js
  chrome/manifest.test.js
  chrome/manifest.testnet.js
Labels: bug (confirmed)

#1239 Cancel fee calculation on input
  app/config.js
  app/stores/ada/AdaTransactionBuilderStore.js
  app/stores/lib/CachedRequest.js
  app/stores/lib/Request.js
Labels: bug (confirmed)

#1240 Detect server error in account state
  app/components/wallet/staking/dashboard/StakingDashboard.js
  app/components/wallet/staking/dashboard/StakingDashboard.scss
  app/containers/wallet/staking/StakingDashboardPage.js
  app/stores/ada/DelegationStore.js
  chrome/constants.js
Labels: UI/UX
