Repository Emurgo/yoroi-frontend, pull requests merged in 2019-11, with the labels that each got.

#1018 Port "load more transactions" fix to Shelley branch
  app/containers/wallet/WalletSummaryPage.js
  app/stores/base/TransactionsStore.js
Labels: bug (confirmed)

#1023 shin/ch2063/fix-fast-times-on-create-wallet-recover-phrase
  app/stores/toplevel/WalletBackupStore.js
Labels: fix for next version, regression

#1053 Sync develop branch changes to shelley branch
  app/i18n/locales/zh-Hant.json
  app/stores/toplevel/WalletBackupStore.js
Labels: bug (confirmed)

#1051 shin/ch2069/fix-select-input-icon-position
  app/themes/overrides/SelectOverrides.scss
Labels: fix for next version, regression

#1054 shin/ch2071/fix-check-dialog-style-in-both-modern-and
  app/components/wallet/hwConnect/ledger/CheckDialog.js
  app/components/wallet/hwConnect/ledger/CheckDialog.scss
Labels: bug (confirmed), fix for next version

#1050 shin/ch2049/fix-amount-input-fee-margin-and-amount-position
  app/components/wallet/skins/AmountInputSkin.scss
  app/themes/skins/FormFieldOwnSkin.scss
Labels: fix for next version, regression

#1049 shin/ch2068/fix-bottom-margin-on-non-password-dialog
  app/components/wallet/WalletCreateDialog.scss
  app/components/wallet/WalletRestoreDialog.scss
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/settings/ChangeWalletPasswordDialog.scss
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.scss
  app/themes/prebuilt/YoroiModern.js
Labels: bug (confirmed), fix for next version

#1024 shin/ch2064/fix-recovery-phrase-input-off-focus-problem
  app/containers/wallet/WalletSummaryPage.js
  app/themes/skins/AutocompleteOwnSkin.js
Labels: fix for next version, regression

#1025 shin/ch2067/delete-obsolete-notification-message
  app/components/wallet/WalletAdd.js
  app/containers/wallet/WalletAddPage.js
  app/i18n/locales/en-US.json
Labels: bug (confirmed), fix for next version

#1052 shin/ch2070/fix-verify-restored-wallet-copy-tool-tip
  app/components/wallet/WalletRestoreVerifyDialog.scss
Labels: bug (confirmed), fix for next version

#1058 Fix Node CI on Shelley
  .circleci/config.yml
  package-lock.json
  package.json
Labels: bug (confirmed)

#1055 shin/ch2073/in-case-of-no-internet-connection-fix-error
  app/api/ada/index.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/TrezorConnectStore.js
Labels: bug (confirmed), fix for next version

#1059 fix back button on URI verify
  app/components/uri/URIVerifyDialog.js
  app/containers/uri/URILandingDialogContainer.js
Labels: bug (confirmed)

#1064 shin/ch2076/fix-inputs-on-send-page
  app/components/wallet/WalletAdd.js
  app/components/wallet/send/WalletSendForm.js
Labels: bug (confirmed), fix for next version

#880 shin/ch1880/classictheme-fix-fonts-on-transfer-funds
  app/components/transfer/YoroiTransferStartPage.scss
Labels: UI/UX, bug (confirmed)

#1071 shin/ch2081/update-routing-to-load-staking-pages-2
  app/Routes.js
  app/components/wallet/navigation/WalletNavigation.js
  app/containers/wallet/staking/SeizaFetcher.js
  app/containers/wallet/staking/StakingAdvancedSimulatorPage.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/containers/wallet/staking/StakingSimulatorPage.js
  app/i18n/locales/en-US.json
  app/routes-config.js
Labels: UI/UX

#1074 Make all ESLint files JS and not JSON
  .eslintrc
  .eslintrc.js
  features/.eslintrc.js
  scripts/.eslintrc
  scripts/.eslintrc.js
  webpack/.eslintrc
  webpack/.eslintrc.js
Labels: NFC

#1075 Misc version bumps
  .circleci/config.yml
  package-lock.json
  package.json
Labels: NFC

#990 Shin/ch1996/add tooltip info on add wallet page
  app/assets/images/info-icon.inline.svg
  app/components/wallet/WalletAdd.js
  app/components/wallet/WalletAdd.scss
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/widgets/CustomTooltip.js
  app/components/widgets/CustomTooltip.scss
  app/i18n/locales/en-US.json
Labels: UI/UX

#1080 Transfer yoroi paper
  app/actions/ada/paper-wallets-actions.js
  app/actions/ada/yoroi-transfer-actions.js
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/cardanoCrypto/paperWallet.js
  app/api/ada/lib/cardanoCrypto/paperWallet.test.js
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/components/transfer/BaseTransferPage.js
  app/components/transfer/BaseTransferPage.scss
  app/components/transfer/TransferMasterKeyPage.js
  app/components/transfer/TransferMasterKeyPage.scss
  app/components/transfer/TransferMnemonicPage.js
  app/components/transfer/TransferWaitingPage.js
  app/components/transfer/YoroiTransferStartPage.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/widgets/DialogBackButton.js
  app/components/widgets/forms/DaedalusMasterKeyInput.js
  app/components/widgets/forms/DaedalusMasterKeyInput.scss
  app/components/widgets/forms/MnemonicInput.js
  app/components/widgets/forms/MnemonicInput.scss
  app/components/widgets/forms/PaperPasswordInput.js
  app/components/widgets/forms/PaperPasswordInput.scss
  app/config.js
  app/containers/MainLayout.js
  app/containers/transfer/DaedalusTransferFormPage.js
  app/containers/transfer/DaedalusTransferMasterKeyFormPage.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/transfer/DaedalusTransferWaitingPage.js
  app/containers/transfer/YoroiPaperWalletFormPage.js
  app/containers/transfer/YoroiTransferFormPage.js
  app/containers/transfer/YoroiTransferPage.js
  app/containers/transfer/YoroiTransferWaitingPage.js
  app/containers/uri/URILandingDialogContainer.js
  app/containers/wallet/dialogs/CreatePaperWalletDialogContainer.js
  app/containers/wallet/dialogs/WalletLedgerConnectDialogContainer.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  app/containers/wallet/dialogs/WalletTrezorConnectDialogContainer.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/YoroiTransferStore.js
  app/types/TransferTypes.js
  app/types/injectedPropsType.js
  features/daedalus-transfer.feature
  features/mock-chain/mockImporter.js
  features/step_definitions/yoroi-transfer-steps.js
  features/yoroi-transfer.feature
Labels: small-scale change

#1078 Add new theme: YoroiShelleyTestnet
  app/components/topbar/banners/TestnetWarningBanner.js
  app/components/topbar/banners/TestnetWarningBanner.scss
  app/containers/settings/categories/GeneralSettingsPage.js
  app/i18n/locales/en-US.json
  app/stores/toplevel/ProfileStore.js
  app/themes/index.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#1082 Add flow to all files
  .eslintrc.js
  app/api/localStorage/primitives.js
  app/utils/tabManager.js
  chrome/content-scripts/3rd-party-trezor/trezor-usb-permissions.js
  chrome/extension/background.js
  chrome/manifest.development.js
  chrome/manifest.mainnet.js
  chrome/manifest.shelley-dev.js
  chrome/manifest.staging.js
  chrome/manifest.template.js
  chrome/manifest.test.js
  chrome/manifest.testnet.js
  features/step_definitions/migration-steps.js
  webpack/commonConfig.js
  webpack/customPublicPath.js
  webpack/devConfig.js
  webpack/prodConfig.js
Labels: NFC

#1084 Stricter type requirements on API folder
  .eslintrc.js
  app/api/.eslintrc.js
  app/api/ada/lib/cardanoCrypto/rustLoader.js
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/api/ada/lib/storage/bridge/hashMapper.js
  app/api/ada/lib/storage/bridge/tests/common.js
  app/api/ada/lib/storage/bridge/tests/simpleTxs.test.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/api/ada/lib/storage/database/__mocks__/initialSeed.js
  app/api/ada/lib/storage/database/initialSeed.js
  app/api/ada/lib/storage/database/transactionModels/utxo/api/read.js
  app/api/ada/paperWallet/paperWalletPdf.js
  app/api/ada/restoration/byron/scan.js
  app/api/ada/restoration/shelley/scan.js
  app/api/ada/transactions/utils.test.js
  app/api/export/index.test.js
  app/api/localStorage/index.js
  app/utils/routing.js
Labels: NFC

#1085 Fix member variable type in stores
  app/actions/profile-actions.js
  app/containers/profile/LanguageSelectionPage.js
  app/containers/settings/categories/GeneralSettingsPage.js
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/WalletReceivePage.js
  app/stores/.eslintrc.js
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/HWVerifyAddressStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/base/AddressesStore.js
  app/stores/base/TransactionsStore.js
  app/stores/base/WalletSettingsStore.js
  app/stores/base/WalletStore.js
  app/stores/toplevel/LoadingStore.js
  app/stores/toplevel/ProfileStore.js
  app/stores/toplevel/TopbarStore.js
  app/stores/toplevel/UiDialogsStore.js
  app/stores/toplevel/UiNotificationsStore.js
Labels: NFC

#1087 Modify text on transfer sumamry page
  app/components/transfer/TransferSummaryPage.js
  app/components/wallet/settings/paper-wallets/CreatePaperDialog.js
  app/i18n/global-messages.js
Labels: UI/UX

#1088 First snapshot Add Wallet page fixes
  app/components/wallet/WalletAdd.js
  app/containers/wallet/WalletAddPage.js
Labels: UI/UX

#1089 shin/ch2116/transfer-from-wallet-page-remove-create-yoroi
  app/components/transfer/TransferInstructionsPage.js
  app/components/transfer/YoroiTransferStartPage.js
Labels: UI/UX

#1090 First snapshot, hide wallet and paper wallet from settings
  app/components/settings/menu/SettingsMenu.js
Labels: UI/UX

#1092 All outline button color change to Shelley theme
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#1093 Add topbar title on transfer page [ch2129]
  app/containers/transfer/Transfer.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#1094 Merge color changes to shelley-snapshot-check
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#1091 shin/ch2127/enable-transfer-even-if-there-is-no-wallet
  app/actions/ada/daedalus-transfer-actions.js
  app/actions/ada/yoroi-transfer-actions.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/transfer/YoroiTransferPage.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/YoroiTransferStore.js
Labels: UI/UX

#1095 Update add wallet page bg image and Yoroi icon
  app/assets/images/add-wallet/add-wallet-bg-testnet.inline.svg
  app/assets/images/yoroi-logo-shelley-testnet-white.inline.svg
  app/components/wallet/WalletAdd.js
  app/components/wallet/WalletAdd.scss
Labels: UI/UX

#1096 Update topbar testnet warning icon
  app/assets/images/shelley-testnet-warning.inline.svg
  app/components/topbar/banners/TestnetWarningBanner.js
  app/components/topbar/banners/TestnetWarningBanner.scss
Labels: UI/UX

#1098 Add white underline to categories in Shelley
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#1103 Add shelley language page
  app/assets/images/select-language-shelley.svg
  app/assets/images/yoroi-logotestnet-gradient.inline.svg
  app/components/layout/TopBarLayout.js
  app/components/layout/TopBarLayout.scss
  app/components/profile/language-selection/IntroBanner.js
  app/components/profile/language-selection/IntroBanner.scss
  app/components/profile/language-selection/LanguageSelectionForm.scss
  app/components/uri/URIInvalidDialog.js
  app/components/uri/URILandingDialog.js
  app/containers/MainLayout.js
  app/containers/profile/LanguageSelectionPage.js
  app/containers/profile/TermsOfUsePage.js
  app/containers/profile/UriPromptPage.js
  app/containers/settings/Settings.js
  app/containers/transfer/Transfer.js
  app/containers/wallet/NoWalletsPage.js
  app/containers/wallet/Wallet.js
  app/containers/wallet/WalletAddPage.js
  app/containers/wallet/staking/SeizaFetcher.js
  app/i18n/locales/en-US.json
  app/themes/index.js
  app/themes/prebuilt/Common.js
Labels: UI/UX

#1105 Fix typo from "This is an indepdendent extension" to "This is an independent extension"
  app/components/profile/language-selection/IntroBanner.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#1107 Update language selection page texts
  app/components/profile/language-selection/IntroBanner.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#1109 shin/add-i18n-key-to-help-manual-translation
  app/i18n/locales/ja-JP.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: NFC

#1112 Update Add Wallet page bg image
  app/assets/images/add-wallet/add-wallet-bg-testnet.inline.svg
Labels: UI/UX

#1111 shin/ch2175/update-jp-hans-hant-i18n-text
  app/i18n/locales/ja-JP.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: UI/UX

#1116 Ignore shelley l10n for E2E tests
  .circleci/config.yml
Labels: NFC

#1079 New Crowdin translations
  app/i18n/locales/de-DE.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/it-IT.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/paper-wallets/intro/de-DE.md
  app/i18n/locales/paper-wallets/intro/es-ES.md
  app/i18n/locales/paper-wallets/intro/fr-FR.md
  app/i18n/locales/paper-wallets/intro/id-ID.md
  app/i18n/locales/paper-wallets/intro/it-IT.md
  app/i18n/locales/paper-wallets/intro/ja-JP.md
  app/i18n/locales/paper-wallets/intro/ko-KR.md
  app/i18n/locales/paper-wallets/intro/pt-BR.md
  app/i18n/locales/paper-wallets/intro/ru-RU.md
  app/i18n/locales/paper-wallets/intro/zh-Hans.md
  app/i18n/locales/paper-wallets/intro/zh-Hant.md
  app/i18n/locales/pt-BR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/terms-of-use/ada/de-DE.md
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: fix for next version

#1115 Update Yoroi Shelley Testnet page title from 'Yoroi' to 'Yoroi Shelley Testnet'
  chrome/views/main_window.html
  webpack/commonConfig.js
  webpack/devConfig.js
  webpack/prodConfig.js
Labels: UI/UX, fix for next version

#1113 Replace deprecated react-svg-inline library
  app/components/loading/Loading.js
  app/components/profile/language-selection/IntroBanner.js
  app/components/profile/uri-prompt/UriAccept.js
  app/components/profile/uri-prompt/UriPromptForm.js
  app/components/profile/uri-prompt/UriSkip.js
  app/components/topbar/TopBarCategory.js
  app/components/topbar/WalletTopbarTitle.js
  app/components/topbar/banners/ServerErrorBanner.js
  app/components/topbar/banners/TestnetWarningBanner.js
  app/components/transfer/SuccessPage.js
  app/components/uri/URIInvalidDialog.js
  app/components/uri/URILandingDialog.js
  app/components/wallet/WalletAdd.js
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletReceive.scss
  app/components/wallet/add/option-dialog/OptionBlock.js
  app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  app/components/wallet/hwConnect/ledger/CheckDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/HelpLinkBlock.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/CheckDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/HelpLinkBlock.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/wallet/summary/WalletSummary.js
  app/components/wallet/transactions/Transaction.js
  app/components/wallet/transactions/TransactionTypeIcon.js
  app/components/wallet/transactions/WalletNoTransactions.js
  app/components/widgets/CopyableAddress.js
  app/components/widgets/CustomTooltip.js
  app/components/widgets/DialogBackButton.js
  app/components/widgets/DialogCloseButton.js
  app/components/widgets/FlagLabel.js
  app/components/widgets/LinkButton.js
  app/components/widgets/NotificationMessage.js
  app/components/widgets/ProgressSteps.js
  app/components/widgets/forms/ReadOnlyInput.js
  app/i18n/translations.js
  app/themes/skins/FormFieldOwnSkin.js
  package-lock.json
  package.json
  webpack/commonConfig.js
Labels: UI/UX

#1119 replace Yoroi banner for testnet
  app/assets/images/yoroi-logotestnet-gradient.inline.svg
Labels: UI/UX

#1120 Update text from "Transfer all funds from" to "Check funds from"
  app/i18n/global-messages.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/it-IT.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/pt-PT.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: UI/UX, fix for next version

#1124 Fix switching back to English after language change
  app/App.js
  features/mock-chain/TestWallets.js
  stories/helpers/StoryWrapper.js
Labels: bug (confirmed)

#1126 Apply eslint-plugin-flowtype fixes
  .eslintrc.js
  app/api/.eslintrc.js
  app/api/ada/lib/storage/models/PublicDeriver/interfaces.js
  app/stores/.eslintrc.js
  app/stores/ada/AdaAddressesStore.js
  app/stores/ada/AdaTransactionBuilderStore.js
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/AdaWalletSettingsStore.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/HWVerifyAddressStore.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/PaperWalletCreateStore.js
  app/stores/ada/ServerConnectionStore.js
  app/stores/ada/StateFetchStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/ada/TrezorSendStore.js
  app/stores/base/Store.js
  app/stores/base/TransactionsStore.js
  app/stores/base/WalletStore.js
  app/stores/lib/Reaction.js
  app/stores/toplevel/AppStore.js
  app/stores/toplevel/LoadingStore.js
  app/stores/toplevel/ProfileStore.js
  app/stores/toplevel/TopbarStore.js
  app/stores/toplevel/UiDialogsStore.js
  app/stores/toplevel/UiNotificationsStore.js
  app/stores/toplevel/WalletBackupStore.js
  package-lock.json
  package.json
Labels: NFC

#1127 Bump to Flow 112
  package-lock.json
  package.json
Labels: NFC

#1130 Fix Shelley explorer link
  app/domain/Explorer.js
Labels: bug (confirmed)

#1131 Fix manifest generation
  chrome/manifest.development.js
  chrome/manifest.mainnet.js
  chrome/manifest.shelley-dev.js
  chrome/manifest.shelley-testnet.js
  chrome/manifest.staging.js
  chrome/manifest.template.js
  chrome/manifest.test.js
  chrome/manifest.testnet.js
Labels: bug (confirmed)

#1137 Change pasword length requirement from 12 -> 10
  app/components/wallet/WalletRestoreDialog.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/utils/validations.js
Labels: question

#1004 shin/ch1994/update-slogan-text
  app/components/wallet/WalletAdd.js
  app/i18n/locales/en-US.json
Labels: UI/UX, WIP / DO NOT MERGE

#1143 Fix tx history page
  app/api/ada/lib/cardanoCrypto/plate.js
  app/api/ada/lib/storage/bridge/hashMapper.js
  app/api/ada/lib/storage/bridge/walletBuilder/shelley.js
  app/api/ada/lib/storage/models/utils.js
  app/api/ada/restoration/shelley/scan.js
Labels: bug (confirmed)

#1145 Port tx history tests to cip1852 single address
  app/api/ada/index.js
  app/api/ada/index.test.js
  app/api/ada/lib/cardanoCrypto/plate.js
  app/api/ada/lib/storage/bridge/tests/__snapshots__/multiwallet.test.js.snap
  app/api/ada/lib/storage/bridge/tests/__snapshots__/simpleTxs.test.js.snap
  app/api/ada/lib/storage/bridge/tests/__snapshots__/status.test.js.snap
  app/api/ada/lib/storage/bridge/tests/common.js
  app/api/ada/lib/storage/bridge/tests/multiwallet.test.js
  app/api/ada/lib/storage/bridge/tests/simpleTxs.test.js
  app/api/ada/lib/storage/bridge/tests/status.test.js
  app/api/ada/lib/storage/bridge/walletBuilder/byron.js
  app/api/ada/lib/storage/bridge/walletBuilder/shelley.js
  app/api/ada/lib/storage/models/PublicDeriver/interfaces.js
  app/api/ada/lib/storage/models/PublicDeriver/traits.js
  app/api/ada/lib/storage/models/utils.js
  app/api/ada/lib/storage/tests/index.test.js
  app/api/ada/restoration/byron/scan.js
  app/api/ada/restoration/shelley/scan.js
  app/api/ada/transactions/byron/transactionV2.test.js
  app/api/ada/transactions/shelley/utxoTransactions.test.js
  app/config/numbersConfig.js
  app/stores/ada/YoroiTransferStore.js
  app/stores/base/AddressesStore.js
Labels: NFC
