Repository Emurgo/yoroi-frontend, pull requests merged in 2019-04, with the labels that each got.

#391 Add restart command
  features/README.md
Labels: NFC

#386 Bundle change for Firefox
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/decrypt.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/wallet/AdaRedemptionPage.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/i18n/errors.js
  app/i18n/locales/en-US.json
  chrome/views/background.html
  chrome/views/background.pug
  chrome/views/main_window.html
  chrome/views/main_window.pug
  package-lock.json
  package.json
  scripts/tasks.js
  webpack/development.config.js
  webpack/dll.config.js
  webpack/mainnet.config.js
  webpack/staging.config.js
  webpack/test.config.js
  webpack/testnet.config.js
Labels: NFC

#397 Fix on-boot warnings
  chrome/extension/index.js
  package-lock.json
  package.json
Labels: NFC

#396 cleanup webpacks
  scripts/build.js
  scripts/start.js
  webpack/commonConfig.js
  webpack/devConfig.js
  webpack/development.config.js
  webpack/mainnet.config.js
  webpack/prodConfig.js
  webpack/staging.config.js
  webpack/test.config.js
  webpack/testnet.config.js
Labels: NFC

#373 New Crowdin translations
  app/i18n/locales/Indonesian.json
  app/i18n/locales/de-DE.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: fix for next version

#356 Fix multiple tabs of Yoroi open & remove "tabs" permission
  app/stores/toplevel/LoadingStore.js
  app/utils/tabManager.js
  chrome/extension/background.js
  chrome/extension/index.js
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  chrome/manifest.test.json
  chrome/manifest.testnet.json
  webpack/commonConfig.js
Labels: bug (confirmed), small-scale change

#400 New Crowdin translations
  app/i18n/locales/de-DE.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: fix for next version

#399 Version bump
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  chrome/manifest.test.json
  chrome/manifest.testnet.json
  package-lock.json
  package.json
Labels: NFC

#405 Fix bridge use
  app/stores/ada/LedgerConnectStore.js
Labels: bug (confirmed)

#412 Fix tests broken by wasm migration
  .babelrc
  app/api/ada/adaWallet.test.js
  app/api/ada/daedalusTransfer.js
  app/api/ada/daedalusTransfer.test.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: NFC

#414 Bump NPM version
  .circleci/config.yml
  .nvmrc
  package.json
Labels: NFC

#403 Fix some of the single-account assumptions in Yoroi
  app/api/ada/adaAccount.js
  app/api/ada/adaLocalStorage.js
  app/api/ada/adaTransactions/adaNewTransactions.js
  app/api/ada/adaTransactions/adaTransactionsHistory.js
  app/api/ada/adaTypes.js
  app/api/ada/adaWallet.js
  app/api/ada/hardwareWallet/createWallet.js
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoToModel.js
  app/api/ada/lib/utils.js
  app/api/ada/restoreAdaWallet.js
  app/api/common.js
  app/config.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/base/AddressesStore.js
  docs/specs/code/TREZOR_INTEGRATION.md
  docs/specs/code/ledger-integration/README.md
  features/support/mockData.json
Labels: NFC

#417 Remove node version from README
  docs/SETUP.md
Labels: NFC

#407 New Crowdin translations
  app/i18n/locales/Spanish.json
  app/i18n/locales/de-DE.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: fix for next version

#419 Package Fix
  package-lock.json
Labels: NFC

#420 Fix Trezor account creation
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/api/ada/lib/utils.js
  app/stores/ada/TrezorConnectStore.js
Labels: bug (confirmed), fix for next version
