Repository Emurgo/yoroi-frontend, pull requests merged in 2019-08, with the labels that each got.

#817 Tooltip notifications - copy button feedback
  app/assets/images/copied.inline.svg
  app/assets/images/copy.inline.svg
  app/components/uri/URIDisplayDialog.js
  app/components/uri/URIDisplayDialog.scss
  app/components/wallet/WalletReceive.js
  app/components/wallet/WalletReceive.scss
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/components/wallet/settings/paper-wallets/FinalizeDialog.js
  app/components/widgets/CopyableActionLink.js
  app/components/widgets/CopyableActionLink.scss
  app/components/widgets/CopyableAddress.js
  app/components/widgets/CopyableAddress.scss
  app/config.js
  app/containers/wallet/WalletReceivePage.js
  app/containers/wallet/dialogs/CreatePaperWalletDialogContainer.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/toplevel/UiNotificationsStore.js
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  features/main-ui.feature
  features/step_definitions/main-ui-steps.js
  features/step_definitions/uri-steps.js
  features/uri-scheme.feature
Labels: UI/UX

#865 PEM instructions
  docs/SETUP.md
Labels: NFC

#517 Material design animation for input fields
  app/components/settings/SettingsLayout.scss
  app/components/transfer/TransferLayout.scss
  app/components/transfer/TransferMasterKeyPage.js
  app/components/transfer/TransferMasterKeyPage.scss
  app/components/transfer/TransferMnemonicPage.js
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendForm.scss
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.js
  app/themes/overrides/AutocompleteOverrides.scss
  app/themes/overrides/AutocompleteOverridesClassic.scss
  app/themes/skins/AutocompleteOwnSkin.js
  app/themes/skins/FormFieldOwnSkin.js
  app/themes/skins/FormFieldOwnSkin.scss
  app/themes/skins/InputOwnSkin.js
Labels: UI/UX, fix for next version

#848 Dialog margins in Modern theme
  app/components/mixins/HeaderBlock.scss
  app/components/uri/URIGenerateDialog.scss
  app/components/wallet/WalletCreateDialog.scss
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/WalletRestoreDialog.scss
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/components/wallet/WalletRestoreVerifyDialog.scss
  app/components/wallet/add/option-dialog/OptionListWrapperStyle.scss
  app/components/wallet/export/ExportTransactionDialog.js
  app/components/wallet/export/ExportTransactionDialog.scss
  app/components/wallet/hwConnect/common/CheckDialog.scss
  app/components/wallet/hwConnect/common/ConnectDialog.scss
  app/components/wallet/hwConnect/common/DialogCommonStyle.scss
  app/components/wallet/hwConnect/common/SaveDialog.scss
  app/components/wallet/hwConnect/ledger/CheckDialog.js
  app/components/wallet/hwConnect/ledger/ConnectDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/CheckDialog.js
  app/components/wallet/hwConnect/trezor/ConnectDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/settings/ChangeWalletPasswordDialog.scss
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.scss
  app/components/widgets/Dialog.js
  app/components/widgets/Dialog.scss
  app/components/widgets/DialogTextBlock.js
  app/components/widgets/DialogTextBlock.scss
  app/components/widgets/InformativeMessage.scss
  app/themes/overrides/FormFieldOverrides.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#877 Switching to tooltip notifications on generated addresses
  app/components/wallet/WalletReceive.js
  app/components/widgets/CopyableActionLink.js
  app/components/widgets/CopyableActionLink.scss
  app/config.js
  app/containers/wallet/WalletReceivePage.js
Labels: UI/UX

#701 Implement storage spec
  .eslintrc
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/storage/adaAccount.js
  app/api/ada/lib/storage/bridge/IStorageBridge.js
  app/api/ada/lib/storage/bridge/appendChain.js
  app/api/ada/lib/storage/bridge/lovefieldBridge.js
  app/api/ada/lib/storage/bridge/lovefieldDerive.js
  app/api/ada/lib/storage/bridge/utils.js
  app/api/ada/lib/storage/bridge/walletBuilder.js
  app/api/ada/lib/storage/database/README.md
  app/api/ada/lib/storage/database/genericBip44/api/add.js
  app/api/ada/lib/storage/database/genericBip44/api/get.js
  app/api/ada/lib/storage/database/genericBip44/api/utils.js
  app/api/ada/lib/storage/database/genericBip44/tables.js
  app/api/ada/lib/storage/database/index.js
  app/api/ada/lib/storage/database/transactions/api.js
  app/api/ada/lib/storage/database/transactions/tables.js
  app/api/ada/lib/storage/database/uncategorized/api/add.js
  app/api/ada/lib/storage/database/uncategorized/api/get.js
  app/api/ada/lib/storage/database/uncategorized/tables.js
  app/api/ada/lib/storage/database/utils.js
  app/api/ada/lib/storage/lovefieldDatabase.js
  app/api/ada/lib/storage/models/Bip44Wallet.js
  app/api/ada/lib/storage/models/ConceptualWallet.js
  app/api/ada/lib/storage/models/PublicDeriver.js
  app/api/ada/lib/storage/models/functionalities/IDerive.js
  app/api/ada/lib/storage/tests/index.test.js
  app/api/ada/lib/storage/tests/snapshot.js
  docs/specs/code/STORAGE.md
  flow-typed/npm/lovefield_v2.x.x.js
  flow/declarations/utils.js
  package.json
Labels: spec-implementation

#887 shin/ch1899/fix-flow-error
  app/stores/ada/YoroiTransferStore.js
Labels: NFC, bug (confirmed)

#889 Add spec for general data encryption
  docs/specs/meta/TEMPLATE.md
Labels: spec

#891 Add spec for general data encryption
  docs/specs/code/ENCRYPT
Labels: spec

#885 Fixing input labels on Modern Theme
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, fix for next version

#895 Remove Mapping table in storage v2
  app/api/ada/lib/storage/bridge/lovefieldDerive.js
  app/api/ada/lib/storage/bridge/walletBuilder.js
  app/api/ada/lib/storage/database/genericBip44/api/add.js
  app/api/ada/lib/storage/database/genericBip44/api/get.js
  app/api/ada/lib/storage/database/genericBip44/tables.js
  app/api/ada/lib/storage/tests/index.test.js
  app/api/ada/lib/storage/tests/snapshot.js
Labels: NFC

#896 Rename Bip44Derivation
  app/api/ada/lib/storage/bridge/walletBuilder.js
  app/api/ada/lib/storage/database/genericBip44/api/add.js
  app/api/ada/lib/storage/database/genericBip44/api/get.js
  app/api/ada/lib/storage/database/genericBip44/tables.js
  app/api/ada/lib/storage/database/transactions/tables.js
  app/api/ada/lib/storage/tests/index.test.js
  app/api/ada/lib/storage/tests/snapshot.js
Labels: NFC

#901 Remove specs
  docs/architecture/README.txt
  docs/architecture/images/component-diagram.png
  docs/architecture/images/sequence-diagrams.png
  docs/architecture/modelio-project.zip
  docs/specs/code/ENCRYPT.md
  docs/specs/code/NUMBER_PLATES.md
  docs/specs/code/URI_SCHEME.md
  docs/specs/meta/MEETING.md
Labels: NFC
