Repository Emurgo/yoroi-frontend, pull requests merged in 2019-09, with the labels that each got.

#940 Fix Transfer from Another Wallet
  app/api/ada/index.js
  app/api/ada/lib/storage/adaAddress.js
  app/api/ada/lib/storage/types.js
  app/api/ada/restoreAdaWallet.js
Labels: bug (confirmed)

#938 Add missing disabled checks
  app/components/wallet/WalletRestoreVerifyDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  package-lock.json
Labels: UI/UX, bug (confirmed)

#939 Restore spinner when restoring wallet
  app/containers/wallet/WalletSummaryPage.js
Labels: UI/UX, bug (confirmed)

#943 Flow 107
  app/api/ada/index.js
  app/api/ada/lib/pdfParser.js
  app/domain/Explorer.js
  app/i18n/LocalizableError.js
  app/stores/ada/AdaTransactionBuilderStore.js
  flow-typed/npm/react-intl_v2.x.x.js
  flow/declarations/utils.js
  package-lock.json
  package.json
Labels: NFC

#944 Update jest flow
  flow-typed/npm/jest_v24.x.x.js
Labels: NFC

#640 Migrate to CRX3
  app/api/ada/lib/storage/lovefieldDatabase.js
  e2etest-key.pem
  features/support/webdriver.js
  package-lock.json
  package.json
  scripts/compress.js
Labels: WIP / DO NOT MERGE

#947 Upgrade to ESLint v6
  .eslintrc
  app/App.js
  app/api/ada/lib/storage/helpers.js
  app/api/ada/lib/storage/lovefieldDatabase.js
  app/components/wallet/settings/paper-wallets/CreatePaperDialog.js
  app/environment.js
  app/stores/base/WalletStore.js
  package-lock.json
  package.json
Labels: NFC

#946 Remove dead code
  .flowconfig
  app/Routes.js
  app/actions/ada/ada-redemption-actions.js
  app/actions/ada/index.js
  app/api/ada/adaRedemption.js
  app/api/ada/errors.js
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoErrors.js
  app/api/ada/lib/cardanoCrypto/cryptoRedemption.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/decrypt.js
  app/api/ada/lib/pdfParser.js
  app/api/ada/lib/storage/adaAddress.js
  app/components/settings/menu/SettingsMenu.js
  app/components/wallet/ada-redemption/AdaRedemptionChoices.js
  app/components/wallet/ada-redemption/AdaRedemptionChoices.scss
  app/components/wallet/ada-redemption/AdaRedemptionDisclaimer.js
  app/components/wallet/ada-redemption/AdaRedemptionDisclaimer.scss
  app/components/wallet/ada-redemption/AdaRedemptionForm.js
  app/components/wallet/ada-redemption/AdaRedemptionForm.scss
  app/components/wallet/ada-redemption/AdaRedemptionNoWallets.js
  app/components/wallet/ada-redemption/AdaRedemptionNoWallets.scss
  app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.js
  app/components/wallet/ada-redemption/AdaRedemptionSuccessOverlay.scss
  app/components/widgets/forms/AdaCertificateUploadWidget.js
  app/components/widgets/forms/AdaCertificateUploadWidget.scss
  app/components/widgets/forms/ImageUploadWidget.js
  app/components/widgets/forms/ImageUploadWidget.scss
  app/config.js
  app/containers/wallet/AdaRedemptionPage.js
  app/containers/wallet/Wallet.js
  app/i18n/errors.js
  app/i18n/locales/en-US.json
  app/i18n/translations.js
  app/routes-config.js
  app/stores/ada/AdaRedemptionStore.js
  app/stores/ada/index.js
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  app/types/redemptionTypes.js
  app/utils/redemption-key-validation.js
  features/ada-redemption.feature
  features/mock-chain/mockImporter.js
  features/step_definitions/ada-redemption-steps.js
  features/support/webdriver.js
  jest.config.js
  package-lock.json
  package.json
  tests/unit/mockData/force-vended-decrypted.txt
  tests/unit/mockData/force-vended.pdf.enc
  tests/unit/mockData/mockData.json
  tests/unit/mockData/mockDataBuilder.js
  tests/unit/mockData/regular-decrypted.txt
  tests/unit/mockData/regular.pdf
  tests/unit/mockData/regular.pdf.enc
  tests/unit/mockData/regular.txt
Labels: NFC

#948 Focus broken on Paper Wallet mnemonic verification step
  app/components/wallet/WalletRestoreDialog.js
Labels: bug (confirmed)

#949 Fix all sketchy lints
  .eslintrc
  .flowconfig
  app/api/ada/adaWallet.js
  app/api/ada/adaWallet.test.js
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/cardanoCrypto/rustLoader.js
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/api/ada/lib/storage/bridge/utils.js
  app/api/ada/paperWallet/paperWalletPdf.js
  app/api/export/index.js
  app/api/localStorage/primitives.js
  app/components/layout/TopBarLayout.js
  app/components/profile/terms-of-use/TermsOfUseText.js
  app/components/settings/menu/SettingsMenuItem.js
  app/components/topbar/TopBarCategory.js
  app/components/topbar/WalletAccountIcon.js
  app/components/uri/URIGenerateDialog.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/add/option-dialog/OptionBlock.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseMnemonic.js
  app/components/wallet/export/ExportTransactionDialog.js
  app/components/wallet/skins/AmountInputSkin.js
  app/components/widgets/Dialog.js
  app/components/widgets/DialogCloseButton.js
  app/components/widgets/DialogTextBlock.js
  app/containers/settings/Settings.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/i18n/LocalizableError.js
  app/stores/ada/AdaTransactionBuilderStore.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/PaperWalletCreateStore.js
  app/stores/ada/TrezorSendStore.js
  app/stores/base/WalletSettingsStore.js
  app/stores/toplevel/ProfileStore.js
  app/stores/toplevel/UiNotificationsStore.js
  app/themes/skins/FormFieldOwnSkin.js
  app/themes/skins/InputOwnSkin.js
  app/utils/routing.js
  chrome/manifest.template.js
  chrome/manifestEnvs.js
  features/mock-chain/mockImporter.js
  features/mock-chain/mockServer.js
  scripts/compress.js
Labels: NFC

#950 Add no-floating-promise
  .eslintrc
  features/step_definitions/common-steps.js
  package-lock.json
  package.json
Labels: NFC
