Repository Emurgo/yoroi-frontend, pull requests merged in 2019-01, with the labels that each got.

#213 added default wallet type to CWTWeb if given type is undefined
  app/domain/Wallet.js
Labels: bug (confirmed)

#218 [doc update] app/i18n
  app/i18n/README.md
Labels: NFC

#219 change password restrictions
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  app/utils/validations.js
  features/settings-ui.feature
  features/support/mockData.json
  features/transactions.feature
  features/wallet-creation.feature
  features/wallet-restoration.feature
Labels: UI/UX, small-scale change

#197 upgrade to react 16 and react-router v4
  app/App.js
  app/Routes.js
  app/routes-config.js
  chrome/extension/index.js
  package-lock.json
  package.json
Labels: WIP / DO NOT MERGE, refactoring

#119 Babel 7 + Latest Flow + Other necessary dependencies
  .babelrc
  .flowconfig
  app/App.js
  app/Routes.js
  app/routes-config.js
  chrome/extension/index.js
  flow/declarations/mobx.js
  package-lock.json
  package.json
  webpack/development.config.js
Labels: refactoring

#231 remove unused exports
  app/components/topbar/banners/TestnetWarningBanner.js
  app/components/wallet/WalletSettings.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/skins/AmountInputSkin.js
  app/containers/LoadingPage.js
  app/containers/wallet/WalletReceivePage.js
  app/containers/wallet/WalletSummaryPage.js
Labels: NFC

#232 Fix vulnerability in reactdom 16.0.0
  package-lock.json
  package.json
Labels: bug (confirmed), fix for next version

#228 fix password validation
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
Labels: bug (confirmed), downgraded, fix for next version

#233 log time even on empty logs
  app/utils/logging.js
Labels: NFC

#242 Fix onClick in WalletSendConfirmationDialog
  app/components/wallet/send/WalletSendConfirmationDialog.js
Labels: bug (confirmed)

#243 fix missing color
  app/themes/prebuilt/yoroi.js
Labels: UI/UX, bug (confirmed), downgraded

#246 Fix onClick in TrezorSendConfirmationDialog
  app/components/wallet/send/trezor/TrezorSendConfirmationDialog.js
Labels: bug (confirmed)

#222 Export transaction to file [ITERATION 1]
  .circleci/config.yml
  .eslintrc
  LICENSE
  app/actions/ada/transactions-actions.js
  app/api/ada/index.js
  app/api/ada/lib/test-config.js
  app/api/ada/lib/utils.js
  app/api/ada/lib/utils.test.js
  app/api/common.js
  app/api/export/index.js
  app/api/export/index.test.js
  app/api/export/utils.js
  app/api/index.js
  app/assets/images/transaction/export-tx-to-file.inline.svg
  app/components/wallet/export/ExportTransactionDialog.js
  app/components/wallet/export/ExportTransactionDialog.scss
  app/components/wallet/summary/WalletSummary.js
  app/components/wallet/summary/WalletSummary.scss
  app/containers/wallet/WalletSummaryPage.js
  app/i18n/LocalizableError.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/ada/TrezorSendStore.js
  app/themes/prebuilt/yoroi.js
  flow-typed/npm/jest_v23.x.x.js
  package-lock.json
  package.json
Labels: new scenario (approved)

#223 Added basic UML diagrams
  docs/architecture/README.txt
  docs/architecture/images/component-diagram.png
  docs/architecture/images/sequence-diagrams.png
  docs/architecture/modelio-project.zip
Labels: NFC, help wanted

#270 Fix manage-translations
  app/i18n/locales/en-US.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  package-lock.json
  package.json
Labels: bug (confirmed), downgraded

#273 Fix Japanese ToS
  app/i18n/locales/terms-of-use/ada/ja-JP.md
Labels: NFC, UI/UX

#271 Update test section of README
  README.md
Labels: NFC
