Repository Emurgo/yoroi-frontend, pull requests merged in 2019-02, with the labels that each got.

#278 Unify to Rust stable version
  .circleci/config.yml
  docs/SETUP.md
  features/localCI/post_copy.sh
Labels: NFC

#283 Fix occasionally broken test
  features/localCI/create.sh
  features/localCI/post_copy.sh
  features/step_definitions/wallet-creation-steps.js
Labels: NFC, bug (confirmed), downgraded

#272 German + French support
  app/App.js
  app/i18n/global-messages.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/terms-of-use/ada/de-DE.md
  app/i18n/locales/terms-of-use/ada/fr-FR.md
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  app/stores/toplevel/ProfileStore.js
  crowdin.yml
  translations/translation-runner.js
Labels: UI/UX, WIP / DO NOT MERGE

#282 Refactoring the footer
  app/components/footer/FooterItem.js
  app/components/footer/FooterItem.scss
  app/components/footer/HelpLinkFooter.js
  app/components/layout/HorizontalFlexContainer.js
  app/components/layout/HorizontalFlexContainer.scss
  app/containers/footer/AddWalletFooter.js
  app/containers/wallet/WalletAddPage.js
Labels: UI/UX, bug (confirmed)

#294 fix warn logging
  app/utils/logging.js
Labels: small-scale change

#295 Temporarily remove FR + DE
  app/stores/toplevel/ProfileStore.js
Labels: fix for next version

#297 Fix bad string
  app/components/wallet/ada-redemption/AdaRedemptionDisclaimer.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/defaultMessages.json
  app/i18n/locales/en-US.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: NFC

#303 Disable Redemption for non-(EN+JP)
  app/components/settings/menu/SettingsMenu.js
  app/containers/settings/Settings.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/en-US.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
Labels: UI/UX, small-scale change

#305 fix YT link in About Yoroi
  app/components/settings/categories/AboutYoroiSettings.js
Labels: bug (confirmed)

#312 Release Prep changes
  app/components/settings/menu/SettingsMenu.js
  app/containers/settings/Settings.js
  app/i18n/locales/fr-FR.json
  app/stores/toplevel/ProfileStore.js
Labels: small-scale change

#318 Re-enable German
  app/stores/toplevel/ProfileStore.js
Labels: small-scale change

#317 Misc small fixes
  app/config/numbersConfig.js
  app/containers/settings/categories/DisplaySettingsPage.js
  app/i18n/README.md
  app/i18n/locales/en-US.json
  app/utils/validations.js
  docs/RELEASE.md
Labels: NFC

#319 Disable themes on mainnet
  app/components/settings/menu/SettingsMenu.js
Labels: fix for next version
