Repository Emurgo/yoroi-frontend, pull requests merged in 2019-07, with the labels that each got.

#729 Fix hot reload on yoroi extension
  app/Routes.js
  app/config/topbarConfig.js
  app/containers/TopBarContainer.js
  app/containers/settings/Settings.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/wallet/AdaRedemptionPage.js
  app/containers/wallet/NoWalletsPage.js
  app/containers/wallet/WalletSummaryPage.js
  app/stores/toplevel/TopbarStore.js
  app/utils/imports.js
Labels: NFC, bug (confirmed)

#584 Paper Wallet GIF Loader
  app/assets/images/paper-wallet/create-paper-wallet-loader-classic.gif
  app/assets/images/paper-wallet/create-paper-wallet-loader-modern.gif
  app/assets/images/paper-wallet/download-certificate-classic.inline.svg
  app/assets/images/paper-wallet/download-certificate-modern.inline.svg
  app/components/wallet/settings/paper-wallets/CreatePaperDialog.js
  app/components/wallet/settings/paper-wallets/CreatePaperDialog.scss
  app/i18n/locales/en-US.json
  app/stores/ada/PaperWalletCreateStore.js
  app/themes/prebuilt/Common.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, fix for next version

#736 Make NODE_ENV always either `production` or `development`
  app/environment.js
  scripts/build.js
  scripts/start.js
  webpack/commonConfig.js
  webpack/devConfig.js
  webpack/prodConfig.js
Labels: NFC

#716 shin/ch1631/increase-line-space-in-trezor-ledger-prerequisites
  app/components/wallet/hwConnect/common/CheckDialog.scss
Labels: UI/UX, fix for next version

#735 Bold labels in General Settings
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.js
  app/components/settings/categories/general-setting/ThemeSettingsBlock.js
  app/i18n/locales/en-US.json
Labels: UI/UX, fix for next version

#720 shin/ch1627/fix-title-in-receive-page
  app/components/wallet/WalletReceive.scss
Labels: UI/UX, fix for next version

#722 Fixing text style in terms of use
  app/components/profile/terms-of-use/TermsOfUseText.scss
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, fix for next version

#707 [bugfix] Use fit-content on checkbox
  app/components/wallet/send/WalletSendForm.scss
  app/themes/overrides/CheckboxOverrides.scss
  app/themes/overrides/CheckboxOverridesClassic.scss
Labels: bug (confirmed), fix for next version

#548 Form Field Icons YoroiClassic
  app/components/settings/SettingsLayout.scss
  app/components/settings/categories/PaperWalletSettings.scss
  app/components/settings/categories/general-setting/GeneralSettings.scss
  app/components/settings/menu/SettingsMenu.js
  app/components/settings/menu/SettingsMenu.scss
  app/components/settings/menu/SettingsMenuItem.scss
  app/components/transfer/TransferMasterKeyPage.js
  app/components/transfer/TransferMasterKeyPage.scss
  app/components/transfer/TransferMnemonicPage.js
  app/components/transfer/TransferMnemonicPage.scss
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletCreateDialog.scss
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/WalletRestoreDialog.scss
  app/components/wallet/ada-redemption/AdaRedemptionForm.js
  app/components/wallet/backup-recovery/WalletBackupPrivacyWarningDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.js
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.scss
  app/components/wallet/skins/AmountInputSkin.js
  app/components/wallet/skins/AmountInputSkin.scss
  app/components/widgets/forms/InlineEditingInput.js
  app/components/widgets/forms/InlineEditingInput.scss
  app/components/widgets/forms/PasswordInstructions.scss
  app/components/widgets/forms/ReadOnlyInput.js
  app/components/widgets/forms/ReadOnlyInput.scss
  app/i18n/locales/en-US.json
  app/themes/overrides/AutocompleteOverrides.scss
  app/themes/overrides/AutocompleteOverridesClassic.scss
  app/themes/overrides/FormFieldOverridesClassic.scss
  app/themes/overrides/InputOverridesClassic.scss
  app/themes/overrides/SelectOverridesClassic.scss
  app/themes/skins/FormFieldOwnSkin.scss
  features/step_definitions/transactions-steps.js
  features/transactions.feature
Labels: UI/UX, fix for next version

#738 Fix hot-reload for dialogs
  app/App.js
  app/stores/toplevel/UiDialogsStore.js
Labels: NFC, bug (confirmed)

#740 shin/ch1677/change-Mb-to-MB-for-file-size
  app/components/wallet/settings/paper-wallets/CreatePaperDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX, fix for next version

#693 server status endpoint spec
  docs/specs/code/SERVER_STATUS_ENDPOINT.md
  docs/specs/images/banner_example_1.png
  docs/specs/images/banner_example_2.png
Labels: fix for next version, spec

#721 Matching the style of address and derivation path with InVision slide
  app/components/wallet/receive/VerifyAddressDialog.js
  app/components/wallet/receive/VerifyAddressDialog.scss
Labels: UI/UX, fix for next version

#690 server status endpoint
  app/api/ada/errors.js
  app/api/ada/lib/state-fetch/IFetcher.js
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/api/ada/lib/state-fetch/remoteFetcher.js
  app/api/ada/lib/state-fetch/types.js
  app/api/ada/lib/test-config.js
  app/components/topbar/banners/ServerErrorBanner.js
  app/components/topbar/banners/ServerErrorBanner.scss
  app/containers/MainLayout.js
  app/containers/profile/LanguageSelectionPage.js
  app/containers/profile/TermsOfUsePage.js
  app/containers/settings/Settings.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/wallet/NoWalletsPage.js
  app/containers/wallet/Wallet.js
  app/containers/wallet/WalletAddPage.js
  app/environment.js
  app/i18n/locales/en-US.json
  app/stores/ada/ServerConnectionStore.js
  app/stores/ada/index.js
  app/types/serverStatusErrorType.js
  config/config-types.js
  config/development.json
  config/mainnet.json
  config/staging.json
  config/test.json
  config/testnet.json
  features/main-ui.feature
  features/mock-chain/mockImporter.js
  features/mock-chain/mockServer.js
  features/step_definitions/common-steps.js
  features/step_definitions/main-ui-steps.js
Labels: UI/UX, fix for next version, spec-implementation

#719 shin/ch1628/fix-text-style-in-settings-paper-wallets
  app/components/settings/categories/PaperWalletSettings.scss
  app/i18n/locales/paper-wallets/intro/en-US.md
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  app/themes/skins/CheckboxOwnSkin.js
  app/themes/skins/CheckboxOwnSkin.scss
Labels: UI/UX, fix for next version

#741 yanko/ch1513/remove-white-line-in-front-page
  app/assets/images/add-wallet/add-wallet-bg-modern.inline.svg
Labels: UI/UX, fix for next version

#706 Matching Restore Wallet dialog style
  app/components/wallet/add/option-dialog/OptionBlock.scss
  app/components/wallet/add/option-dialog/WalletRestoreOptionDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX, fix for next version

#745 Enable Indonesian on prod
  app/stores/toplevel/ProfileStore.js
Labels: UI/UX

#733 Upgrade Mobx & related libraries to v5
  .flowconfig
  app/components/profile/language-selection/LanguageSelectionForm.js
  app/components/settings/categories/PaperWalletSettings.js
  app/components/settings/categories/general-setting/ExplorerSettings.js
  app/components/settings/categories/general-setting/GeneralSettings.js
  app/components/transfer/TransferMasterKeyPage.js
  app/components/transfer/TransferMnemonicPage.js
  app/components/uri/URIGenerateDialog.js
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/ada-redemption/AdaRedemptionForm.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.js
  app/components/widgets/forms/InlineEditingInput.js
  app/containers/wallet/WalletReceivePage.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/base/TransactionsStore.js
  app/stores/toplevel/LoadingStore.js
  app/stores/toplevel/UiDialogsStore.js
  chrome/extension/index.js
  flow-typed/npm/mobx-react-router.js
  flow-typed/npm/mobx-react.js
  flow/declarations/mobx.js
  package-lock.json
  package.json
Labels: NFC

#723 Removing line in Tx list in classic theme
  app/components/wallet/transactions/Transaction.scss
Labels: UI/UX, fix for next version

#734 fixing columns alignment in Tx list
  app/components/wallet/transactions/Transaction.scss
Labels: UI/UX, fix for next version

#727 Small UI fixes
  app/actions/wallet-backup-actions.js
  app/components/wallet/WalletBackupDialog.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseDisplayDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.js
  app/components/widgets/forms/PasswordInstructions.js
  app/containers/wallet/dialogs/WalletBackupDialogContainer.js
  app/i18n/locales/en-US.json
  app/stores/toplevel/WalletBackupStore.js
Labels: UI/UX, fix for next version

#724 Hide dialog scrollbar if window height is available
  app/components/widgets/Dialog.scss
Labels: UI/UX, fix for next version

#742 Black label for input fields in classic theme
  app/themes/skins/FormFieldOwnSkin.scss
Labels: UI/UX, fix for next version

#744 yanko/ch1632/fix-text-color-start-page
  app/components/wallet/WalletAdd.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, fix for next version

#757 Fix hmr on css
  webpack/commonConfig.js
Labels: NFC

#739 Add warning for URI Scheme and change warning box UI
  app/assets/images/attention-classic.inline.svg
  app/assets/images/attention-modern.inline.svg
  app/components/transfer/AnnotatedLoader.js
  app/components/transfer/AnnotatedLoader.scss
  app/components/transfer/TransferWaitingPage.js
  app/components/transfer/TransferWaitingPage.scss
  app/components/uri/URIDisplayDialog.js
  app/components/uri/URIDisplayDialog.scss
  app/components/uri/URIGenerateDialog.scss
  app/components/wallet/send/HWSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.js
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/send/WalletSendForm.scss
  app/components/widgets/WarningBox.js
  app/components/widgets/WarningBox.scss
  app/components/widgets/forms/WarningBox.js
  app/components/widgets/forms/WarningBox.scss
  app/containers/transfer/DaedalusTransferWaitingPage.js
  app/i18n/locales/en-US.json
  app/themes/prebuilt/Common.js
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX, fix for next version

#730 shin/ch1630/fix-links-style-in-settings-support
  app/components/settings/categories/SupportSettings.js
  app/components/settings/categories/SupportSettings.scss
Labels: UI/UX, fix for next version

#751 shin/ch1696/fix-generate-url-dialog
  app/components/uri/URIGenerateDialog.js
  app/components/uri/URIGenerateDialog.scss
Labels: UI/UX, fix for next version

#756 Shin/ch1699/fix classic theme block title style
  app/components/transfer/TransferInstructionsPage.scss
  app/components/transfer/TransferMasterKeyPage.scss
  app/components/transfer/TransferMnemonicPage.scss
  app/components/wallet/WalletReceive.scss
Labels: UI/UX, fix for next version

#748 Downloads Logs button in Support section
  app/components/settings/categories/SupportSettings.js
  app/components/settings/categories/SupportSettings.scss
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
Labels: UI/UX, fix for next version

#775 Update localci steps
  features/README.md
  features/localCI/setup.sh
Labels: NFC

#754 Prep work for URI Prompt page
  app/actions/profile-actions.js
  app/containers/profile/LanguageSelectionPage.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/toplevel/LoadingStore.js
  app/stores/toplevel/ProfileStore.js
  app/uri-protocols.js
  app/utils/userAgentInfo.js
  features/migration.feature
  features/step_definitions/migration-steps.js
  features/support/helpers/i18n-helpers.js
Labels: NFC

#776 Implement UI for URI Scheme Prompt
  app/Routes.js
  app/actions/profile-actions.js
  app/api/localStorage/index.js
  app/assets/images/uri/about-url-classic.inline.svg
  app/assets/images/uri/about-url.inline.svg
  app/assets/images/uri/uri-prompt.inline.svg
  app/components/profile/uri-prompt/UriAccept.js
  app/components/profile/uri-prompt/UriAccept.scss
  app/components/profile/uri-prompt/UriPromptForm.js
  app/components/profile/uri-prompt/UriPromptForm.scss
  app/components/profile/uri-prompt/UriSkip.js
  app/components/profile/uri-prompt/UriSkip.scss
  app/components/settings/categories/general-setting/UriSettingsBlock.js
  app/components/settings/categories/general-setting/UriSettingsBlock.scss
  app/components/widgets/WarningBox.scss
  app/containers/profile/UriPromptPage.js
  app/containers/settings/categories/GeneralSettingsPage.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/routes-config.js
  app/stores/toplevel/ProfileStore.js
  app/utils/tabManager.js
  features/step_definitions/common-steps.js
  features/support/webdriver.js
Labels: UI/UX, spec-implementation

#779 Fix registration on firefox and websites
  app/containers/settings/categories/GeneralSettingsPage.js
  app/stores/toplevel/ProfileStore.js
  app/uri-protocols.js
  app/utils/userAgentInfo.js
Labels: bug (confirmed), fix for next version

#746 Bump to 1.8.0
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  chrome/manifest.test.json
  chrome/manifest.testnet.json
  package-lock.json
  package.json
Labels: NFC, WIP / DO NOT MERGE

#789 Add changes from 1.8.1 into develop
  app/i18n/locales/ko-KR.json
  app/i18n/locales/paper-wallets/intro/ko-KR.md
  app/i18n/locales/ru-RU.json
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  chrome/manifest.test.json
  chrome/manifest.testnet.json
  package-lock.json
  package.json
Labels: UI/UX

#795 (hotfix) fix scrollbar on prompt
  app/components/profile/uri-prompt/UriAccept.scss
  app/components/profile/uri-prompt/UriPromptForm.scss
  app/components/profile/uri-prompt/UriSkip.scss
Labels: UI/UX, bug (confirmed)

#796 Port Master hotfix into develop
  app/components/profile/uri-prompt/UriAccept.scss
  app/components/profile/uri-prompt/UriPromptForm.scss
  app/components/profile/uri-prompt/UriSkip.scss
Labels: UI/UX, bug (confirmed)

#797 bump version to 1.8.2
  chrome/manifest.development.json
  chrome/manifest.mainnet.json
  chrome/manifest.staging.json
  chrome/manifest.test.json
  chrome/manifest.testnet.json
  package-lock.json
  package.json
Labels: NFC

#813 Revert "Bump @babel/core from 7.5.0 to 7.5.4"
  package-lock.json
  package.json
Labels: bug (confirmed)

#812 Attempt to fix some CI test issues
  features/main-ui.feature
  features/migration.feature
  features/step_definitions/transactions-steps.js
  features/step_definitions/tx-history-steps.js
  features/transactions.feature
  features/wallet-restoration.feature
Labels: NFC

#814 Bump babel core from 7.5.0 to 7.5.4
  package-lock.json
  package.json
Labels: NFC

#818 silence the mock server during e2e tests
  features/mock-chain/mockServer.js
  scripts/startWithMockServer.js
Labels: low prio

#819 Replace Flow hack
  app/api/ada/lib/cardanoCrypto/rustLoader.js
  flow/declarations/cardano-wasm.js
  jest.config.js
  webpack/commonConfig.js
Labels: NFC

#844 Fixing for eslint warnings
  app/components/wallet/transactions/Transaction.js
  app/components/widgets/forms/PasswordInstructions.js
  app/containers/wallet/WalletReceivePage.js
  app/stores/ada/StateFetchStore.js
  app/stores/toplevel/ProfileStore.js
Labels: NFC

#845 Refactor wallet creation
  app/actions/wallet-backup-actions.js
  app/components/wallet/WalletBackupDialog.js
  app/components/wallet/backup-recovery/WalletRecoveryPhraseEntryDialog.js
  app/stores/ada/PaperWalletCreateStore.js
  app/stores/base/WalletStore.js
  app/stores/toplevel/WalletBackupStore.js
Labels: NFC

#846 Unregister protocol before trying to register
  app/components/profile/uri-prompt/UriAccept.js
  app/components/profile/uri-prompt/UriAccept.scss
  app/components/profile/uri-prompt/UriSkip.js
  app/components/settings/categories/general-setting/UriSettingsBlock.js
  app/containers/profile/UriPromptPage.js
  app/containers/settings/categories/GeneralSettingsPage.js
  app/i18n/global-messages.js
  app/uri-protocols.js
Labels: UI/UX, small-scale change

#847 shin/ch1826/ada-redemption-certificate-upload-not-working
  app/components/widgets/forms/AdaCertificateUploadWidget.js
Labels: regression

#851 Misc fixes
  .flowconfig
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/storage/adaAccount.js
  app/api/ada/lib/storage/adaMigration.js
  app/domain/HWSignTx.js
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: NFC

#849 Show testnet warning in language selection page
  app/containers/profile/LanguageSelectionPage.js
Labels: UI/UX, regression

#852 Removing PasswordInstructions component from Form dialogs
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.js
  app/components/widgets/forms/PasswordInstructions.js
  app/components/widgets/forms/PasswordInstructions.scss
  app/i18n/locales/en-US.json
Labels: UI/UX

#820 Disable buttons in Classic theme if form is not filled
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/hwConnect/ledger/SaveDialog.js
  app/components/wallet/hwConnect/trezor/SaveDialog.js
  app/components/wallet/settings/ChangeWalletPasswordDialog.js
  features/settings-ui.feature
  features/step_definitions/wallet-creation-steps.js
  features/wallet-creation.feature
  features/wallet-restoration.feature
Labels: UI/UX, fix for next version

#778 shin/ch1709/change-underline-to-custom-underline
  app/components/loading/Loading.js
  app/components/loading/Loading.scss
  app/components/settings/categories/SupportSettings.scss
  app/components/settings/categories/general-setting/ThemeSettingsBlock.js
  app/components/settings/categories/general-setting/ThemeSettingsBlock.scss
  app/components/settings/categories/general-setting/UriSettingsBlock.scss
  app/components/topbar/banners/TestnetWarningBanner.scss
  app/components/wallet/WalletReceive.scss
  app/components/wallet/hwConnect/common/CheckDialog.scss
  app/components/wallet/hwConnect/common/HelpLinkBlock.scss
  app/components/widgets/WarningBox.scss
  app/components/widgets/hashWrappers/ExplorableHash.scss
  app/containers/LoadingPage.js
  app/themes/mixins/underline.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#781 shin/ch1732/remove-old-footer-with-it-s-assets
  app/assets/fonts/Electrolize-Regular.ttf
  app/assets/fonts/Helvetica-Regular.otf
  app/assets/fonts/Montserrat-Medium.ttf
  app/assets/images/footer/buy-trezor.inline.svg
  app/assets/images/footer/how-to-connect-trezor.inline.svg
  app/assets/images/footer/how-to-create-wallet.inline.svg
  app/assets/images/footer/how-to-restore-wallet.inline.svg
  app/assets/images/footer/what-is-hardware-wallet.inline.svg
  app/components/footer/FooterItem.js
  app/components/footer/FooterItem.scss
  app/components/layout/TopBarLayout.js
  app/components/layout/TopBarLayout.scss
  app/containers/MainLayout.js
  app/containers/footer/AddWalletFooter.js
  app/themes/index.global.scss
  app/themes/prebuilt/YoroiModern.js
Labels: NFC

#787 leivaburto/ch1503/topbar-refactoring
  app/components/topbar/TopBar.js
  app/components/topbar/TopBarCategory.js
  app/config/topbarConfig.js
  app/containers/TopBarContainer.js
  app/containers/profile/LanguageSelectionPage.js
  app/containers/profile/TermsOfUsePage.js
  app/containers/profile/UriPromptPage.js
  app/containers/settings/Settings.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/wallet/WalletAddPage.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/toplevel/ProfileStore.js
  app/stores/toplevel/TopbarStore.js
Labels: NFC

#864 Flow server.max_workers fix
  .flowconfig
Labels: NFC

#863 Fix two Jest errors
  app/api/ada/adaTransactions/adaNewTransactions.test.js
  app/api/ada/adaWallet.test.js
  app/api/ada/daedalusTransfer.test.js
  app/api/ada/index.test.js
  app/api/ada/lib/storage/lovefieldDatabase.js
  jest.config.js
  package-lock.json
  package.json
Labels: NFC
