Repository Emurgo/yoroi-frontend, pull requests merged in 2019-10, with the labels that each got.

#951 No floating Promise Flow implementation
  .flowconfig
  app/api/ada/index.js
  app/stores/ada/AdaTransactionBuilderStore.js
  app/stores/ada/AdaWalletSettingsStore.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/TrezorConnectStore.js
  app/stores/ada/TrezorSendStore.js
  app/stores/base/WalletStore.js
  app/types/HWConnectStoreTypes.js
  features/support/helpers/language-selection-helpers.js
Labels: bug (confirmed)

#886 Fix password input spacing for create/restore dialogs in Classic theme
  app/components/wallet/WalletCreateDialog.js
  app/components/wallet/WalletCreateDialog.scss
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/WalletRestoreDialog.scss
Labels: UI/UX

#989 Update docker to node12
  .circleci/Dockerfile
  .circleci/README.md
Labels: NFC

#867 Draft spec for "unit of account"
  docs/specs/code/UNIT_OF_ACCOUNT.md
Labels: spec

#992 Offline transaction support
  app/api/ada/adaTransactions/transactionV2.test.js
  app/api/ada/adaTransactions/transactionsV2.js
  app/api/ada/hardwareWallet/hwTransactions.js
  app/api/ada/index.js
  app/api/ada/lib/storage/bridge/tests/multiwallet.test.js
  app/api/ada/lib/storage/bridge/tests/simpleTxs.test.js
  app/api/ada/lib/storage/bridge/tests/status.test.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/api/ada/lib/storage/database/utxoTransactions/api/read.js
  app/api/ada/lib/storage/models/PublicDeriver/index.js
  app/api/ada/lib/storage/models/PublicDeriver/interfaces.js
  app/api/ada/lib/storage/models/utils.js
  app/api/ada/lib/storage/tests/index.test.js
  app/api/ada/lib/utils.js
  app/stores/ada/AdaTransactionBuilderStore.js
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/TrezorSendStore.js
  app/stores/base/AddressesStore.js
  app/stores/base/TransactionsStore.js
  flow/declarations/cardano-wasm.js
Labels: small-scale change

#993 add shelley wasm bindings
  app/api/ada/adaTransactions/transactionV2.test.js
  app/api/ada/adaTransactions/transactionsV2.js
  app/api/ada/adaTypes.js
  app/api/ada/adaWallet.test.js
  app/api/ada/daedalusTransfer.js
  app/api/ada/daedalusTransfer.test.js
  app/api/ada/hardwareWallet/hwTransactions.js
  app/api/ada/index.js
  app/api/ada/lib/cardanoCrypto/cryptoWallet.js
  app/api/ada/lib/cardanoCrypto/rustLoader.js
  app/api/ada/lib/state-fetch/types.js
  app/api/ada/lib/storage/adaMigration.js
  app/api/ada/lib/storage/bridge/tests/common.js
  app/api/ada/lib/storage/bridge/walletHelper.js
  app/api/ada/lib/storage/models/utils.js
  app/api/ada/lib/storage/tests/index.test.js
  app/api/ada/lib/utils.js
  app/api/ada/restoreAdaWallet.js
  app/stores/ada/DaedalusTransferStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/ada/YoroiTransferStore.js
  app/types/TransferTypes.js
  app/utils/passwordCipher.js
  flow-typed/npm/js-chain-libs_v0.1.2.js
  jest.config.js
  package-lock.json
  package.json
Labels: NFC

#996 add shelley dev config
  app/components/wallet/WalletAdd.js
  app/environment.js
  babel.config.js
  chrome/manifest.shelley-dev.js
  config/config-types.js
  config/shelley-dev.json
  package.json
  webpack/customPublicPath.js
Labels: NFC

#995 Shelley UTXO transaction support
  app/api/ada/adaTypes.js
  app/api/ada/daedalusTransfer.js
  app/api/ada/hardwareWallet/README.md
  app/api/ada/index.js
  app/api/ada/lib/storage/bridge/tests/multiwallet.test.js
  app/api/ada/lib/test-config.js
  app/api/ada/lib/utils.js
  app/api/ada/transactions/legacy/hwTransactions.js
  app/api/ada/transactions/legacy/transactionV2.test.js
  app/api/ada/transactions/legacy/transactionsV2.js
  app/api/ada/transactions/utils.js
  app/api/ada/transactions/utxoTransactions.js
  app/api/ada/transactions/utxoTransactions.test.js
  config/config-types.js
  config/development.json
  config/mainnet.json
  config/staging.json
  config/test.json
  config/testnet.json
  flow-typed/npm/bech32_v1.1.x.js
  flow-typed/npm/js-chain-libs_v0.1.2.js
  flow/declarations/cardano-wasm.js
  package-lock.json
  package.json
Labels: small-scale change

#696 [SPEC] Add WebAuthn as new and default Ledger Transport
  docs/specs/code/hardware-wallets/ledger/BOLOS_SDK_SETUP.md
  docs/specs/code/hardware-wallets/ledger/FIRMWARE_UPDATE.md
  docs/specs/code/hardware-wallets/ledger/README.md
  docs/specs/code/hardware-wallets/trezor/README.md
Labels: spec

#884 shin/ch1886/add-webauthn-as-new-and-default-ledger-transport
  .eslintignore
  app/api/ada/hardwareWallet/newTransaction.js
  app/api/ada/index.js
  app/assets/images/top-bar/with-ledger-nano-logo.inline.svg
  app/components/topbar/TopBarCategory.scss
  app/components/wallet/receive/VerifyAddressDialog.js
  app/config.js
  app/config/topbarConfig.js
  app/containers/wallet/WalletSendPage.js
  app/domain/LedgerLocalizedError.js
  app/domain/Wallet.js
  app/i18n/locales/en-US.json
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/HWVerifyAddressStore.js
  app/stores/ada/LedgerConnectStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/toplevel/TopbarStore.js
  app/utils/hwConnectHandler.js
  app/utils/iframeHandler.js
  chrome/content-scripts/3rd-party-trezor/README.md
  chrome/content-scripts/3rd-party-trezor/trezor-content-script.js
  chrome/content-scripts/3rd-party-trezor/trezor-usb-permissions.html
  chrome/content-scripts/3rd-party-trezor/trezor-usb-permissions.js
  chrome/content-scripts/ledger/ledger-content-script.js
  chrome/manifest.template.js
  docs/specs/code/hardware-wallets/ledger/README.md
  jest.config.js
  package-lock.json
  package.json
  scripts/tasks.js
Labels: spec-implementation

#991 Fix null checks (sketchy lints)
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/components/profile/terms-of-use/TermsOfUseText.js
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/add/option-dialog/OptionBlock.js
  app/components/wallet/skins/AmountInputSkin.js
  app/components/widgets/Dialog.js
  app/components/widgets/DialogCloseButton.js
  app/components/widgets/DialogTextBlock.js
  app/stores/toplevel/ProfileStore.js
  app/themes/skins/InputOwnSkin.js
  app/utils/routing.js
Labels: fix for next version

#1009 shin/ch2050/fix-autocomplete-problems
  app/components/wallet/WalletRestoreDialog.js
Labels: fix for next version, regression

#1012 shin/ch2052/fix-select-component-label
  app/themes/overrides/FormFieldOverrides.scss
Labels: fix for next version, regression

#1011 shin/ch2051/fix-password-input-component
  app/components/wallet/WalletCreateDialog.scss
  app/components/wallet/WalletRestoreDialog.scss
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/settings/ChangeWalletPasswordDialog.scss
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.scss
  app/themes/prebuilt/YoroiModern.js
  app/themes/skins/FormFieldOwnSkin.js
Labels: fix for next version, regression

#1014 Merge develop into Shelley
  .circleci/chrome_webstore_deploy.sh
  app/api/ada/lib/state-fetch/batchedFetcher.js
  app/components/profile/terms-of-use/TermsOfUseText.js
  app/components/wallet/WalletCreateDialog.scss
  app/components/wallet/WalletRestoreDialog.js
  app/components/wallet/WalletRestoreDialog.scss
  app/components/wallet/add/option-dialog/OptionBlock.js
  app/components/wallet/send/WalletSendConfirmationDialog.scss
  app/components/wallet/settings/ChangeWalletPasswordDialog.scss
  app/components/wallet/settings/paper-wallets/UserPasswordDialog.scss
  app/components/wallet/skins/AmountInputSkin.js
  app/components/widgets/Dialog.js
  app/components/widgets/DialogCloseButton.js
  app/components/widgets/DialogTextBlock.js
  app/i18n/locales/de-DE.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr-FR.json
  app/i18n/locales/id-ID.json
  app/i18n/locales/it-IT.json
  app/i18n/locales/ja-JP.json
  app/i18n/locales/ko-KR.json
  app/i18n/locales/paper-wallets/intro/pt-BR.md
  app/i18n/locales/pt-BR.json
  app/i18n/locales/ru-RU.json
  app/i18n/locales/terms-of-use/ada/id-ID.md
  app/i18n/locales/terms-of-use/ada/pt-BR.md
  app/i18n/locales/zh-Hans.json
  app/i18n/locales/zh-Hant.json
  app/stores/toplevel/ProfileStore.js
  app/themes/overrides/FormFieldOverrides.scss
  app/themes/prebuilt/YoroiModern.js
  app/themes/skins/FormFieldOwnSkin.js
  app/themes/skins/InputOwnSkin.js
  app/utils/routing.js
Labels: bug (confirmed)

#1015 shin/ch2061/fix-verify-paper-wallet-password-error
  app/components/wallet/WalletRestoreDialog.scss
Labels: fix for next version, regression

#1017 Only load local tx on "load more" button
  app/containers/wallet/WalletSummaryPage.js
  app/stores/base/TransactionsStore.js
Labels: bug (confirmed)
