Repository Emurgo/yoroi-frontend, pull requests merged in 2020-01, with the labels that each got.

#1277 Fix spinner condition for delegation page
  app/containers/wallet/staking/StakingDashboardPage.js
Labels: bug (confirmed)

#1278 Explorable pool id on dashboard
  app/components/wallet/staking/dashboard/Address.js
  app/components/wallet/staking/dashboard/Address.scss
  app/components/wallet/staking/dashboard/StakePool.js
  app/components/wallet/staking/dashboard/StakePool.scss
  app/containers/wallet/staking/StakingDashboardPage.js
Labels: UI/UX

#1279 Attempt to fix transaction-screen check on Firefox
  features/step_definitions/main-ui-steps.js
Labels: bug (confirmed)

#1282 Fix semver import
  app/api/ada/lib/storage/adaMigration.js
Labels: bug (confirmed)

#1284 Explain why reward may be lower than expected
  app/components/wallet/staking/dashboard/LessThanExpectedDialog.js
  app/components/wallet/staking/dashboard/LessThanExpectedDialog.scss
  app/components/wallet/staking/dashboard/UserSummary.js
  app/components/wallet/staking/dashboard/UserSummary.scss
  app/containers/wallet/staking/StakingDashboardPage.js
  app/i18n/locales/en-US.json
  app/themes/mixins/unordered-list.scss
Labels: UI/UX

#1285 Paged delegation dashboard
  app/assets/images/widget/page-nav/arrow-all.inline.svg
  app/assets/images/widget/page-nav/arrow-single.inline.svg
  app/components/wallet/staking/dashboard/StakingDashboard.js
  app/components/wallet/staking/dashboard/StakingDashboard.scss
  app/components/widgets/BarDecoration.js
  app/components/widgets/BarDecoration.scss
  app/components/widgets/PageSelect.js
  app/components/widgets/PageSelect.scss
  app/containers/wallet/staking/StakingDashboardPage.js
  app/stores/ada/DelegationStore.js
Labels: UI/UX

#1287 Fix sendall when small UTXO is included
  app/api/ada/transactions/shelley/inputSelection.js
  app/api/ada/transactions/shelley/utxoTransactions.js
  app/api/ada/transactions/shelley/utxoTransactions.test.js
  app/stores/ada/YoroiTransferStore.js
Labels: bug (confirmed)

#1309 Add another reason for lower-than-expected rewards
  app/components/wallet/staking/dashboard/LessThanExpectedDialog.js
  app/i18n/locales/en-US.json
Labels: UI/UX

#1310 Add support for undelegating
  app/api/ada/lib/storage/bridge/delegationUtils.js
  app/api/ada/lib/storage/bridge/tests/mockNetwork.js
  app/api/ada/lib/storage/bridge/utils.js
  app/components/wallet/staking/dashboard/StakePool.js
  app/components/wallet/staking/dashboard/StakePool.scss
  app/components/wallet/staking/dashboard/UndelegateDialog.js
  app/components/wallet/staking/dashboard/UndelegateDialog.scss
  app/containers/wallet/staking/StakingDashboardPage.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/stores/ada/DelegationStore.js
Labels: small-scale change

#1312 Improve wallet upgrade debugging
  app/api/ada/transactions/byron/daedalusTransfer.js
  app/api/ada/transactions/byron/yoroiTransfer.js
  app/api/ada/transactions/shelley/daedalusTransfer.js
  app/api/ada/transactions/shelley/yoroiTransfer.js
  app/api/ada/transactions/transfer/legacyDaedalus.test.js
  app/components/transfer/TransferSummaryPage.js
  app/components/wallet/transactions/Transaction.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/i18n/global-messages.js
Labels: UI/UX

#1313 Add option for user to clear transaction history without restoring wallet
  app/actions/ada/daedalus-transfer-actions.js
  app/actions/ada/wallet-settings-actions.js
  app/api/ada/lib/storage/adaMigration.js
  app/api/ada/lib/storage/bridge/tests/common.js
  app/api/ada/lib/storage/bridge/tests/multiwallet.test.js
  app/api/ada/lib/storage/bridge/tests/shelleyGroup.test.js
  app/api/ada/lib/storage/bridge/tests/simpleTxs.test.js
  app/api/ada/lib/storage/bridge/updateTransactions.js
  app/api/ada/lib/storage/database/legacy.js
  app/api/ada/lib/storage/database/primitives/api/read.js
  app/api/ada/lib/storage/database/primitives/api/write.js
  app/api/ada/lib/storage/database/primitives/tables.js
  app/api/ada/lib/storage/database/transactionModels/account/tables.js
  app/api/ada/lib/storage/database/transactionModels/utxo/tables.js
  app/api/ada/lib/storage/database/utils.js
  app/api/ada/lib/storage/database/walletTypes/core/api/read.js
  app/api/ada/lib/storage/database/walletTypes/core/api/write.js
  app/api/ada/lib/storage/models/PublicDeriver/traits.js
  app/api/ada/lib/storage/tests/adaMigration.test.js
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.js
  app/components/settings/categories/general-setting/AboutYoroiSettingsBlock.scss
  app/components/wallet/settings/ResyncBlock.js
  app/components/wallet/settings/ResyncBlock.scss
  app/components/wallet/settings/WalletSettings.js
  app/components/wallet/settings/WalletSettings.scss
  app/containers/settings/categories/GeneralSettingsPage.js
  app/containers/settings/categories/WalletSettingsPage.js
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/transfer/YoroiTransferPage.js
  app/containers/wallet/WalletSummaryPage.js
  app/domain/PublicDeriverWithCachedMeta.js
  app/environment.js
  app/i18n/locales/en-US.json
  app/stores/ada/AdaTransactionsStore.js
  app/stores/ada/AdaWalletSettingsStore.js
  app/stores/ada/AdaWalletsStore.js
  app/stores/ada/DelegationTransactionStore.js
  app/stores/ada/LedgerSendStore.js
  app/stores/base/AddressesStore.js
  app/stores/base/TransactionsStore.js
  app/stores/base/WalletStore.js
  app/stores/toplevel/ProfileStore.js
  babel.config.js
  chrome/constants.js
Labels: small-scale change

#1315 Approximate rewards UI properly compounds rewards
  app/actions/ada/delegation-transaction-actions.js
  app/api/ada/index.js
  app/api/ada/lib/storage/bridge/delegationUtils.js
  app/components/wallet/staking/dashboard/StakingDashboard.js
  app/components/wallet/staking/dashboard/StakingDashboard.scss
  app/components/wallet/transactions/WalletTransactionsList.js
  app/containers/wallet/staking/SeizaFetcher.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/stores/ada/DelegationTransactionStore.js
Labels: UI/UX, bug (confirmed)

#1316 Fix transaction assurance calculation
  app/api/ada/index.js
  app/api/ada/lib/storage/database/primitives/api/read.js
  app/domain/WalletTransaction.js
Labels: UI/UX

#1308 Multiwallet Topbar Dropdown
  app/assets/images/my-wallets/icon_eye_closed.inline.svg
  app/assets/images/my-wallets/icon_eye_open.inline.svg
  app/assets/images/wallet-nav/back-arrow.inline.svg
  app/assets/images/wallet-nav/caret-down.inline.svg
  app/assets/images/wallet-nav/conceptual-wallet.inline.svg
  app/assets/images/wallet-nav/paper-wallet.inline.svg
  app/assets/images/wallet-nav/tab-receive.inline.svg
  app/assets/images/wallet-nav/tab-send.inline.svg
  app/assets/images/wallet-nav/tab-transactions.inline.svg
  app/assets/images/wallet-nav/trezor-wallet.inline.svg
  app/components/layout/TopBarLayout.js
  app/components/layout/TopBarLayout.scss
  app/components/topbar/NavBar.js
  app/components/topbar/NavBar.scss
  app/components/topbar/NavBarBack.js
  app/components/topbar/NavBarBack.scss
  app/components/topbar/NavBarTitle.js
  app/components/topbar/NavBarTitle.scss
  app/components/topbar/NavDropdown.js
  app/components/topbar/NavDropdown.scss
  app/components/topbar/NavDropdownRow.js
  app/components/topbar/NavDropdownRow.scss
  app/components/topbar/NavPlate.js
  app/components/topbar/NavPlate.scss
  app/components/topbar/NavWalletDetails.js
  app/components/topbar/NavWalletDetails.scss
  app/components/wallet/layouts/WalletWithNavigation.scss
  app/components/wallet/navigation/WalletNavButton.js
  app/components/wallet/navigation/WalletNavButton.scss
  app/components/wallet/navigation/WalletNavigation.js
  app/components/wallet/navigation/WalletNavigation.scss
  app/containers/MainLayout.js
  app/containers/NavBarContainer.js
  app/containers/settings/Settings.js
  app/containers/transfer/Transfer.js
  app/containers/wallet/Wallet.js
  app/containers/wallet/staking/SeizaFetcher.js
  app/i18n/locales/en-US.json
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  features/step_definitions/common-steps.js
  features/step_definitions/main-ui-steps.js
  features/step_definitions/settings-ui-steps.js
  features/step_definitions/wallet-restoration-steps.js
  features/step_definitions/wallet-steps.js
Labels: UI/UX

#1318 Fix EpochProgress height in Dashboard
  app/components/wallet/staking/dashboard/EpochProgress.scss
Labels: UI/UX

#1319 Connect multiwallet UI to API
  app/components/notice-board/NoticeBoard.scss
  app/components/topbar/NavDropdownRow.js
  app/components/topbar/NavDropdownRow.scss
  app/components/topbar/NavPlate.js
  app/components/topbar/NavPlate.scss
  app/components/topbar/NavWalletDetails.js
  app/components/topbar/NavWalletDetails.scss
  app/components/transfer/TransferInstructionsPage.scss
  app/components/wallet/WalletAdd.js
  app/components/wallet/staking/dashboard/StakingDashboard.js
  app/components/wallet/staking/dashboard/StakingDashboard.scss
  app/components/wallet/transactions/WalletNoTransactions.scss
  app/components/widgets/CustomTooltip.js
  app/components/widgets/CustomTooltip.scss
  app/components/widgets/hashWrappers/ExplorableHash.scss
  app/containers/NavBarContainer.js
  app/containers/settings/Settings.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/containers/wallet/staking/StakingPage.js
  app/i18n/locales/en-US.json
  app/stores/ada/DelegationStore.js
  app/stores/ada/DelegationTransactionStore.js
  app/stores/base/AddressesStore.js
  app/stores/base/TransactionsStore.js
  app/stores/base/WalletStore.js
  app/stores/toplevel/ProfileStore.js
  app/themes/mixins/loading-spinner.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  app/utils/formatters.js
  features/step_definitions/common-steps.js
  features/step_definitions/settings-ui-steps.js
  features/step_definitions/wallet-steps.js
Labels: UI/UX

#1325 Design improvements for next reward
  app/api/ada/lib/storage/bridge/delegationUtils.js
  app/components/wallet/WalletAdd.js
  app/components/wallet/WalletAdd.scss
  app/components/wallet/staking/dashboard/EpochProgress.js
  app/components/wallet/staking/dashboard/EpochProgress.scss
  app/components/wallet/staking/dashboard/FirstRewardTooltip.js
  app/components/wallet/staking/dashboard/FirstRewardTooltip.scss
  app/components/wallet/staking/dashboard/RewardPopup.js
  app/components/wallet/staking/dashboard/RewardPopup.scss
  app/components/wallet/staking/dashboard/StakingDashboard.js
  app/components/wallet/staking/dashboard/StakingDashboard.scss
  app/components/wallet/staking/dashboard/UpcomingRewards.js
  app/components/wallet/staking/dashboard/UpcomingRewards.scss
  app/components/wallet/staking/dashboard/UserSummary.scss
  app/components/widgets/CustomTooltip.scss
  app/components/widgets/Timer.js
  app/components/widgets/Timer.scss
  app/containers/wallet/staking/StakingDashboardPage.js
  app/containers/widgets/ExplorableHashContainer.js
  app/domain/Explorer.js
  app/i18n/locales/en-US.json
  app/themes/prebuilt/YoroiModern.js
Labels: UI/UX

#1324 Settings tab navigation re-style
  app/components/settings/SettingsLayout.js
  app/components/settings/SettingsLayout.scss
  app/components/settings/categories/general-setting/ThemeSettingsBlock.scss
  app/components/settings/menu/SettingsMenu.scss
  app/components/settings/menu/SettingsMenuItem.scss
  app/components/wallet/navigation/WalletNavButton.scss
  app/themes/prebuilt/YoroiClassic.js
  features/step_definitions/daedalus-transfer-steps.js
  features/step_definitions/general-settings-steps.js
Labels: UI/UX

#1326 Fix a few small UI issues
  app/assets/images/wallet-nav/ledger-wallet.inline.svg
  app/components/topbar/NavPlate.js
  app/components/wallet/staking/dashboard/UpcomingRewards.js
  app/components/wallet/staking/dashboard/UpcomingRewards.scss
  app/components/widgets/forms/InlineEditingInput.scss
  app/stores/base/WalletStore.js
Labels: bug (confirmed)

#1327 Show users any mangled addresses they have
  app/Routes.js
  app/actions/ada/tx-builder-actions.js
  app/api/ada/index.js
  app/api/ada/lib/storage/bridge/delegationUtils.js
  app/api/ada/lib/storage/bridge/utils.js
  app/api/ada/lib/storage/models/utils.js
  app/assets/images/small-cross.inline.svg
  app/components/profile/terms-of-use/TermsOfUseForm.js
  app/components/topbar/NavDropdown.js
  app/components/transfer/TransferSummaryPage.js
  app/components/transfer/TransferSummaryPage.scss
  app/components/wallet/add/option-dialog/OptionBlock.js
  app/components/wallet/layouts/ReceiveWithNavigation.js
  app/components/wallet/navigation/ReceiveNavButton.js
  app/components/wallet/navigation/ReceiveNavButton.scss
  app/components/wallet/navigation/ReceiveNavigation.js
  app/components/wallet/receive/InternalHeader.js
  app/components/wallet/receive/InternalHeader.scss
  app/components/wallet/receive/MangledHeader.js
  app/components/wallet/receive/MangledHeader.scss
  app/components/wallet/receive/WarningHeader.js
  app/components/wallet/receive/WarningHeader.scss
  app/components/wallet/send/WalletSendForm.js
  app/components/wallet/staking/dashboard/UserSummary.js
  app/components/wallet/staking/dashboard/UserSummary.scss
  app/components/wallet/transactions/Transaction.js
  app/components/widgets/DialogCloseButton.scss
  app/components/widgets/TooltipBox.js
  app/components/widgets/TooltipBox.scss
  app/components/widgets/forms/DaedalusMasterKeyInput.js
  app/components/widgets/forms/InlineEditingInput.js
  app/components/widgets/forms/MnemonicInput.js
  app/components/widgets/forms/PaperPasswordInput.js
  app/components/widgets/forms/SpendingPasswordInput.js
  app/components/widgets/forms/SpendingPasswordInput.scss
  app/containers/transfer/DaedalusTransferPage.js
  app/containers/transfer/UnmangleTxDialogContainer.js
  app/containers/transfer/YoroiTransferPage.js
  app/containers/wallet/Receive.js
  app/containers/wallet/WalletReceivePage.js
  app/containers/wallet/dialogs/CreatePaperWalletDialogContainer.js
  app/containers/wallet/dialogs/WalletRestoreDialogContainer.js
  app/containers/wallet/staking/StakingDashboardPage.js
  app/i18n/global-messages.js
  app/i18n/locales/en-US.json
  app/routes-config.js
  app/stores/ada/AdaTransactionBuilderStore.js
  app/stores/ada/DelegationStore.js
  app/stores/base/AddressesStore.js
  app/themes/mixins/unordered-list.scss
  app/themes/prebuilt/YoroiClassic.js
  app/themes/prebuilt/YoroiModern.js
  app/types/TransferTypes.js
Labels: small-scale change
