Repository Emurgo/yoroi-frontend, pull requests merged in 2021-07, with the labels that each got.

#2213 Cardano dApp-connector : Add read-access functions for cardano
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/chrome/extension/background.js
Labels: dapp-connector

#2216 [4.5.6] Dates update for Catalyst fund 5
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
Labels: catalyst

#2215 [4.5.6] Ledger support backport
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/lib/cardanoCrypto/catalyst.js
  packages/yoroi-extension/app/api/ada/lib/cardanoCrypto/catalyst.test.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/HaskellShelleyTxSignRequest.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/ledgerTx.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/ledgerTx.test.js
  packages/yoroi-extension/app/assets/images/pic-catalyst-step3-ledger.inline.svg
  packages/yoroi-extension/app/assets/images/pic-catalyst-step3-trezor.inline.svg
  packages/yoroi-extension/app/components/wallet/voting/ConfirmPinDialog.js
  packages/yoroi-extension/app/components/wallet/voting/GeneratePinDialog.js
  packages/yoroi-extension/app/components/wallet/voting/ProgressStepBlock.js
  packages/yoroi-extension/app/components/wallet/voting/QrCodeDialog.js
  packages/yoroi-extension/app/components/wallet/voting/RegisterDialog.js
  packages/yoroi-extension/app/components/wallet/voting/Voting.js
  packages/yoroi-extension/app/components/wallet/voting/Voting.scss
  packages/yoroi-extension/app/components/wallet/voting/VotingRegTxDialog.js
  packages/yoroi-extension/app/components/wallet/voting/VotingRegTxDialog.scss
  packages/yoroi-extension/app/components/wallet/voting/types.js
  packages/yoroi-extension/app/containers/wallet/WalletSendPage.js
  packages/yoroi-extension/app/containers/wallet/dialogs/voting/RegisterDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/dialogs/voting/TransactionDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/dialogs/voting/VotingRegistrationDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/app/domain/LedgerLocalizedError.js
  packages/yoroi-extension/app/i18n/global-messages.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/stores/ada/HWVerifyAddressStore.js
  packages/yoroi-extension/app/stores/ada/LedgerConnectStore.js
  packages/yoroi-extension/app/stores/ada/VotingStore.js
  packages/yoroi-extension/app/stores/ada/send/LedgerSendStore.js
  packages/yoroi-extension/features/mock-ledger-connect/index.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: hardware-wallets

#2217 Release / 4.5.6
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/lib/cardanoCrypto/catalyst.js
  packages/yoroi-extension/app/api/ada/lib/cardanoCrypto/catalyst.test.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/HaskellShelleyTxSignRequest.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/ledgerTx.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/ledgerTx.test.js
  packages/yoroi-extension/app/assets/images/pic-catalyst-step3-ledger.inline.svg
  packages/yoroi-extension/app/assets/images/pic-catalyst-step3-trezor.inline.svg
  packages/yoroi-extension/app/components/wallet/voting/ConfirmPinDialog.js
  packages/yoroi-extension/app/components/wallet/voting/GeneratePinDialog.js
  packages/yoroi-extension/app/components/wallet/voting/ProgressStepBlock.js
  packages/yoroi-extension/app/components/wallet/voting/QrCodeDialog.js
  packages/yoroi-extension/app/components/wallet/voting/RegisterDialog.js
  packages/yoroi-extension/app/components/wallet/voting/Voting.js
  packages/yoroi-extension/app/components/wallet/voting/Voting.scss
  packages/yoroi-extension/app/components/wallet/voting/VotingRegTxDialog.js
  packages/yoroi-extension/app/components/wallet/voting/VotingRegTxDialog.scss
  packages/yoroi-extension/app/components/wallet/voting/types.js
  packages/yoroi-extension/app/containers/wallet/WalletSendPage.js
  packages/yoroi-extension/app/containers/wallet/dialogs/voting/RegisterDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/dialogs/voting/TransactionDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/dialogs/voting/VotingRegistrationDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/app/domain/LedgerLocalizedError.js
  packages/yoroi-extension/app/i18n/global-messages.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/stores/ada/HWVerifyAddressStore.js
  packages/yoroi-extension/app/stores/ada/LedgerConnectStore.js
  packages/yoroi-extension/app/stores/ada/VotingStore.js
  packages/yoroi-extension/app/stores/ada/send/LedgerSendStore.js
  packages/yoroi-extension/features/mock-ledger-connect/index.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2219 [hotfix/4.5.7] Ledger instruction link fix
  packages/yoroi-extension/app/components/wallet/voting/Voting.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: hotfix

#2221 Nightly / 4.6-rc1
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/lib/state-fetch/mockNetwork.js
  packages/yoroi-extension/app/api/ada/lib/state-fetch/remoteFetcher.js
  packages/yoroi-extension/app/api/ada/lib/state-fetch/types.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/multiwallet.test.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/shelley.test.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/simpleTxs.test.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/status.test.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/updateTransactions.js
  packages/yoroi-extension/app/api/ada/lib/storage/database/primitives/api/write.js
  packages/yoroi-extension/app/api/ada/lib/storage/database/primitives/tables.js
  packages/yoroi-extension/app/api/ergo/lib/storage/bridge/updateTransactions.js
  packages/yoroi-extension/app/assets/images/close-cross.inline.svg
  packages/yoroi-extension/app/assets/images/cross-dark.inline.svg
  packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
  packages/yoroi-extension/app/components/wallet/add/option-dialog/WalletEraOptionDialog.js
  packages/yoroi-extension/app/components/wallet/navigation/WalletNavButton.scss
  packages/yoroi-extension/app/components/wallet/staking/dashboard/GraphWrapper.js
  packages/yoroi-extension/app/components/wallet/transactions/Transaction.js
  packages/yoroi-extension/app/components/wallet/transactions/Transaction.scss
  packages/yoroi-extension/app/components/widgets/DialogCloseButton.js
  packages/yoroi-extension/app/components/widgets/DialogCloseButton.scss
  packages/yoroi-extension/app/containers/NavBarContainer.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/stores/ada/AdaTransactionsStore.js
  packages/yoroi-extension/app/stores/stateless/tokenHelpers.js
  packages/yoroi-extension/app/stores/toplevel/TokenInfoStore.js
  packages/yoroi-extension/app/themes/prebuilt/YoroiModern.js
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: nightly, release

#2222 Nightly / 4.5.7001
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: nightly, release

#2226 Nightly / 4.5.7002
  packages/yoroi-extension/app/stores/toplevel/TokenInfoStore.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: nightly, release

#2228 Ruslan / Revert my own incorrect flow fix
  packages/yoroi-extension/app/stores/toplevel/TokenInfoStore.js
Labels: revert

#2224 Add cardano RPC
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/chrome/extension/background.js
Labels: dapp-connector

#2232 Ergo Connector: Fix for large token amounts
  packages/yoroi-ergo-connector/example/index.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
Labels: dapp-connector, ergo

#2238 Nightly / 4.5.7003
  packages/yoroi-ergo-connector/example/index.js
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/app/actions/ada/ledger-send-actions.js
  packages/yoroi-extension/app/actions/ada/trezor-send-actions.js
  packages/yoroi-extension/app/actions/wallet-actions.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/updateTransactions.js
  packages/yoroi-extension/app/components/wallet/send/TransactionSuccessDialog.js
  packages/yoroi-extension/app/containers/transfer/TransferSendPage.js
  packages/yoroi-extension/app/containers/wallet/WalletSendPage.js
  packages/yoroi-extension/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/stores/ada/send/AdaMnemonicSendStore.js
  packages/yoroi-extension/app/stores/ada/send/LedgerSendStore.js
  packages/yoroi-extension/app/stores/ada/send/TrezorSendStore.js
  packages/yoroi-extension/app/stores/ergo/send/ErgoMnemonicSendStore.js
  packages/yoroi-extension/app/stores/jormungandr/send/JormungandrMnemonicSendStore.js
  packages/yoroi-extension/app/stores/toplevel/WalletStore.js
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/chrome/extension/ergo-connector/types.js
  packages/yoroi-extension/chrome/extension/ergo-connector/utils.js
  packages/yoroi-extension/features/hardware.feature
  packages/yoroi-extension/features/step_definitions/transactions-steps.js
  packages/yoroi-extension/features/transactions.feature
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: nightly

#2244 dapp-connector inject some fixes
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/chrome/extension/background.js
Labels: dapp-connector

#2234 Get rid of some type coersions in Ergo connector store initialization code
  packages/yoroi-extension/app/ergo-connector/stores/index.js
  packages/yoroi-extension/app/stores/index.js
  packages/yoroi-extension/app/stores/toplevel/StateFetchStore.js
  packages/yoroi-extension/app/stores/toplevel/TokenInfoStore.js
Labels: ergo

#2245 ergo-lib updated to 0.14.0-alpha.
  package-lock.json
  packages/yoroi-ergo-connector/example/package-lock.json
  packages/yoroi-ergo-connector/example/package.json
  packages/yoroi-extension/flow-typed/npm/ergo-lib-wasm-browser_vx.x.x.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: ergo

#2248 Flow warn fixes
  packages/yoroi-extension/app/api/ada/lib/state-fetch/remoteFetcher.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/updateTransactions.js
  packages/yoroi-extension/app/api/ergo/lib/storage/bridge/updateTransactions.js
  packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
Labels: NFC

#2256 Nightly / 4.5.7005
  packages/yoroi-ergo-connector/example/index.js
  packages/yoroi-extension/app/api/ergo/index.js
  packages/yoroi-extension/app/api/ergo/lib/state-fetch/remoteFetcher.js
  packages/yoroi-extension/app/ergo-connector/containers/ConnectContainer.js
  packages/yoroi-extension/app/stores/toplevel/ProfileStore.js
  packages/yoroi-extension/features/memo.feature
  packages/yoroi-extension/features/migration.feature
  packages/yoroi-extension/features/settings-ui.feature
  packages/yoroi-extension/features/step_definitions/common-steps.js
  packages/yoroi-extension/features/yoroi-transfer.feature
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: nightly
