Repository Emurgo/yoroi-frontend, pull requests merged in 2021-09, with the labels that each got.

#2252 add Alanzo white testnet wallet
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/__snapshots__/multiwallet.test.js.snap
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/__snapshots__/shelley.test.js.snap
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/__snapshots__/simpleTxs.test.js.snap
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/__snapshots__/status.test.js.snap
  packages/yoroi-extension/app/api/ada/lib/storage/database/prepackaged/explorers.js
  packages/yoroi-extension/app/api/ada/lib/storage/database/prepackaged/networks.js
  packages/yoroi-extension/app/api/ada/lib/storage/tests/__snapshots__/index.test.js.snap
  packages/yoroi-extension/app/api/ergo/lib/storage/bridge/tests/__snapshots__/simpleTxs.test.js.snap
  packages/yoroi-extension/app/api/jormungandr/lib/storage/bridge/tests/__snapshots__/jormungandrGroup.test.js.snap
  packages/yoroi-extension/app/api/jormungandr/lib/storage/bridge/tests/__snapshots__/multiwallet.test.js.snap
  packages/yoroi-extension/app/api/jormungandr/lib/storage/bridge/tests/__snapshots__/simpleTxs.test.js.snap
  packages/yoroi-extension/app/api/jormungandr/lib/storage/bridge/tests/__snapshots__/status.test.js.snap
  packages/yoroi-extension/app/components/wallet/add/option-dialog/PickCurrencyOptionDialog.js
  packages/yoroi-extension/app/components/widgets/options/OptionBlock.scss
  packages/yoroi-extension/app/containers/wallet/WalletAddPage.js
  packages/yoroi-extension/app/containers/wallet/dialogs/PickCurrencyDialogContainer.js
Labels: alonzo

#2367 Hotfix / 4.6.200 Catalyst Dates
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release, hotfix

#2285 Ergo connector p2s signature
  install-all.sh
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/traitUtils.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/utxoTransaction.js
  packages/yoroi-extension/app/components/widgets/tokenOption/TokenOptionRow.js
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/flow-typed/npm/ergo-lib-wasm-browser_vx.x.x.js
Labels: ergo, dapp-connector

#2388 [hot/4.7.100] Don't show total rewards and disable withdraw
  packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard/UserSummary.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: hotfix

#2404 Release / 4.7.300
  packages/yoroi-extension/app/Routes.js
  packages/yoroi-extension/app/api/ada/lib/cardanoCrypto/rustLoader.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/HaskellShelleyTxSignRequest.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/ledgerTx.test.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.test.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/trezorTx.test.js
  packages/yoroi-extension/app/api/common/errors.js
  packages/yoroi-extension/app/api/common/index.js
  packages/yoroi-extension/app/api/common/lib/transactions/ISignRequest.js
  packages/yoroi-extension/app/assets/images/assets-page/arrows-list-from-bottom.inline.svg
  packages/yoroi-extension/app/assets/images/assets-page/arrows-list-from-top.inline.svg
  packages/yoroi-extension/app/assets/images/assets-page/arrows-list.inline.svg
  packages/yoroi-extension/app/assets/images/assets-page/asset-no.inline.svg
  packages/yoroi-extension/app/assets/images/assets-page/assets.inline.svg
  packages/yoroi-extension/app/assets/images/assets-page/info.inline.svg
  packages/yoroi-extension/app/assets/images/assets-page/search.inline.svg
  packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
  packages/yoroi-extension/app/components/wallet/assets/AssetsList.js
  packages/yoroi-extension/app/components/wallet/assets/AssetsList.scss
  packages/yoroi-extension/app/components/wallet/assets/AssetsPage.js
  packages/yoroi-extension/app/components/wallet/assets/AssetsPage.scss
  packages/yoroi-extension/app/components/wallet/send/WalletSendConfirmationDialog.js
  packages/yoroi-extension/app/components/wallet/send/WalletSendConfirmationDialog.scss
  packages/yoroi-extension/app/containers/NavBarContainer.js
  packages/yoroi-extension/app/containers/wallet/Wallet.js
  packages/yoroi-extension/app/containers/wallet/Wallet.mock.js
  packages/yoroi-extension/app/containers/wallet/WalletAssetsPage.js
  packages/yoroi-extension/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  packages/yoroi-extension/app/i18n/global-messages.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/routes-config.js
  packages/yoroi-extension/app/stores/stateless/tokenHelpers.js
  packages/yoroi-extension/app/stores/stateless/topbarCategories.js
  packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
  packages/yoroi-extension/stories/helpers/cardano/ByronMocks.js
  packages/yoroi-extension/stories/helpers/cardano/ShelleyCip1852Mocks.js
  packages/yoroi-extension/stories/helpers/ergo/ErgoMocks.js
  packages/yoroi-extension/stories/helpers/jormungandr/JormungandrMocks.js
Labels: release

#2409 asset deposit readme
  docs/readme/cardano-token-deposit-explained.md
Labels: documentation

#2391 Update sigma-rust to 0.14.0-alpha-a3940fc
  packages/yoroi-extension/app/api/ergo/lib/restore.test.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/ErgoExternalTxSignRequest.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/ErgoTxSignRequest.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/utxoTransaction.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/utxoTransaction.test.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: ergo, dapp-connector

#2412 Release / 4.7.400
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/components/buySell/BuySellDialog.js
  packages/yoroi-extension/app/components/topbar/BuySellAdaButton.js
  packages/yoroi-extension/app/components/topbar/NavPlate.js
  packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
  packages/yoroi-extension/app/components/topbar/NavWalletDetails.scss
  packages/yoroi-extension/app/components/wallet/add/option-dialog/WalletEraOptionDialog.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard/StakingDashboard.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard/UserSummary.js
  packages/yoroi-extension/app/containers/wallet/staking/StakingDashboardPage.js
  packages/yoroi-extension/app/i18n/global-messages.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release
