Repository Emurgo/yoroi-frontend, pull requests merged in 2021-05, with the labels that each got.

#2092 Catalyst Fund4 another date push
  .gitignore
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
Labels: catalyst

#2091 Remove repeated function
  packages/yoroi-ergo-connector/src/inject.js
Labels: ergo

#2093 Changed nightly build action to use `nightly` branch
  .github/workflows/main.yml
Labels: configs

#2094 Release/4.5.0
  .github/workflows/main.yml
  .gitignore
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/app/actions/ada/voting-actions.js
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/HaskellShelleyTxSignRequest.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/trezorTx.js
  packages/yoroi-extension/app/components/wallet/voting/Voting.js
  packages/yoroi-extension/app/components/wallet/voting/Voting.scss
  packages/yoroi-extension/app/containers/wallet/dialogs/voting/VotingRegistrationDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.stories.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/stores/ada/VotingStore.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2087 buid(yoroi-extension): buld scripts now compatible with Windows
  packages/yoroi-extension/docs/BUILD.md
  packages/yoroi-extension/docs/SETUP.md
  packages/yoroi-extension/package.json
Labels: configs

#2081 Data inputs + P2S support
  packages/yoroi-ergo-connector/example/index.js
  packages/yoroi-ergo-connector/example/package-lock.json
  packages/yoroi-ergo-connector/example/package.json
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: ergo

#2102 Ergo Connector Version bump 0.4.0
  packages/yoroi-ergo-connector/package-lock.json
  packages/yoroi-ergo-connector/package.json
Labels: dapp-connector, ergo

#2106 [quickfix] Release/4.5.2 Catalyst dates again
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2110 [quickfix] Release/4.5.3 Catalyst Dates Push
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2120 Sigma Rust some Flow fixes
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/package-lock.json
Labels: ergo
