Repository Emurgo/yoroi-frontend, pull requests merged in 2021-11, with the labels that each got.

#2523 [4.7.500] Reworked the reward amount parsing a bit
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/updateTransactions.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: hotfix

#2476 new tx-building API
  packages/yoroi-ergo-connector/example-cardano/index.html
  packages/yoroi-ergo-connector/example-cardano/index.js
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/api/common/lib/MultiToken.js
  packages/yoroi-extension/app/ergo-connector/components/signin/CardanoSignTxPage.js
  packages/yoroi-extension/app/ergo-connector/containers/SignTxContainer.js
  packages/yoroi-extension/app/ergo-connector/stores/ConnectorStore.js
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/chrome/extension/ergo-connector/types.js
Labels: dapp-connector

#2515 Improve the UI when connecting to a Ledger wallet
  packages/yoroi-extension/app/stores/ada/LedgerConnectStore.js
Labels: hardware-wallets

#2463 Redesign transaction page
  packages/yoroi-extension/app/actions/common/transactions-actions.js
  packages/yoroi-extension/app/assets/images/close.inline.svg
  packages/yoroi-extension/app/assets/images/transaction/export.inline.svg
  packages/yoroi-extension/app/assets/images/transaction/wallet-empty-banner.inline.svg
  packages/yoroi-extension/app/components/topbar/BuySellAdaButton.js
  packages/yoroi-extension/app/components/wallet/summary/WalletSummaryRevamp.js
  packages/yoroi-extension/app/components/wallet/transactions/Transaction.scss
  packages/yoroi-extension/app/components/wallet/transactions/TransactionRevamp.js
  packages/yoroi-extension/app/components/wallet/transactions/WalletNoTransactionsRevamp.js
  packages/yoroi-extension/app/components/wallet/transactions/WalletTransactionsList.scss
  packages/yoroi-extension/app/components/wallet/transactions/WalletTransactionsListRevamp.js
  packages/yoroi-extension/app/components/widgets/CopyableAddress.scss
  packages/yoroi-extension/app/containers/wallet/WalletEmptyBanner.js
  packages/yoroi-extension/app/containers/wallet/WalletSummaryPage.js
  packages/yoroi-extension/app/containers/wallet/WalletSummaryPage.stories.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js
  packages/yoroi-extension/app/styles/overrides/Button.js
  packages/yoroi-extension/package-lock.json
Labels: UI/UX

#2465 Fixes and disabled revamp
  packages/yoroi-extension/app/App.js
  packages/yoroi-extension/app/assets/images/top-bar/notification.inline.svg
  packages/yoroi-extension/app/components/settings/categories/general-setting/ThemeSettingsBlock.js
  packages/yoroi-extension/app/components/settings/categories/general-setting/ThemeSettingsBlock.scss
  packages/yoroi-extension/app/components/topbar/NavBarRevamp.js
  packages/yoroi-extension/app/components/topbar/NavBarRevamp.scss
  packages/yoroi-extension/app/components/topbar/NavDropdownContentRevamp.js
  packages/yoroi-extension/app/components/topbar/NavPlate.js
  packages/yoroi-extension/app/components/topbar/WalletCard.js
  packages/yoroi-extension/app/components/topbar/WalletCard.scss
  packages/yoroi-extension/app/components/topbar/WalletListDialog.js
  packages/yoroi-extension/app/components/wallet/my-wallets/WalletsList.js
  packages/yoroi-extension/app/components/wallet/my-wallets/WalletsList.scss
  packages/yoroi-extension/app/components/wallet/summary/WalletSummaryRevamp.js
  packages/yoroi-extension/app/components/wallet/transactions/Transaction.js
  packages/yoroi-extension/app/components/wallet/transactions/TransactionRevamp.js
  packages/yoroi-extension/app/containers/NavBarContainer.js
  packages/yoroi-extension/app/containers/wallet/MyWalletsPage.js
  packages/yoroi-extension/app/containers/wallet/WalletEmptyBanner.js
  packages/yoroi-extension/app/i18n/global-messages.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/styles/context/layout.js
Labels: UI/UX

#2467 Redesign receive page
  packages/yoroi-extension/app/components/layout/TopBarLayout.scss
  packages/yoroi-extension/app/components/wallet/layouts/ReceiveWithNavigation.js
  packages/yoroi-extension/app/components/wallet/layouts/ReceiveWithNavigation.scss
  packages/yoroi-extension/app/components/wallet/send/WalletSendForm.scss
  packages/yoroi-extension/app/styles/context/layout.js
  packages/yoroi-extension/app/styles/globalStyles.js
Labels: UI/UX

#2469 Refactor layout components to mui styles
  packages/yoroi-extension/app/components/layout/BackgroundColoredLayout.js
  packages/yoroi-extension/app/components/layout/BackgroundColoredLayout.scss
  packages/yoroi-extension/app/components/layout/CenteredLayout.js
  packages/yoroi-extension/app/components/layout/CenteredLayout.scss
  packages/yoroi-extension/app/components/layout/GridFlexContainer.scss
  packages/yoroi-extension/app/components/layout/HorizontalFlexContainer.js
  packages/yoroi-extension/app/components/layout/HorizontalFlexContainer.scss
  packages/yoroi-extension/app/components/layout/TopBarLayout.js
  packages/yoroi-extension/app/components/layout/TopBarLayout.scss
  packages/yoroi-extension/app/components/layout/VerticalFlexContainer.js
  packages/yoroi-extension/app/components/layout/VerticalFlexContainer.scss
  packages/yoroi-extension/app/components/layout/VerticallyCenteredLayout.js
  packages/yoroi-extension/app/components/layout/VerticallyCenteredLayout.scss
Labels: UI/UX
