Repository Emurgo/yoroi-frontend, pull requests merged in 2021-08, with the labels that each got.

#2246 Ergo number Values to be encoded as strings
  install-all.sh
  packages/yoroi-ergo-connector/example/index.js
  packages/yoroi-ergo-connector/example/package-lock.json
  packages/yoroi-ergo-connector/example/package.json
  packages/yoroi-ergo-connector/package-lock.json
  packages/yoroi-ergo-connector/package.json
  packages/yoroi-extension/app/api/ergo/index.js
  packages/yoroi-extension/app/api/ergo/lib/state-fetch/mockNetwork.js
  packages/yoroi-extension/app/api/ergo/lib/state-fetch/remoteFetcher.js
  packages/yoroi-extension/app/api/ergo/lib/state-fetch/types.js
  packages/yoroi-extension/app/api/ergo/lib/storage/bridge/tests/simpleTxs.test.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/utils.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/utxoTransaction.test.js
  packages/yoroi-extension/app/ergo-connector/containers/ConnectContainer.js
  packages/yoroi-extension/app/ergo-connector/containers/SignTxContainer.stories.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/chrome/extension/ergo-connector/types.js
  packages/yoroi-extension/features/mock-chain/mockErgoImporter.js
  packages/yoroi-extension/flow-typed/npm/ergo-lib-wasm-browser_vx.x.x.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
  packages/yoroi-extension/stories/helpers/ergo/ErgoMocks.js
Labels: dapp-connector, ergo

#2260 [NIGHTLY ONLY] Patch to allow to ignore Catalyst registration starting and ending date
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
Labels: nightly

#2293 Nightly / 4.6.001 (Connector 0.6.001)
  README.md
  packages/yoroi-ergo-connector/package-lock.json
  packages/yoroi-ergo-connector/package.json
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/traitUtils.js
  packages/yoroi-extension/app/api/ada/lib/storage/database/transactionModels/multipart/api/read.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.test.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/trezorTx.js
  packages/yoroi-extension/app/api/ergo/index.js
  packages/yoroi-extension/app/api/ergo/lib/state-fetch/remoteFetcher.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/utxoTransaction.js
  packages/yoroi-extension/app/api/ergo/lib/transactions/utxoTransaction.test.js
  packages/yoroi-extension/app/components/profile/uri-prompt/UriPromptForm.js
  packages/yoroi-extension/app/components/profile/uri-prompt/UriPromptForm.scss
  packages/yoroi-extension/app/components/profile/uri-prompt/UriSkip.js
  packages/yoroi-extension/app/components/profile/uri-prompt/UriSkip.scss
  packages/yoroi-extension/app/components/wallet/transactions/Transaction.js
  packages/yoroi-extension/app/components/wallet/voting/Voting.js
  packages/yoroi-extension/app/containers/profile/UriPromptPage.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/app/domain/CardanoShelleyTransaction.js
  packages/yoroi-extension/app/domain/TrezorLocalizedError.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/features/mock-trezor-connect/index.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: nightly, release

#2229 Add the get_balance function to the CardanoAPI class
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
Labels: dapp-connector

#2295 Release / 4.6.100
  packages/yoroi-extension/app/api/ergo/lib/state-fetch/mockNetwork.js
  packages/yoroi-extension/app/components/wallet/send/WalletSendForm.js
  packages/yoroi-extension/app/components/wallet/send/WalletSendForm.scss
  packages/yoroi-extension/app/components/widgets/tokenOption/TokenOptionRow.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/chrome/extension/ergo-connector/utils.js
  packages/yoroi-extension/features/step_definitions/transactions-steps.js
  packages/yoroi-extension/features/support/webdriver.js
  packages/yoroi-extension/features/transactions.feature
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2296 Catalyst round info integration
  packages/yoroi-extension/app/api/ada/lib/state-fetch/IFetcher.js
  packages/yoroi-extension/app/api/ada/lib/state-fetch/batchedFetcher.js
  packages/yoroi-extension/app/api/ada/lib/state-fetch/remoteFetcher.js
  packages/yoroi-extension/app/api/ada/lib/state-fetch/types.js
  packages/yoroi-extension/app/api/common/errors.js
  packages/yoroi-extension/app/containers/wallet/voting/RegistrationOver.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.stories.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/stores/ada/VotingStore.js
Labels: catalyst

#2207 Adapt to Alonzo version of cardano-serialization-lib
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/lib/cardanoCrypto/catalyst.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/metadataUtils.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/updateTransactions.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/HaskellShelleyTxSignRequest.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/ledgerTx.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.test.js
  packages/yoroi-extension/app/stores/ada/send/LedgerSendStore.js
  packages/yoroi-extension/features/mock-ledger-connect/index.js
  packages/yoroi-extension/features/mock-trezor-connect/index.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: alonzo
