Repository Emurgo/yoroi-frontend, pull requests merged in 2021-12, with the labels that each got.

#2471 Add staking page revamp
  packages/yoroi-extension/app/Routes.js
  packages/yoroi-extension/app/actions/common/transactions-actions.js
  packages/yoroi-extension/app/assets/fonts/Rubik-Bold.ttf
  packages/yoroi-extension/app/assets/fonts/Rubik-Light.ttf
  packages/yoroi-extension/app/assets/fonts/Rubik-Medium.ttf
  packages/yoroi-extension/app/assets/fonts/Rubik-Regular.ttf
  packages/yoroi-extension/app/assets/images/question-mark.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/discord.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/facebook.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/github.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/personal.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/telegram.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/twitch.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/twitter.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/youtube.inline.svg
  packages/yoroi-extension/app/components/layout/TopBarLayout.js
  packages/yoroi-extension/app/components/topbar/NavBarRevamp.js
  packages/yoroi-extension/app/components/topbar/NavDropdownRevamp.scss
  packages/yoroi-extension/app/components/wallet/staking/dashboard/StakingDashboard.js
  packages/yoroi-extension/app/containers/transfer/Transfer.js
  packages/yoroi-extension/app/containers/wallet/Wallet.js
  packages/yoroi-extension/app/containers/wallet/WalletDelegationBanner.js
  packages/yoroi-extension/app/containers/wallet/staking/CardanoStakingPage.js
  packages/yoroi-extension/app/containers/wallet/staking/SeizaFetcher.js
  packages/yoroi-extension/app/containers/wallet/staking/StakingPage.js
  packages/yoroi-extension/app/i18n/global-messages.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/routes-config.js
  packages/yoroi-extension/app/stores/stateless/sidebarCategories.js
  packages/yoroi-extension/app/stores/stateless/topbarCategories.js
  packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js
  packages/yoroi-extension/app/styles/overrides/Button.js
  packages/yoroi-extension/chrome/constants.js
Labels: UI/UX

#2521 Staking Page Revamp: Add Cards and Overview Modal
  packages/yoroi-extension/app/assets/images/dashboard/staking-active.inline.svg
  packages/yoroi-extension/app/assets/images/dashboard/total-delegated.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/discord.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/facebook.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/github.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/linkedin.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/medium.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/personal.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/telegram.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/twitch.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/twitter.inline.svg
  packages/yoroi-extension/app/assets/images/social/revamp/youtube.inline.svg
  packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/DelegatedStakePoolCard.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/OverviewDialog.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/StakePool/StakePool.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/StakePool/StakePool.styles.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/StakingTabs.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/SummaryCard.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard/UpcomingRewards.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard/UserSummary.js
  packages/yoroi-extension/app/containers/wallet/WalletDelegationBanner.js
  packages/yoroi-extension/app/containers/wallet/staking/CardanoStakingPage.js
  packages/yoroi-extension/app/containers/wallet/staking/SeizaFetcher.js
  packages/yoroi-extension/app/containers/wallet/staking/StakingPage.js
  packages/yoroi-extension/app/i18n/global-messages.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
Labels: UI/UX

#2528 Revamp: Assets page - Token
  packages/yoroi-extension/app/Routes.js
  packages/yoroi-extension/app/assets/images/link.inline.svg
  packages/yoroi-extension/app/components/topbar/SubMenuItem.scss
  packages/yoroi-extension/app/components/wallet/assets/AssetsList.js
  packages/yoroi-extension/app/components/wallet/assets/AssetsMenu.js
  packages/yoroi-extension/app/components/wallet/assets/TokenDetails.js
  packages/yoroi-extension/app/components/wallet/assets/TokenList.js
  packages/yoroi-extension/app/components/wallet/assets/Tokens.js
  packages/yoroi-extension/app/components/widgets/CopyToClipboardLabel.js
  packages/yoroi-extension/app/components/widgets/CopyableAddress.js
  packages/yoroi-extension/app/containers/wallet/AssetsWrapper.js
  packages/yoroi-extension/app/containers/wallet/TokenDetailPageRevamp.js
  packages/yoroi-extension/app/containers/wallet/TokensPageRevamp.js
  packages/yoroi-extension/app/i18n/global-messages.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/routes-config.js
  packages/yoroi-extension/app/stores/stateless/sidebarCategories.js
Labels: UI/UX

#2555 [4.8.1] Trailing zeros fix
  packages/yoroi-extension/app/components/topbar/NavWalletDetails.js
  packages/yoroi-extension/app/components/wallet/send/WalletSendForm.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard/UserSummary.js
  packages/yoroi-extension/app/containers/wallet/WalletAssetsPage.js
  packages/yoroi-extension/app/stores/stateless/tokenHelpers.js
  packages/yoroi-extension/app/utils/formatters.js
  packages/yoroi-extension/app/utils/formatters.test.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release, hotfix

#2561 [4.8.2] Do not retain the whole tx list in memory permanently
  install-all.sh
  packages/yoroi-extension/app/api/common/index.js
  packages/yoroi-extension/app/stores/base/BaseCoinPriceStore.js
  packages/yoroi-extension/app/stores/toplevel/CoinPriceStore.js
  packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js
  packages/yoroi-extension/app/stores/toplevel/WalletStore.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
  packages/yoroi-extension/stories/helpers/cardano/ByronMocks.js
  packages/yoroi-extension/stories/helpers/cardano/ShelleyCip1852Mocks.js
  packages/yoroi-extension/stories/helpers/ergo/ErgoMocks.js
  packages/yoroi-extension/stories/helpers/jormungandr/JormungandrMocks.js
  run-dev.sh
Labels: release, hotfix

#2584 Release / 4.8.3
  packages/yoroi-extension/app/api/ada/transactions/shelley/ledgerTx.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard/StakingDashboard.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2588 [dapp connector]make the wallet list scrollable
  packages/yoroi-extension/app/ergo-connector/components/connect/ConnectPage.scss
Labels: dapp-connector
