Repository Emurgo/yoroi-frontend, pull requests merged in 2022-08, with the labels that each got.

#2949 [4.15.200] Fund message hotfix
  packages/yoroi-extension/app/api/ada/lib/state-fetch/types.js
  packages/yoroi-extension/app/components/wallet/voting/Voting.js
  packages/yoroi-extension/app/containers/wallet/voting/VotingPage.js
  packages/yoroi-extension/app/i18n/locales/cs-CZ.json
  packages/yoroi-extension/app/i18n/locales/de-DE.json
  packages/yoroi-extension/app/i18n/locales/el-GR.json
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/i18n/locales/es-ES.json
  packages/yoroi-extension/app/i18n/locales/fr-FR.json
  packages/yoroi-extension/app/i18n/locales/hr-HR.json
  packages/yoroi-extension/app/i18n/locales/id-ID.json
  packages/yoroi-extension/app/i18n/locales/it-IT.json
  packages/yoroi-extension/app/i18n/locales/ja-JP.json
  packages/yoroi-extension/app/i18n/locales/ko-KR.json
  packages/yoroi-extension/app/i18n/locales/nl-NL.json
  packages/yoroi-extension/app/i18n/locales/pt-BR.json
  packages/yoroi-extension/app/i18n/locales/ru-RU.json
  packages/yoroi-extension/app/i18n/locales/sk-SK.json
  packages/yoroi-extension/app/i18n/locales/tr-TR.json
  packages/yoroi-extension/app/i18n/locales/zh-Hans.json
  packages/yoroi-extension/app/i18n/locales/zh-Hant.json
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release, hotfix

#2914 Upgrade to SerLib 11 (Babbage)
  packages/yoroi-ergo-connector/example-cardano/package-lock.json
  packages/yoroi-ergo-connector/example-cardano/package.json
  packages/yoroi-extension/app/api/ada/transactions/shelley/coinSelection.test.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.test.js
  packages/yoroi-extension/app/api/common/errors.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: babbage

#2956 Fix min ada calculation
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/stores/toplevel/TransactionBuilderStore.js
Labels: in-testing

#2957 Not allowing tx-building when token amount is zero
  packages/yoroi-extension/app/stores/toplevel/TransactionBuilderStore.js
Labels: in-testing

#2953 Release / 4.16
  .github/workflows/tests.yml
  .github/workflows/tests_hw_emulators.yml
  packages/yoroi-ergo-connector/example-cardano/package-lock.json
  packages/yoroi-ergo-connector/example-cardano/package.json
  packages/yoroi-extension/app/App.js
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/coinSelection.test.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.test.js
  packages/yoroi-extension/app/api/analytics/index.js
  packages/yoroi-extension/app/api/common/errors.js
  packages/yoroi-extension/app/api/localStorage/index.js
  packages/yoroi-extension/app/components/buySell/BuySellDialog.js
  packages/yoroi-extension/app/components/wallet/send/WalletSendFormSteps/WalletSendPreviewStepContainer.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/EpochProgressCard.js
  packages/yoroi-extension/app/components/wallet/staking/dashboard-revamp/StakingTabs.js
  packages/yoroi-extension/app/containers/profile/UriPromptPage.js
  packages/yoroi-extension/app/containers/settings/categories/BlockchainSettingsPage.js
  packages/yoroi-extension/app/containers/settings/categories/GeneralSettingsPage.js
  packages/yoroi-extension/app/containers/settings/categories/RemoveWalletDialogContainer.js
  packages/yoroi-extension/app/containers/settings/categories/ResyncWalletDialogContainer.js
  packages/yoroi-extension/app/containers/settings/categories/WalletSettingsPage.js
  packages/yoroi-extension/app/containers/transfer/WithdrawalTxDialogContainer.js
  packages/yoroi-extension/app/containers/transfer/YoroiTransferPage.stories.js
  packages/yoroi-extension/app/containers/wallet/WalletSendPage.js
  packages/yoroi-extension/app/containers/wallet/dialogs/WalletSendConfirmationDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/staking/CardanoStakingPage.js
  packages/yoroi-extension/app/containers/wallet/staking/StakingDashboardPage.stories.js
  packages/yoroi-extension/app/containers/wallet/staking/StakingPage.js
  packages/yoroi-extension/app/routes-config.js
  packages/yoroi-extension/app/stores/ada/AdaDelegationTransactionStore.js
  packages/yoroi-extension/app/stores/ada/AdaWalletRestoreStore.js
  packages/yoroi-extension/app/stores/ada/AdaWalletsStore.js
  packages/yoroi-extension/app/stores/ada/LedgerConnectStore.js
  packages/yoroi-extension/app/stores/ada/TrezorConnectStore.js
  packages/yoroi-extension/app/stores/ada/VotingStore.js
  packages/yoroi-extension/app/stores/base/BaseProfileStore.js
  packages/yoroi-extension/app/stores/toplevel/TransactionBuilderStore.js
  packages/yoroi-extension/chrome/constants.js
  packages/yoroi-extension/chrome/extension/index.js
  packages/yoroi-extension/features/step_definitions/common-steps.js
  packages/yoroi-extension/features/step_definitions/connector-steps.js
  packages/yoroi-extension/features/support/helpers/helpers.js
  packages/yoroi-extension/features/support/webdriver.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2969 [4.16.100] hotfix - serlib upgrade
  packages/yoroi-ergo-connector/example-cardano/package-lock.json
  packages/yoroi-ergo-connector/example-cardano/package.json
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release, hotfix

#2972 [4.16.200] Ledger ff fix
  packages/yoroi-extension/app/utils/hwConnectHandler.js
  packages/yoroi-extension/ledger/const.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: hotfix

#2975 [4.16.300] Serlib upgrade
  packages/yoroi-ergo-connector/example-cardano/package-lock.json
  packages/yoroi-ergo-connector/example-cardano/package.json
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: hotfix

#2980 Making the Voting page accessible from the revamp
  packages/yoroi-extension/app/containers/wallet/Wallet.js
  packages/yoroi-extension/app/routes-config.js
  packages/yoroi-extension/app/stores/stateless/topbarCategories.js
Labels: bug (confirmed)
