Repository Emurgo/yoroi-frontend, pull requests merged in 2022-03, with the labels that each got.

#2758 Release / 4.11.200
  packages/yoroi-extension/.gitignore
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/tests/utils.test.js
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/utils.js
  packages/yoroi-extension/app/assets/images/down-arrow.inline.svg
  packages/yoroi-extension/app/components/experimental/YoroiPalette/YoroiPalette.js
  packages/yoroi-extension/app/components/experimental/YoroiPalette/YoroiPalette.scss
  packages/yoroi-extension/app/components/topbar/WalletListDialog.scss
  packages/yoroi-extension/app/containers/NavBarContainerRevamp.js
  packages/yoroi-extension/app/ergo-connector/components/connect/ConnectPage.js
  packages/yoroi-extension/app/ergo-connector/components/connect/ConnectPage.scss
  packages/yoroi-extension/app/ergo-connector/components/signin/SignTxPage.scss
  packages/yoroi-extension/app/ergo-connector/components/signin/UtxoDetails.scss
  packages/yoroi-extension/app/ergo-connector/containers/ConnectContainer.js
  packages/yoroi-extension/app/styles/globalStyles.js
  packages/yoroi-extension/features/daedalus-transfer.feature
  packages/yoroi-extension/features/dashboard.feature
  packages/yoroi-extension/features/hardware.feature
  packages/yoroi-extension/features/main-ui.feature
  packages/yoroi-extension/features/migration.feature
  packages/yoroi-extension/features/mock-trezor-connect/index.js
  packages/yoroi-extension/features/settings-ui.feature
  packages/yoroi-extension/features/step_definitions/common-steps.js
  packages/yoroi-extension/features/step_definitions/daedalus-transfer-steps.js
  packages/yoroi-extension/features/step_definitions/general-settings-steps.js
  packages/yoroi-extension/features/step_definitions/hardware-steps.js
  packages/yoroi-extension/features/step_definitions/installation-procedure-steps.js
  packages/yoroi-extension/features/step_definitions/main-ui-steps.js
  packages/yoroi-extension/features/step_definitions/memo-steps.js
  packages/yoroi-extension/features/step_definitions/select-language-steps.js
  packages/yoroi-extension/features/step_definitions/settings-ui-steps.js
  packages/yoroi-extension/features/step_definitions/transactions-steps.js
  packages/yoroi-extension/features/step_definitions/tx-history-steps.js
  packages/yoroi-extension/features/step_definitions/uri-steps.js
  packages/yoroi-extension/features/step_definitions/wallet-creation-steps.js
  packages/yoroi-extension/features/step_definitions/wallet-delegation-steps.js
  packages/yoroi-extension/features/step_definitions/wallet-paper-steps.js
  packages/yoroi-extension/features/step_definitions/wallet-restoration-steps.js
  packages/yoroi-extension/features/step_definitions/wallet-steps.js
  packages/yoroi-extension/features/step_definitions/yoroi-transfer-steps.js
  packages/yoroi-extension/features/support/helpers/language-selection-helpers.js
  packages/yoroi-extension/features/support/helpers/transfer-helpers.js
  packages/yoroi-extension/features/support/webdriver.js
  packages/yoroi-extension/features/uri-scheme.feature
  packages/yoroi-extension/features/wallet-creation.feature
  packages/yoroi-extension/features/wallet-restoration.feature
  packages/yoroi-extension/features/yoroi-transfer.feature
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2631 Redesign dapp connector 2
  packages/yoroi-extension/app/ergo-connector/components/connect/WalletCard.js
  packages/yoroi-extension/app/ergo-connector/components/layout/Layout.js
  packages/yoroi-extension/app/ergo-connector/components/signin/CardanoSignTxPage.js
  packages/yoroi-extension/app/ergo-connector/components/signin/CardanoUtxoDetails.js
  packages/yoroi-extension/app/ergo-connector/components/signin/SignTxPage.js
  packages/yoroi-extension/app/ergo-connector/components/signin/SignTxPage.scss
  packages/yoroi-extension/app/ergo-connector/components/signin/SignTxTabs.js
  packages/yoroi-extension/app/ergo-connector/components/signin/UtxoDetails.js
  packages/yoroi-extension/app/ergo-connector/components/signin/UtxoDetails.scss
  packages/yoroi-extension/app/ergo-connector/containers/SignTxContainer.js
  packages/yoroi-extension/app/ergo-connector/containers/SignTxContainer.stories.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
Labels: dapp-connector

#2766 Release / 4.11.300
  packages/yoroi-ergo-connector/example-cardano/index.js
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/components/wallet/send/WalletSendForm.js
  packages/yoroi-extension/app/coreUtils.js
  packages/yoroi-extension/app/ergo-connector/components/connect/WalletCard.js
  packages/yoroi-extension/app/ergo-connector/components/layout/Layout.js
  packages/yoroi-extension/app/ergo-connector/components/signin/CardanoSignTxPage.js
  packages/yoroi-extension/app/ergo-connector/components/signin/CardanoUtxoDetails.js
  packages/yoroi-extension/app/ergo-connector/components/signin/SignTxPage.js
  packages/yoroi-extension/app/ergo-connector/components/signin/SignTxPage.scss
  packages/yoroi-extension/app/ergo-connector/components/signin/SignTxTabs.js
  packages/yoroi-extension/app/ergo-connector/components/signin/UtxoDetails.js
  packages/yoroi-extension/app/ergo-connector/components/signin/UtxoDetails.scss
  packages/yoroi-extension/app/ergo-connector/containers/SignTxContainer.js
  packages/yoroi-extension/app/ergo-connector/containers/SignTxContainer.stories.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/app/stores/stateless/tokenHelpers.js
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2770 Release / 4.11.400
  packages/yoroi-extension/app/actions/ada/ledger-send-actions.js
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/ledgerTx.js
  packages/yoroi-extension/app/api/ergo/index.js
  packages/yoroi-extension/app/api/localStorage/index.js
  packages/yoroi-extension/app/components/wallet/transactions/Transaction.js
  packages/yoroi-extension/app/components/wallet/transactions/WalletTransactionsList.js
  packages/yoroi-extension/app/containers/transfer/UpgradeTxDialogContainer.js
  packages/yoroi-extension/app/containers/wallet/WalletSummaryPage.js
  packages/yoroi-extension/app/domain/CardanoShelleyTransaction.js
  packages/yoroi-extension/app/domain/ErgoTransaction.js
  packages/yoroi-extension/app/stores/ada/AdaTransactionsStore.js
  packages/yoroi-extension/app/stores/ada/send/LedgerSendStore.js
  packages/yoroi-extension/app/stores/ada/send/TrezorSendStore.js
  packages/yoroi-extension/app/stores/toplevel/TokenInfoStore.js
  packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2713 connector collateral API
  packages/yoroi-ergo-connector/example-cardano/index.html
  packages/yoroi-ergo-connector/example-cardano/index.js
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/app/api/ada/index.js
  packages/yoroi-extension/app/ergo-connector/components/signin/CardanoSignTxPage.js
  packages/yoroi-extension/app/ergo-connector/containers/ConnectContainer.js
  packages/yoroi-extension/app/ergo-connector/containers/SignTxContainer.js
  packages/yoroi-extension/app/ergo-connector/containers/SignTxContainer.stories.js
  packages/yoroi-extension/app/ergo-connector/stores/ConnectorStore.js
  packages/yoroi-extension/app/ergo-connector/types.js
  packages/yoroi-extension/app/i18n/locales/en-US.json
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/chrome/extension/ergo-connector/types.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
  run-cardano-example-dapp.sh
Labels: dapp-connector

#2783 don't sync wallet for signHexPayload
  packages/yoroi-extension/chrome/extension/background.js
Labels: dapp-connector

#2776 Fix old signing with old addresses
  packages/yoroi-extension/app/api/ada/lib/storage/bridge/utils.js
  packages/yoroi-extension/app/ergo-connector/stores/ConnectorStore.js
  packages/yoroi-extension/app/styles/globalStyles.js
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/types.js
Labels: bug (confirmed), dapp-connector

#2792 Hotfix / 4.11.410
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: hotfix
