Repository Emurgo/yoroi-frontend, pull requests merged in 2022-04, with the labels that each got.

#2809 [4.11.500] adapt to ledgerjs 5.0.0 API changes
  packages/yoroi-extension/app/stores/ada/HWVerifyAddressStore.js
  packages/yoroi-extension/app/stores/ada/LedgerConnectStore.js
  packages/yoroi-extension/app/stores/ada/send/LedgerSendStore.js
  packages/yoroi-extension/features/mock-ledger-connect/index.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release

#2827 [4.11.600] Fix wallet sync bug and sync all wallets in the background
  packages/yoroi-extension/app/api/common/index.js
  packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js
  packages/yoroi-extension/app/stores/toplevel/WalletSettingsStore.js
  packages/yoroi-extension/app/stores/toplevel/WalletStore.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: release, hotfix

#2737 Collateral coin-selection
  packages/yoroi-ergo-connector/example-cardano/package-lock.json
  packages/yoroi-ergo-connector/example-cardano/package.json
  packages/yoroi-ergo-connector/src/inject.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/coinSelection.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/coinSelection.test.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.js
  packages/yoroi-extension/app/api/ada/transactions/shelley/transactions.test.js
  packages/yoroi-extension/app/api/ada/transactions/utils.js
  packages/yoroi-extension/app/api/common/lib/MultiToken.js
  packages/yoroi-extension/chrome/extension/background.js
  packages/yoroi-extension/chrome/extension/ergo-connector/api.js
  packages/yoroi-extension/package-lock.json
  packages/yoroi-extension/package.json
Labels: dapp-connector

#2833 [4.12.100] Fix bug on wallet loader
  packages/yoroi-extension/app/stores/toplevel/TransactionsStore.js
  packages/yoroi-extension/app/stores/toplevel/WalletSettingsStore.js
  packages/yoroi-extension/app/stores/toplevel/WalletStore.js
Labels: release
